### ISSUE TITLE
Find location -- DaWanda / Ahoy? 

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#1]

**Comment by martinklepsch** [comment]
I'll check with Red Pineapple regarding ahoy. There's a bigger lobby there that could probably be used.

I think universities and similar institutions might also be interested I'm hosting events like ClojureBridge.

**Comment by nblumoe** [comment]
I might be able to offer space at Futurice. Depending on when this happens and the number of attendees.

Also I could check if we could do it at Beuth Hochschule where we did :clojureD

**Comment by Malwine** [comment]
Dawanda provides 2 rooms (like 15 people each) in Ahoy! 
I just need to inform the Ahoy team.

**Comment by plexus** [comment]
So that's 30 people including coaches,  around 20 attendees. I would've
liked a bit more capacity but could be fine for a first workshop.

**Comment by thatbettina** [comment]
@Malwine - Can you please confirm with DaWanda / Ahoy that we can have the rooms for July? ClojureBridge wants us to have a date and a venue confirmed before they will list us on their website.

**Comment by Malwine** [comment]
Location is confirmed :)

**Comment by plexus** [comment]
Awesomesauce :spaghetti: 

Do you also know how many rooms / tables / couches we'll have available?

**Comment by martinklepsch** [comment]
What about the lobby at Ahoy? If that's not part of the deal yet I could talk to Red Pineapple if they'd be willing to sponsor it. (Fairly confident that they would.)

**EDIT:** This only makes sense if the meeting rooms are also the on the Ahoy floor. Splitting it up over two floors is probably not a very good idea.

**Comment by Malwine** [comment]
So we have two rooms called: 

**Gray Door**: 
- up to 20-25 people
- currently 1 big table(14 people), possible to put in 3 more smaller tables(each 3 people).  

**Glass Door**:
- a bit smaller 
- 2 table tennis desks as tables
- up to 15 people  

**Lobby**
- Ahoy Management said we could use the lobby if we take care that it stays clean. And maybe the cleaning service will be cleaning on Saturday and we need to let them do their work.
- like 3 couches  

All in all thats like **40-50** people maximum. But consider that it could be hot in July and we should pack the rooms too full.

**Comment by thatbettina** [comment]
@Malwine - The three rooms you mention, is that from DaWanda or from Ahoy? I'm going for 45 max participants.

**Comment by Malwine** [comment]
The rooms are in Ahoy but they they belong to DaWanda.

**Comment by thatbettina** [comment]
Closing this story because the location has been confirmed.
