### ISSUE TITLE
Plan Outreach

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#100]
This is a meta issue to co-ordinate the issues needed for our Outreach effort. Relevant issue from last time: #75 

 Suggestions:
- People who missed out before
- Poster design
- Poster spreading
- Email lists (reflectinfo, universities)
- Berliner Fenster?

Please don't add this issue to the project, directly, make an issue for each bullet/mail etc :)

And please suggest things! Would also be good if a pair took over ownership of this issue (and helped to delegate etc, not doing all the work)

**Comment by vsmart** [comment]
I'm happy to take ownership of this one. Who wants to join me?

**Comment by vsmart** [comment]
Closing this as registrations are closed, with 110 signups 🎉
