### ISSUE TITLE
After Party

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#101]
As of #86, part of the problem seen was the lack of a co-ordinated dinner, meaning we lost people on the way to the after party. Might be good to make a dinner reservation. For reference, last time the after party was at Volksbar, and before that, Kaschk.

This is a low priority item, we can do it by 11/11/2016 (two weeks before the workshop).

**Comment by lislis** [comment]
Are there suggestions on how we can co-ordinate dinner? Or if we even want to do that at all?

**Comment by socksy** [comment]
I'm guessing nowhere is going to be big enough/popular enough with everyone that everyone goes together somewhere. Maybe we make a booking at Soy, and have one person take people there, one person goes with people for Falafel place, and that person for each group is in charge of everyone turning up at Volksbar after?

Alternatively, we go straight to Folksbar, then people can splinter off to get food and come back.

**Comment by vsmart** [comment]
I think trying to coordinate dinner is too hard. I think it worked ok like last time. (we go straight to the bar, people can go to buy food & return). 

alternatively: what if the "after party" happens somewhere that has food AND drinks? Like, maybe Due Forni 🍕 ? (we can always have an after-after-party in a bar)

**Comment by socksy** [comment]
If I remember correctly, the problem was that because there was no provision for dinner last time, we lost a lot of people simply because they chose to get dinner instead. I am thinking that doing what happened last time accidentally on purpose instead is probably a good bet — so we specify that we'll be going to go get food in groups after arriving at the bar, then maybe people will be more likely to stay. 

If we go to a place with food and drinks it should be possible to stay there longer term with just drinks, otherwise we end up with the dinner and then drinks problem again :) (Maybe this is what you mean with Due Forni, I've never been).

**Comment by lislis** [comment]
I would like to avoid locations too far away (like Due Forni, that's at almost 30 min by foot with a group) and too much location hopping (go for food and then a bar). 
Say people want to head home and join later, should they go to the food place or the bar?

As @socksy said, I think doing the accidental on purpose would be the least overhead for us

**Comment by vsmart** [comment]
Hmmm, agreed about not too far away, but I think Due Forni is still within the radius. e.g. we go there by foot for lunch often, it's about a 15min walk. But of course, walking with a big group takes longer. 

I think volksbar is a good safe bet. (do mention about non-smoking, since the upstairs area is usually their smoke area)

**Comment by lislis** [comment]
Update: The Volksbar upstairs is already booked but they can reserve the 'Podest' which is in the non-smoking part of the bar. Reservation is under my name starting from 19:00

**Comment by lislis** [comment]
In the end the space they reserved was smaller than expected, but we were also more than anticipated. Since we arrived very early it was to problem to just occupy more tables.
🎉
