### ISSUE TITLE
Poster and Flyers

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#102]
As part of the [outreach](https://github.com/clojurebridge-berlin/organization/issues/75) last time @Malwine designed an [awesome poster & flyer](https://github.com/clojurebridge-berlin/organization/issues/75#issuecomment-217187506). We know it was awesome, because it converted very well to sign-ups after being plastered around the city ;)

**Comment by vsmart** [comment]
What is the work item here @socksy - Is it to design new posters? Or modify the existing posters with updated dates + venue?

**Comment by codebeige** [comment]
@malwine Can you maybe provide me with the original design files?

**Comment by Malwine** [comment]
hej @codebeige 😊 
I did that with [sketch](https://www.sketchapp.com/). I zipped the a sketch files for poster and flyers plus the drawing. You can also recreate the poster with another tool by copying and pasting from the first poster pdf if you like. 

The text could definitely have a more suitable update. We could lay a focus on the creative part of the workshop for example.
[clojurebridge-poster-material.zip](https://github.com/clojurebridge-berlin/organization/files/516357/clojurebridge-poster-material.zip)

**Comment by codebeige** [comment]
I wanted to emphasize the creative part and have a more emotional appeal. So I ended up with something completely different. Hope you  like it.

It's on a non-standardized format, namely 320 × 424 mm.

[161014 Poster.pdf](https://github.com/clojurebridge-berlin/organization/files/529878/161014.Poster.pdf)

**Comment by codebeige** [comment]
Here a PNG for quick preview:

![161014 poster](https://cloud.githubusercontent.com/assets/91858/19393612/c2eac672-9235-11e6-8123-4f3be017ec6f.png)

**Comment by codebeige** [comment]
Ups, missed a comma at "Du möchtest wissen, wie das alles funktioniert …" Fixed.

**Comment by martinklepsch** [comment]
This is pretty cool 👍  maybe there could be a smaller, landscape version of it too that could be shared on Twitter. Because images. :)

**Comment by codebeige** [comment]
Another round of text edit and typo fixes …

![161014 poster 2](https://cloud.githubusercontent.com/assets/91858/19394070/cee4b530-9237-11e6-9053-3879347f5cc4.png)

**Comment by codebeige** [comment]
@martinklepsch I will first go for the flyers now. They will probably be landscape, but I can later produce some other images as well.

**Comment by codebeige** [comment]
Here is my take on the flyers: 
[161014 Flyer.pdf](https://github.com/clojurebridge-berlin/organization/files/530041/161014.Flyer.pdf)

**Comment by codebeige** [comment]
![161014 flyer back](https://cloud.githubusercontent.com/assets/91858/19396177/002f439e-9242-11e6-9c95-dffce86c4f81.png)
![161014 flyer front](https://cloud.githubusercontent.com/assets/91858/19396178/005f3cb6-9242-11e6-876a-a3b25d2288d2.png)

**Comment by vsmart** [comment]
@codebeige they look really cool! I Iike it! 👏 ❤️ 

Some small copy edits: Please change "Frauen und nicht-binaer identifizierte Menschen" to "**Frauen**\* und **nicht-binäre Menschen**".

Might make sense to put "Twitter" or the twitter icon before the handle - otherwise people don't know what it is.

**Comment by codebeige** [comment]
I made the headline more prominent and included the text changes. Looks pretty final to me now.

[161014 Poster and Flyer (v3).pdf](https://github.com/clojurebridge-berlin/organization/files/530105/161014.Poster.and.Flyer.v3.pdf)

**Comment by codebeige** [comment]
![161014 poster v3](https://cloud.githubusercontent.com/assets/91858/19397089/9649b888-9246-11e6-832a-1f8ec02c6b3b.png)

**Comment by codebeige** [comment]
![161014 flyer front v3](https://cloud.githubusercontent.com/assets/91858/19397097/a02fc324-9246-11e6-924d-750a7715ec4a.png)

**Comment by codebeige** [comment]
![161014 flyer back v3](https://cloud.githubusercontent.com/assets/91858/19397111/aaf4905a-9246-11e6-8ee2-3670286a438d.png)

**Comment by codebeige** [comment]
I plan to order 50 posters 4/0, 320 × 424 mm, 115 g, uncoated (~ € 90) and 500 flyers 4/4, DIN long, 135 g uncoated (~ € 50) at [Pinguindruck](https://pinguindruck.de). In order to get them in time, I have to upload the final documents until Monday 10:00 a.m. latest. But I would rather prefer to do so tomorrow evening.

**Comment by codebeige** [comment]
Woman -> Women

[161014 Poster and Flyer (v4).pdf](https://github.com/clojurebridge-berlin/organization/files/530140/161014.Poster.and.Flyer.v4.pdf)

**Comment by codebeige** [comment]
This is the fInal artwork that will be uploaded to the printer:

[161015 Flyer Reinzeichnung.pdf](https://github.com/clojurebridge-berlin/organization/files/531417/161015.Flyer.Reinzeichnung.pdf)
[161015 Poster Reinzeichnung.pdf](https://github.com/clojurebridge-berlin/organization/files/531418/161015.Poster.Reinzeichnung.pdf)

**Comment by codebeige** [comment]
FInally placed the order of 1000 flyers and 75 posters with a total cost of 130,85 € at [Pinguindruck](https://pinguindruck.de). Will be delivered to Wunderlist on Wednesday, October 19 between 10:00 am and 4:00 pm. @vsmart I will fill you in with more details on Slack.

**Comment by plexus** [comment]
👍
