### ISSUE TITLE
Decide how to handle sponsors this time

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#103]
Obviously related to #98, last time we did a system of sponsors involving tiers, which you can find [detailed on our sponsor page](http://clojurebridge-berlin.org/sponsor-us/). 

At the very least, we need to update this away from the notebooks, which thanks to Babbel we have plenty of :) But we should also discuss whether the tier system worked. 

Part of the reasoning of it was to change from a mental price list which included all our costs to a more abstract one, where it's easier to point a sponsor to "hey we need to get this amount of money that hasn't been achieved yet".

However, it did lead to confusion when fundraising, people where not in sync with which tiers were which and it's kind of hard to offer different benefits for different tiers. It's also been absurdly difficult to deal with getting sponsors to pay for things directly (excepting @nicsnet's fantastic dealing with her employer).

This is something that ideally needs to be sorted out before we start contacting people on #98. Can we discuss this next week at the core meeting?

**Comment by plexus** [comment]
> It's also been absurdly difficult to deal with getting sponsors to pay for things directly

What are you referring to here? As far as I remember we've had a lot of good experiences in the past with this. 

> Part of the reasoning of it was to change from a mental price list which included all our costs to a more abstract one

Personally I'm all for keeping the tier system, it gives potential sponsors a clear choice, so they can see what fits in their budget. Before that are message was basically "these are out costs, tell us how much you want to pitch in". That works sometimes for companies that we know personally, but it's generally counterintuitive for business people. They want to see a price list.

**Comment by vsmart** [comment]
- 1 for keeping the tier system. 

I'd like to clarify the tiers a bit on the website. Have set up an issue for this: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/30 

Do you have any further concerns for this ? Otherwise we can close this issue.

**Comment by plexus** [comment]
I had a look at your changes to the website @vsmart, thanks a lot, that does clarify things.

For larger sums I would still highly recommend to try to get the company to pay a supplier directly, because
- it's generally less (paper)work for us
- it's easier to explain, big companies are used to seeing invoices, they get very confused when talking about donation receipts (cfr. Zalando)
- more "net" sponsorship because we don't have to deduct the fee for Travis
- anything that goes through Travis I tend to pay myself first so that I can bundle up the receipts, that's not something I can do on 500+ euro amounts

**Comment by vsmart** [comment]
@plexus totally, agree! I did try to decouple the direct sponsorship vs "add to the bucket" from the tiers a bit in my PR, I think that discussion is independent of the amount. if we get a direct sponsor for a 200 bill that's also cool I think.

**Comment by vsmart** [comment]
@socksy @plexus can we close this?

**Comment by socksy** [comment]
Yes :)
