### ISSUE TITLE
New caterer

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#104]
Someone that
- Understands catering on time for specific large number of people
- Understands veganism

**Comment by Realtin** [comment]
- [Sfizy Veg](http://sfizyveg.de/catering) _Pizza, Salads, Pasta_
- [noTiers](http://notiers.de/)  <-- this looks amazing and they are professional caterers!

**Comment by vsmart** [comment]
I will ask our office manager for contacts of one of our usual team lunch caterers who makes great vegan food. 
I also think we should consider the caterer from the first workshop again.

**Comment by plexus** [comment]
Caterer for the first workshop was

> Miriam Lappenberg 
> Café Federica 
> Reichenberger Str. 61a 
> D-10999 Berlin 
> Tel. 030/61209643 
> Mob. +49(0)157 30102948

I agree they did a good job. We paid 10 EUR per person for lunch.

**Comment by vsmart** [comment]
http://www.bleibtreu-catering.de/catering2/ 

this is the caterer I was referring to. They do pretty good vegan food.

**Comment by vsmart** [comment]
Also Suppenkult is the soup place we had in Jan. Soup might be nice for coaches training or installfest. http://suppen-cult.de/index.php?page=2 (not substantial enough for lunch I guess)

**Comment by vsmart** [comment]
Closing this as we decided on caterers: Knofi and Suppenkult. 
We still have individual issues for Catering: https://github.com/clojurebridge-berlin/organization/issues/107 and https://github.com/clojurebridge-berlin/organization/issues/108
