### ISSUE TITLE
Breakfast

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#106]
Last time we had "30 chocolate muffins, 30 carrot cake muffins, 30 vollkornbrötchen", but this time we should reduce vollkornbrötchen. Maybe vegan croissants?

**Comment by vsmart** [comment]
@lislis and I  went to the bakery to enquire about vegan breakfast options. 

They still do muffins. Regarding savoury options, we could get vegan Brezels, different kinds of bread rolls, possibly Mueslistangen (contain honey). They don't have croissants or similar. 

My proposal: 
35 chocolate muffins
35 carrot cake muffins
15 Brezels 
15 white bread rolls
15 whole wheat bread roll
selection of vegan spreads
selection of fruits (bananas + apples) 

Please 👍 if this sounds good, or comment with improvements

**Comment by vsmart** [comment]
I ordered breakfast today (as listed above) , and will buy spreads + fruits on Friday. Closing this 🎉
