### ISSUE TITLE
Coaches and Installfest catering

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#107]

**Comment by Realtin** [comment]
How many people are we estimating for the **Coaches Training**?  
We said we aim for 25 coaches, right? So about 15 will show up plus about 5 from us.
**Food for 20 people**? or you think it is too much?

And the **Installparty**. Do we remember how many people where there last time?
so if we aim at 70 peeps in total for the main event then it will be maybe **50**?

**Comment by plexus** [comment]
@Realtin that sounds about right. Maybe aim for 55 or even 60 for the installfest. It's not a big deal if there's some food left over then, we just serve it the next day.

Coaches training I think 20 is definitely enough.

**Comment by vsmart** [comment]
We've decided to go with Suppencult again, cause they make delicious vegan soups! We've ordered two soups for each evening: 

```
17th  (Coaches Training)  -  Erdnusstopf + Karibischer Pfeffertopf (ohne Koriander) - 25 persons
25th  (Installfest) - Möhrensuppe + Linsensuppe - 55 persons
```

Both come with bread & baguette.
