### ISSUE TITLE
Cupcakes for Afternoon Tea

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#109]

**Comment by plexus** [comment]
Studio NAND has offered to sponsor ~250, and suggest they pay for this.

I quote:

> We do not have budgets for recurring support of more events, but we would be glad to support you with budget for coffee and cake (Small Supporter - 250€) for the end of Nov session. We can directly pay for the items, I think that's the best way. If it would be a donation, we have to jump through more hoops with regards to your organization.

Would that work?
