### ISSUE TITLE
Find space for Installfest on Friday night / plus requirements

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#11]

**Comment by martinklepsch** [comment]
So to write out the requirements for this:
- place for 40-50 people
- decent internet connection
- from 3pm to 8pm(**?**) on July 10th

Anything else?

**Comment by Malwine** [comment]
The idea was to do it close to our main venue.
I will ask if we get the Snuggery or the Dawanda cinema for this event.

Moreover we need:
- WIFI
- electricity plugs
  (both best provided by the venue)

**Comment by martinklepsch** [comment]
6Wunderkinder would also be interested in hosting it. They have a good network there according to @andreiursan

**Comment by thatbettina** [comment]
We will have the installfest at 6W.
