### ISSUE TITLE
Raffle Books

### ISSUE THREAD

**Issue by Realtin** [clojurebridge-berlin/organization#110]
- [x] Buy 3x Clojure for the Brave and True
- [x] Buy 3x Living Clojure
- [x] take them to Euroclojure 🚗 
- [x] get them signed! 💜

**Comment by lislis** [comment]
I'm gonna assign myself right away and order the books and 🚗 them to Bratislava

**Comment by lislis** [comment]
Hmm, looks like amazon can't deliver Living Clojure before November :/ Any other ideas where to order/ pick them up?

**Comment by lislis** [comment]
Never mind. Once I split up the order in 1 and 2 books it is deliverable until Saturday :shruggggg:

**Comment by vsmart** [comment]
@lislis  got the books signed by Caren 🎉 I think this can be closed.

**Comment by plexus** [comment]
Had a chat with Carin Meier, and she mentioned O'Reilly directly sponsored some books to other ClojureBridges and that they're usually quite good about that, so something to keep in mind.

**Comment by lislis** [comment]
She mentioned the same to me while signing. I can also ask Tobi from RUG::B how to go about that because he raffled some sponsored O'Reilly books some time last year
