### ISSUE TITLE
Add Site/Info about the Study Group

### ISSUE THREAD

**Issue by Realtin** [clojurebridge-berlin/organization#112]

**Comment by vsmart** [comment]
===> https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/28

**Comment by ioctaptceb** [comment]
if no one is taking over this, would it make sense for me to do it? is there any other information that is necessary? also is this a separate issue or the same as this one (as mentioned by franka) ? https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/28

**Comment by plexus** [comment]
@lithop that would be great! having anything up there to point people at would already be a big improvement. We can always improve it later.

Main points that should be on such a page (someone correct me if I'm wrong or misrepresenting things)
- meets three times per month on Wednesday, the fourth Wednesday everyone goes to the Clojure Meetup
- beginners are most welcome. If you've done the workshop you know more than enough (this seems to be a misconception and a reason why not many people find the way: they think you need to be somewhat "advanced")
- you can either work on your own stuff, or find people with shared interests to work on a project together over a longer time
- we do both artsy stuff and "practical" (i.e. webdev) stuff
- the evening starts with a vegan potluck, so feel free to bring and share some food
- there will be coaches to help you
- location can vary so best to get in touch
- main communication channel is slack, if you've done the workshop and want to join the group then you can get an invite
- there's a tumblr with some stuff the art group did. It's not very up to date but I would still link to it.

**Comment by vsmart** [comment]
@lithop sure, would be great! It's the same issue. We just try to keep orga stuff on this repo, but the actual change needs to be made in the website repo. 
@plexus that's a great list 👍 
one thing I would add to the potluck info is this: 
_Typical schedule:_
_7pm - 8pm: Vegan potluck & hanging out_
_8pm - 10pm(ish) Clojure Hacking_

**Comment by ioctaptceb** [comment]
I updated the other issue with the info here. I will try to start working on it this week

**Comment by vsmart** [comment]
Done: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/39
🎉 💯
