### ISSUE TITLE
Reachout [Event Pages/Blogs] 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#115]
A lot of feminist / queer / lefty blogs and pages have event calendars where you can submit entries. I think we can take advantage of this. Below: 
# Event Pages / Blogs
- [x] http://maedchenmannschaft.net/ - post(at)maedchenmannschaft.net [franka]
- [x] http://missy-magazine.de - redaktion at missy-mag.de [Lisa]
- [x] stressfaktor - http://stressfaktor.squat.net/terminator.php [franka]
- [x] http://www.l-mag.de/l-termine/termin-aufgeben.html [franka]

Please add more if you can think of them. And put your name down after you contacted one, for example:  
- [x] my-awesome-blog [Franka] 

Thanks! ❤️

**Comment by lislis** [comment]
I have a contact at Missy. Let me know if you want me to contact them

**Comment by vsmart** [comment]
@lislis that would be super :). [Here](https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Reachout-Mail-reflect-info) is a template that may be helpful.

**Comment by lithop** [comment]
https://www.facebook.com/workinprocessmag/ has posted as well

**Comment by ioctaptceb** [comment]
https://www.facebook.com/workinprocessmag/?fref=ts 
work in progress has posted something, I can also talk to them about doing an interview with one of the coaches, might be a nice way of getting more people from a different background

**Comment by vsmart** [comment]
Closing this as registrations are closed, with 110 signups 🎉
