### ISSUE TITLE
T-Shirts

### ISSUE THREAD

**Issue by codebeige** [clojurebridge-berlin/organization#117]
We want to give t-shirts to the attendees. We need a design, a sponsor and have to place an order.

The design will have no dates or sponsors on it, so we can reuse t-shirts that are not given away during the upcoming workshop. But still we need to figure out, how to deal with the size distribution.

**Comment by lislis** [comment]
Will there be only one cut or two cuts?
Do we know if the tshirt sizes of the fabric are reasonable? (S is really S and not XS and so on).

**Comment by codebeige** [comment]
@plexus might have already found a sponsor for the T-Shirts (and possibly also the orga-hoodies). 🎉 

There is a premise with the payment, though. Once I have checked the payment procedure with [cotton.de], we can select the actual model. (See also #96 for a discussion about possible brands.)

**Comment by codebeige** [comment]
Front:
![t-shirt front](https://cloud.githubusercontent.com/assets/91858/19386570/3abca150-9215-11e6-9a29-87701f4172cb.png)

Back:
![t-shirt back](https://cloud.githubusercontent.com/assets/91858/19386571/3ce10a34-9215-11e6-852d-00e44f495997.png)

**Comment by codebeige** [comment]
![161014 t-shirt](https://cloud.githubusercontent.com/assets/91858/19387184/d82eab56-9218-11e6-83f3-c82ea5497ef2.png)

**Comment by socksy** [comment]
At the risk of bikeshedding, I'd prefer to have the logo on the t-shirt to the side, like the old t-shirts — this makes it much more likely that I'll wear the t-shirt in day to day life as it's not so in your face.

**Comment by ioctaptceb** [comment]
I quite like the design of the back of the old t-shirt -- this config style look was really nice. Is there a way to echo this again?

**Comment by plexus** [comment]
Seems at the core meeting most people really like where this is going. The same point raised about the hoodies applies though, for women it would be preferable to have a smaller logo up on the side.

**Comment by plexus** [comment]
Maybe with namespaced keywords, to move with the times ;)

**Comment by codebeige** [comment]
I have no strong opinion on the placement of the logo in the front. So let's go with the classic and well-tried small version at the upper left. After some more contemplation I am no longer happy with the lettering on the back. I would probably give the Clojure data approach another try. Although there is maybe not enough general information to be used here.

**Comment by codebeige** [comment]
How do you like this?

![161019 t-shirt back_config](https://cloud.githubusercontent.com/assets/91858/19535187/fd145114-9646-11e6-8bad-efc39bfd6f85.png)

**Comment by Malwine** [comment]
@codebeige last year Arne shared this article: http://geekfeminism.wikia.com/wiki/T-shirts
A good read to understand T-Shirt Design for Women.

**Comment by codebeige** [comment]
![161019 t-shirt placement_position](https://cloud.githubusercontent.com/assets/91858/19535752/4fc9c2e8-9649-11e6-9f6f-a0b2fc66f9b3.png)

**Comment by codebeige** [comment]
We can order these two cuts with color "Vintage Navy Blue":

http://www.cotton.de/hersteller/earthpositive/ep31-mens-vintage-shirt/
http://www.cotton.de/hersteller/earthpositive/ep32-womens-vintage-shirt/

<del>I still have no idea how to best estimate/decide on sizes and amounts to order. Any ideas? Can we maybe interpolate the numbers from the last workshop(s)? </del>

**Comment by codebeige** [comment]
I will wait for the registrations to be complete before continuing with the order.

**Comment by plexus** [comment]
@codebeige how long does Cotton.de need to do the t-shirts? Can you already get a quote from them? I need to know if it's the right kind of amount that I can link them directly with a sponsor.

**Comment by vsmart** [comment]
@codebeige I think waiting till registration is closed will be too late, no? We have 55  tshirt sizes now from attendees, plus a few from coaches, already. That should give you a good sample.

**Comment by codebeige** [comment]
The cotton.de website states that they deliver within 7 to 14 days, sometimes even faster. So we should be save ordering at beginning of next week.

**Comment by codebeige** [comment]
Final design:

![161106position](https://cloud.githubusercontent.com/assets/91858/20040776/b397afe8-a45d-11e6-86dc-92eb3397e83a.png)

![161106front](https://cloud.githubusercontent.com/assets/91858/20040777/b6f35782-a45d-11e6-8021-f1ac51228748.png)

![161106back](https://cloud.githubusercontent.com/assets/91858/20040778/b9abfff6-a45d-11e6-8f29-7b5eca583d85.png)

Color: HKS 91 K with white grounding print.

**Comment by codebeige** [comment]
This is the quote from [cotton.de](http://cotton.de) that I received today:
[34413_ag.pdf](https://github.com/clojurebridge-berlin/organization/files/575862/34413_ag.pdf)

**Comment by codebeige** [comment]
At the orga meeting today we decided to not order t-shirts this time as we do not have the budget for it.
