### ISSUE TITLE
Curriculum/Timeline for Learners Group 📚🎓

### ISSUE THREAD

**Issue by Realtin** [clojurebridge-berlin/organization#118]

**Comment by Realtin** [comment]
**First Week after Workshop**: _getting to know everyone / revisiting the Workshop Project_
**after that**: going through [Clojure for the Brave and True](http://www.braveclojure.com/)

**Comment by vsmart** [comment]
- [Week 0] Intro: Get up and running with Nightcode/Clojure) 
- [Week 1] Basic animation: (e.g. a ball moving, heart beating sketch from quil.info) based on frame count
- [Week 2] User interaction (using mouse-x, mouse-y, mouse-click, draw, bonus: erase) 
- [Weeks 3] State with fun-mode (a counter increment) 
- [Week 4-5] Using user interaction + state together (e.g. simple snake) 
- [Week 6-?] Adding enemies (more complex state)

**Comment by ellenkoenig** [comment]
I like the proposed curriculum from @vsmart . I would just suggest to make it clear that the curriculum is optional, so if someone has a specific thing in mind  they want to do, they can do that instead.

I would not recommend starting with "Brave and True" in the second week already, from my experience, it is pretty dry and not very motivating.

**Comment by lislis** [comment]
I would insert an extra week before [1] as I find that getting the computational aspects of animation are quite difficult to understand without prior programming experience (based on my teaching experience, so maybe others' is different?)
I liked the Rustbridge tutorial of 'just' randomly colored squares 
![image from rustbridge](https://raw.githubusercontent.com/rust-community/rustbridge/master/workshops/beginners/03_random_image/image.png) 
which would introduce some quil commands and then we can animate stuff that we drew.

**Comment by jellea** [comment]
@lislis the idea was to dodge collections at first and go for some simple drawings and make things move as soon as possible. I think the problem with animation is that it can get mathematical too quick, so we'll have to make an exercise which avoid this.

Here's some great inspiration/ideas
http://worrydream.com/#!/LearnableProgramming

**Comment by vsmart** [comment]
I used the input from this issue to make the following repo: https://github.com/clojurebridge-berlin/study-group-curriculum

In that repo, there is an open issue for each week of curriculum that needs help. Please head over there, check it out and maybe make a quil sketch to help out 💪 ✨ Thank you! ❤️

**Comment by vsmart** [comment]
study group curriculum lives here: https://github.com/clojurebridge-berlin/study-group-curriculum
