### ISSUE TITLE
Expenses

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#119]
Please comment here if you spend any money for ClojureBridge, just a short date/amount/description summary is fine. Keep the receipts!

| 2016-10-17 | 46.02 | flag/banner for EuroClojure |
|--|--|--|
| 2016-10-08 | 92.58 | Books |
| 2016-10-08 | 71.85 | Books |
| 2016-10-15 | 130.85 | Flyers |
|  | 341.30 | |

**Comment by plexus** [comment]
- 2016-10-17
- 46,02 €
- flag/banner from Flyeralarm

**Comment by plexus** [comment]
@codebeige @lislis could you please already post what you spent on the flyers and books? Ta!

**Comment by lislis** [comment]
- 3x Living Clojure 92,58 € (2016-10-08)
- 3x Clojure for the Brave and True 71,85 € (2016-10-08)

**Comment by codebeige** [comment]
- 2016-10-15
- € 130,85
- Posters and flyers from Pinguindruck

**Comment by socksy** [comment]
- 2016-11-18
- 6,40€
- [Orange stickers](https://www.amazon.de/gp/product/B007G79SDU/ref=od_aui_detailpages00?ie=UTF8&psc=1) for name badges

**Comment by vsmart** [comment]
* 145.35 EUR for breakfast

**Comment by vsmart** [comment]
58.64 for more breakfast (bananas, apples, spreads)

**Comment by codebeige** [comment]
* 80,– € for vegan Donuts from Brammibal's. (Managed to get a receipt in hindsight.)

**Comment by plexus** [comment]
Sent to Travis for refunds:

| Item | Price |
|---|---|
| Books: Clojure for the Brave and True | -€71.85  |
| Books: Living Clojure                 | -€61.72  |
| Books: Living Clojure                 | -€30.86  |
| Breakfast: Donuts                     | -€80.00  |
| Breakfast: Muffins/Brezel/Brötchen    | -€145.35 |
| Breakfast: spreads                    | -€58.64  |
| Flyers                                | -€130.85 |
| USB sticks                            | -€25.96  |
| **Total** | -605.23 |

Knofi was paid by Travis directly. The soup was paid by InnoQ.
