### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#12]
I like chat and think it would be nice to have some chat room for organisers.
My friends and I mostly use [Telegram](http://telegram.org) these days, which has excellent clients for most devices/operating systems. 

If you already have Telegram you can add me via my username `martinklepsch`.
I'll create a group if a few people add me.

**Comment by thatbettina** [comment]
@martinklepsch - I downloaded Telegram but couldn't find you there. Seems like I can only add contacts, and I don't have your phone number.

**Comment by thatbettina** [comment]
Since we decided to go with Telegram, I am closing this issue--new organizers, please join our Telegram group.

**Comment by martinklepsch** [comment]
@plexus & @Malwine are still missing from the group :cry:

**Comment by Malwine** [comment]
:rage: ok ok :laughing: will join
