### ISSUE TITLE
7.11.2016 Core Team Meeting III Agenda [November 2016] 

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#120]
- Status update
- finance overview
- close the attendee form (if not closed already), merge PR to website removing link -> https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/35
- attendee care: who is doing it? (& when) 
- speakers -> https://github.com/clojurebridge-berlin/organization/issues/95
  - can we afford the invite https://twitter.com/jjordan_dev ?
- guest policy -> https://github.com/clojurebridge-berlin/organization/issues/123
- child care -> https://github.com/clojurebridge-berlin/organization/issues/122
- prep coaches training -> https://github.com/clojurebridge-berlin/organization/issues/121
- tshirts / orga-hoodies? -> https://github.com/clojurebridge-berlin/organization/issues/117
- dicuss roles during the workshop (who will coach, will help out)
- send coaches invite email (if not already covered by 'prep coaches training')
- video call in to the London Clojure Bridge during/after Lunch?

**Comment by lislis** [comment]
added 2

**Comment by socksy** [comment]
Are we paying for the main workshop catering from Travis? If so, what's the billing address?

**Comment by plexus** [comment]
Present: Franziska, Lisa, Saskia, Julia, Yulia, Ben, Kate, Nicola, Arne, Tibor

### Status update
1.  Signup
   -   105 people signed up so far
   -   19 coaches
2.  Catering
   -   Soup for Coaches training + installfest (two types of soup each + bread and stuff)
     => 7 EUR/person = 177 CT + 333 Lunch = 510
   -   Main workshop: Knofi (mediterannean good stuff)
     => 12 EUR/person = 970 EUR total
     -   salad
     -   3 main dishes

### Finance overview
-   [Issue: Sponsors](https://github.com/clojurebridge-berlin/organization/issues/98)
-   [Issue: Expenses](https://github.com/clojurebridge-berlin/organization/issues/119)

Travis: 1402,84€

Sponsors

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<colgroup>
<col  class="org-left" />
<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">sponsor</th>
<th scope="col" class="org-right">amount</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">Doctronic</td>
<td class="org-right">600</td>
</tr>
<tr>
<td class="org-left">Soundcloud</td>
<td class="org-right">500</td>
</tr>
<tr>
<td class="org-left">InnoQ</td>
<td class="org-right">500</td>
</tr>
<tr>
<td class="org-left">Bitcrowd</td>
<td class="org-right">250</td>
</tr>
<tr>
<td class="org-left">Babbel</td>
<td class="org-right">250</td>
</tr>
<tr>
<td class="org-left">Studio NAND</td>
<td class="org-right">**cupcakes**</td>
</tr>
<tr>
<td class="org-left">PragProg</td>
<td class="org-right">5 e-books</td>
</tr>
<tr>
<td class="org-left">Microsoft</td>
<td class="org-right">venue + drinks</td>
</tr>
<tr>
<td class="org-left">Lambda Island</td>
<td class="org-right">1 year membership</td>
</tr>
<tr>
<td class="org-left">Purefunctional.tv</td>
<td class="org-right">1 year membership</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">Total</td>
<td class="org-right">2100</td>
</tr>
</tbody>
</table>

Expenses

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<colgroup>
<col  class="org-right" />
<col  class="org-right" />
<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">2016-10-17</th>
<th scope="col" class="org-right">46.02</th>
<th scope="col" class="org-left">flag/banner for EuroClojure</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-right">2016-10-08</td>
<td class="org-right">92.58</td>
<td class="org-left">Books</td>
</tr>
<tr>
<td class="org-right">2016-10-08</td>
<td class="org-right">71.85</td>
<td class="org-left">Books</td>
</tr>
<tr>
<td class="org-right">2016-10-15</td>
<td class="org-right">130.85</td>
<td class="org-left">Flyers</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">970</td>
<td class="org-left">Workshop food</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">510</td>
<td class="org-left">Suppenkult</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">~150</td>
<td class="org-left">cupcakes</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">~150</td>
<td class="org-left">breakfast</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">100~200</td>
<td class="org-left">childcare</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-left">t-shirt</td>
</tr>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">2075.30</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

We'll try to link Suppenkult with InnoQ, and studio NAND with Cupcakeberlin.

### close the attendee form (if not closed already), merge PR to website removing link -> https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/35
-   Will be closed on Wednesday
-   First look who was rejected last time, invite those first => data is in the "to be deleted" sheet
-   pre-invite speakers
-   Check for potential coaches

### attendee care: who is doing it? (& when)
-   Arne will make the initial selection
-   Lisa and Yulia can help with managing it afterwards
-   There's a private chat channel to discuss this
-   We'll pick a time the weak before to make the groups

### guest policy -> https://github.com/clojurebridge-berlin/organization/issues/123
-   Franka's suggestion looks good
-   Would be good to add why we have it ("provide a safe, distraction-free environment. + for safety reasons e.g. fire we should know who's there)
-   distinguish coaches / orga / coaches by lanyard/nametag style
-   make sure we print it (been added to the checklist)

### child care -> https://github.com/clojurebridge-berlin/organization/issues/122
-   one person said they would definitely use child care
-   one person said they could use it if possible
-   mention it in the invite email
-   also make it available for coaches

Goodhands is a "marketplace for babysitters", so we would have to provide a space.

It costs 12€/h for one kid or if we have all the kids at one space then it becomes less (2 kids = 7€/h each) and so on.

9:00 - 18:00 = 10.5 hours

```
(* 9 12)    ;;=> 108
(* 9 7 2)   ;;=> 126
(* 9 5.5 3) ;;=> 148.5
(* 9 4.5 4) ;;=> 162.0
```

There are still a lot of questions/concerns about how to best arrange this.
We'll start by offering again and see what happens.

### prep coaches training -> https://github.com/clojurebridge-berlin/organization/issues/121

Most stuff is explained in the issue. Franka will take care of it with Ben
and Lisa. Venue and food are confirmed.

The slide deck should be updated.

Let's send the reminder email before the weekend.

### tshirts / orga-hoodies? -> https://github.com/clojurebridge-berlin/organization/issues/117

The proposal was to get about 120 t-shirts so we have enough spares in each
size. This would cost about 1400 EUR, which per t-shirt comes to about the
same price that we had the first workshop, 11+ EUR per t-shirt.

Looking at the current budget that seems optimistic, we decided to wait
another workshop and in the meanwhile try to increase our savings.

We will still get hoodies for the orga people. Tibor needs to know who wants
to order one soon. Orga people pay for them themselves.

### dicuss roles during the workshop (who will coach, will help out)
-   Lisa can do whatever, mc, catering, be there for questions, etc
-   Franka: mc, catering, venue, general
-   Tibor: can coach again, is also fine to do something else
-   Nicola: float coach or doorkeeper
-   Ben: not full on coaching but can help, happy to do catering, door. Ben will not MC in German.
-   Yulia: would be happy to be a coach or whatever is necessary
-   Julia: would like to be a coach

### send coaches invite email (if not already covered by 'prep coaches training')
-   email needs some updating, we'll try to simplify the RSVP'ing
-   Ben will update the email, Arne will get one

### video call in to the London Clojure Bridge during/after Lunch?
-   seems like a good idea

### Learners group curriculum
-   some initial work was done, since then it's stalled a bit. If anyone feels
  like it they should run with it.

It's a Quil themed 5-week curriculum.

### speakers -> https://github.com/clojurebridge-berlin/organization/issues/95
-   can we afford the invite https://twitter.com/jjordan_dev ?

We agreed to a 300 EUR budget.
