### ISSUE TITLE
Coaches Care & Coaches Training

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#121]
~@lithop~ @lislis and @socksy and @vsmart will take this 

Confirmed venue, Wunderlist will host us on 17 Nov.

**Comment by Realtin** [comment]
Food: https://github.com/clojurebridge-berlin/organization/issues/107

**Comment by vsmart** [comment]
Quick update: we have 18 coaches signed up so far. 🎉 
(But only 5 or 6 non-men, so could try for some more there!)

**Comment by vsmart** [comment]
## Schedule
- 6:30 Food arrives
- 7:00 Food is served, people arrive
- 7:30 We start talking 
  (short break at some point) 

@lislis & @vsmart will run the coaches training 
we need 2 more people to help with doors, volunteers welcome 💌

**Comment by lislis** [comment]
We trained! Any feedback can go in the retro ticket https://github.com/clojurebridge-berlin/organization/issues/132
