### ISSUE TITLE
Child Care 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#122]
We want to offer support with child care this workshop.
Either financial support or child care at the event.

**Comment by vsmart** [comment]
```
Do you need support with child care during the event? (financial or at-the-event care)
Brauchst du Hilfe mit Kinderbetreuung? (entw. finanzielle Unterstuetzung oder Betreuung beim Event) 
```

--- I added this question to the signup form

**Comment by vsmart** [comment]
@Realtin Did you hear back from the child care orga?

**Comment by Realtin** [comment]
I did reach out to my contact but I didn't really know what to say since we don't really know anything for sure yet. (if we will have people needing it at all or how many)

He (Sven) gave me his email address and we can just write emails when we know more. 
this is his company: https://goodhands.eu/client/home

**Comment by vsmart** [comment]
I saw we have two people who would use child care already. Can you send them an email for an offer of what it would cost to watch 2-3 kids for the whole day? (9-1pm, 2pm - 6pm). Perhaps asking if they have a space or if they offer on-site care.

**Comment by Realtin** [comment]
goodhands just is a marketplace for babysitters ... so you need your own place. 
it costs 12€/h for one kid  or if we have all the kids at one space then it becomes less (2 kids = 7€/h each)  and so on.

**Comment by vsmart** [comment]
Just talked with Bastian from goodhands.eu 

We talked through our setup, the office building, the environment etc. He said it all sounds good and they have done similar events before 👍 

It's 18 EUR per hour; so 9 \* 18 = 162. (As long as it's under 5 kids total) 

yay! 🎉

**Comment by vsmart** [comment]
Goodhands was great, even though we didn't end up needing child care in the end. Good contact for next time 📝
