### ISSUE TITLE
Guest Policy

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#123]
Writing up a guest policy is something we put as a to-do from the last retro. 
We should write this up - ideally before the coaches training so we can share it with the coaches too.

**Comment by vsmart** [comment]
I've written up a draft guest policy. Please leave comments! 👀 

---

### Guest Policy
1. The venue is open for attendees, coaches, speakers, orga team and volunteers. These are registered in respective registration documents before workshop day.
2. Guests should be registered on the "guest signup sheet" before the day. Un-announced guest will be turned away at the door. If an un-registered guest _must_ be addmitted, this decision will be made be by at least 2 people of the orga team. These unregistered guests must sign the guest signup sheet. 
3. Everyone in the venue must agree to the Code of Conduct. For unregistered guests, this should be a part of the guest signup sheet. 

---

**Comment by Malwine** [comment]
Would be cool if we could report this back to the clojurebridge/organize repo as a suggestion. After our workshop :)

**Comment by plexus** [comment]
One thing I would suggest to add: everyone gets a name tag or lanyard with their name and role.

**Comment by vsmart** [comment]
Added to  [here](/documents/guest_policy.md).
