### ISSUE TITLE
MC Stuff 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#124]
* Who is mc-ing? 
  (possibly Franka, who else?) 

* MC Notes: 

- remind people to be respectful of other's pronouns, there are nonbinary people too, don't assume someone's gender/pronouns 

- during coaching time, go around & encourage people to take breaks & snacks

**Comment by lislis** [comment]
![I volunteer](http://i.giphy.com/OBvq3e6ZaFbHO.gif)
as MC

**Comment by lislis** [comment]
And so we did 💃 Closing
