### ISSUE TITLE
Mailing list for project group

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#125]
.... needs to be set up. 
not google groups preferably

**Comment by Realtin** [comment]
I don't know anything about mailing lists but I stumbled upon: https://riseup.net/de/lists

**Comment by vsmart** [comment]
@Realtin sounds good 
also on clojureverse.org one can use a private forum like a mailing list, that could work too

**Comment by Realtin** [comment]
clojureverse sounds more appropriate and I love that it is a forum/mailing list hybrid .. so people who are uncomfortable with mailing lists (like me!) can just post go and post forum-style! 💟

**Comment by vsmart** [comment]
I chatted with @plexus for a bit. He will set up a private sub-forum of clojureverse which doubles as a mailing list. ✅ 

We still need a good name. @plexus pointed out that having names like RubyCorns & RubyMonstas really helped forming a group identity which helps people attend regulary. It'd be great if we could have a good name too. Maybe something to brainstorm about on the group on Wednesday? 
(or comment here with suggestions!)

**Comment by vsmart** [comment]
We've been using a manual email system for a while and it's ok for now. Closing this.
