### ISSUE TITLE
Afterparty

### ISSUE THREAD

**Issue by lislis** [clojurebridge-berlin/organization#126]
I'm trying to get in contact with [Volksbar](https://www.yelp.com/biz/volksbar-berlin?adjust_creative=dWJMtmYxpd5N5yoyzSuhtA&utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=dWJMtmYxpd5N5yoyzSuhtA) to see if we can have thait upstairs space to ourselves.

**Comment by vsmart** [comment]
https://github.com/clojurebridge-berlin/organization/issues/101

**Comment by vsmart** [comment]
closing this, duplicate, talking in #101
