### ISSUE TITLE
21.11.2016 Core Team Meeting IV Agenda [November 2016] 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#127]
* Status Update: 
  - on attendee care
  - on coaches care
  - on speaker care
  - on child care
  - any other updates?
* discuss orga communication: e.g. slack with push notifications? Will we have the orga room? 
* does everyone know the process in case of CoC violation?
* Fill out volunteer jobs list 
* go over on-the-day checklist
* decide where to place quiet room, child care room, orga room, groups
* how do we follow up for the project groups? Printed out forms?
* schedule retro + orga celebration dinner
* orga photo

**Comment by plexus** [comment]
# Core Meeting IV<a id="orgheadline32"></a>

Present: Ben, Jelle, Nicola, Franks, Lisa, Julia, Tibor, Arne

## Status Update<a id="orgheadline23"></a>

### on attendee care<a id="orgheadline1"></a>

Currently 37 confirmed, 3 waiting for reply. We'll invite at least one or two more.

We've sent the attendee information to 37.

### on coaches care<a id="orgheadline2"></a>

24 confirmed coaches, one person waiting to hear brack from.

One person didn't come to the coaches training and didn't do ClojureBridge
before, but she does have other relevant experience, and Ben knows her.
We've sent her the info from the coaches training.

Coaches training went well. Franks and Lisa aced the MC'ing. We have a
bunch of new faces, including several new arrivals in Berlin.

The info is in the "working copy" spreadsheet.

### on speaker care<a id="orgheadline3"></a>

We have a really cool speaker lineup of seven people doing six talks. Two
of them are also coaches, we have an all-woman lineup.

Franks made a speaker form to have the speakers confirm the CoC, get their
food prefs, etc.

-   Jenny
-   Malwine
-   Ellen, Ariane
-   Laura
-   Jessica

We got a bit more organized and professional around organizing speakers.
They got an email with all the details, etc.

Two english talks, two german talks, two EN/DE mixed.

NEXTWORKSHOP We have a field on the coaches form for potential lightning
talk topics. We never followed up on that, which is a bit of a shame. Might
be better to take it off.

### on child care<a id="orgheadline4"></a>

Didn't seem necessary in the end. Of all the signups one person said "yes,
I'd like childcare", and one said, "not in principle but I might use it".
The "yes" person did get picked but ended up already having different
plans.

We'll wait another day and then cancel the childcare. Still good we went
through the exercise of figuring all of that out.

### Catering update<a id="orgheadline9"></a>

1.  Suppen-cult did coaches training and will do installfest

    made an invoice directly to InnoQ for 510 EUR

2.  Knofi

    ~970 EUR that we'll get Travis Foundation to pay directly, haven't
    received an invoice, might come after the workshop

    ACTIONABLE Email them with the allergy list

3.  Cupcake Berlin

    Have been ordered 250 EUR. Invoice made out directly to Start Coding e.V.
    (Studio NAND). We've forwarded the invoice, hopefully that's all fine.

4.  Breakfast

    Franks and Lisa went to the bakery and ordered breakfast for 145.35 EUR

    -   35 chocolate muffins
    -   35 carrot cake muffins
    -   15 brezels
    -   15 white rolls
    -   15 whole wheat rolls.

    We'll also get some spreads and fruits.

### Sponsoring update<a id="orgheadline21"></a>

ACTIONABLE add the remaining logos to ClojureBridge.org

-   purefunctional.tv
-   babbel
-   microsoft
-   blacklane
-   thoughtworks

1.  InnoQ [OK]

    Hooked them up with Cupcake Berlin

2.  Doctronic [NEEDS RECEIPT]

3.  Bitcrowd [NEEDS RECEIPT]

4.  PragProg [IN KIND]

    We'll offer two titles

    -   Programming Clojure (for beginners)
    -   Clojure Applied (for more advanced learners)

5.  Soundcloud [?]

6.  Lambda Island [IN KIND]

7.  Purefunctional.tv [IN KIND]

8.  Babbel [NEEDS RECEIPT]

9.  Microsoft [IN KIND]

10. Blacklane [WAITING FOR PAYMENT]

    They want a paper receipt, we asked Travis Foundation, they said they can do that, so now we're waiting for payment.

11. ThoughtWorks [NEEDS ADDRESS]

    Should be paid

### Afterparty<a id="orgheadline22"></a>

Downstairs at Volksbar, 19:00, reserved in Lisa's name. Non-smoking, yay!

## discuss orga communication: e.g. slack with push notifications? Will we have the orga room?<a id="orgheadline24"></a>

We'll do slack + have a dedicated door phone.

We'll make a separate private channel for the day. Make sure everyone has
push notifications on.

The old quiet room can be the orga room, we'll make a separate quiet room.

## does everyone know the process in case of CoC violation?<a id="orgheadline25"></a>

This is the anti-harassment policy, it's been added to the wiki

<http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports>

Policy on the door: main rule is to send uninvited guests away. If we do
decide to let someone in, they should sign in and agree to the CoC.

## Fill out volunteer jobs list<a id="orgheadline26"></a>

ACTIONITEM poke some more potential volunteers (if necessary)

## go over on-the-day checklist<a id="orgheadline27"></a>

ACTIONITEM if you can bring a power cord or two, label it with your name!

## decide where to place quiet room, child care room, orga room, groups<a id="orgheadline28"></a>

## How to follow up for the project groups? Printed out forms?<a id="orgheadline29"></a>

Franks and Arne set up a private mailing list on Clojureverse. We'll get a
paper sign up form (just name+email).

Franks has also been working on a curriculum for the first weeks. Example
quill sketches for each chapter would be very welcome.

Check it out! <https://github.com/clojurebridge-berlin/study-group-curriculum>

Until the end of the year it'll be at Soundcloud.

## schedule retro + orga celebration dinner<a id="orgheadline30"></a>

18 December retro (brunch @ Arne)
7 January celebration! (Da Jia Le?)

## orga photo<a id="orgheadline31"></a>

at the retro?

**Comment by vsmart** [comment]
🎉
