### ISSUE TITLE
update website with sponsor logos for next workshop

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#128]
Change needs to be made here: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/blob/master/index.html#L320-L323

**Comment by plexus** [comment]
![logo-clojurebridge](https://cloud.githubusercontent.com/assets/32212/20244976/7d1864fc-a995-11e6-9f9f-06cb682aceac.png)

**Comment by plexus** [comment]
there you go @vsmart
