### ISSUE TITLE
Who wants to be the "face" of ClojureBridge Berlin?

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#13]
Each workshop group has provided ClojureBridge with the Github username of the person who acts as the "face" of the event. 

Preferably whoever is tweeting out the stuff for us and acts as the "Communicator" for us as documented here: https://github.com/ClojureBridge/organizing/blob/master/Three-Main-Roles.md

**Comment by plexus** [comment]
It would be great if we could have a woman as "face" of the event. I wouldn't mind taking up the role of "stage director"/logistics.

**Comment by martinklepsch** [comment]
> It would be great if we could have a woman as "face" of the event. 

:+1: 

PS: I can do whatever is needed. :smile:

**Comment by thatbettina** [comment]
@Malwine and @nicsnet -- are you interested in being the face of ClojureBridge or the emcee / circus ringmistress role as described here: https://github.com/ClojureBridge/organizing/blob/master/Three-Main-Roles.md ? 

I usually take on the job no one else wants to do.

**Comment by martinklepsch** [comment]
If someone steps up until Wednesday I think it'd be super cool if that person could give a quick shoutout at the Clojure Meetup. :smiley:

**Comment by thatbettina** [comment]
@martinklepsch - If you're at the meetup, you can give a quick shoutout :dancer: 

Otherwise, I think @Malwine wants to tweet out and communicate for us...once she confirms that, I can let ClojureBridge know to link to us under her Github account.

**Comment by Malwine** [comment]
Well I can do it. But I like your picture more @thatbettina :blush:

**Comment by thatbettina** [comment]
So @Malwine is going to be our "face" / communicator--hooray!
