### ISSUE TITLE
demo time!

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#130]
Last time we had the issue that many demos did not work on the projector. 

Any suggestions for improving this? How can we make the demo time smooth and encouraging?

**Comment by socksy** [comment]
Last time, to get around it, we passed around a USB stick and Arne presented them. Perhaps we can still do the USB stick, but get the person who did it to present them? + some anonymous.

**Comment by lislis** [comment]
-> part of the retro https://github.com/clojurebridge-berlin/organization/issues/132#issuecomment-263287559
