### ISSUE TITLE
Collection of stuff for retro

### ISSUE THREAD

**Issue by lislis** [clojurebridge-berlin/organization#132]
- check swag for CoC violations
- check Nightcode version properly
- guidelines for guests at afterparty/ timeframe for afterparty (reg. CoC coverage)

**Comment by Malwine** [comment]
taking pictures is hard without disturbing attendees, Ariane had a good idea, will specify later

**Comment by Malwine** [comment]
some thought for discussion: maybe we should ask roughly in the signup if people are from berlin or from very far away so we can find a way people from far away (e.g. other countries or cities in germany) can plan their trip

**Comment by jellea** [comment]
Reconsider the choice for Nightcode. (Lack of zoom, crashing of nightcode, graphics project scaffolding)
Less floating coaches?
Slim down curriculum to move on to Quil earlier?

**Comment by jellea** [comment]
Oh and more non-sugary food/drinks options. :)

**Comment by vsmart** [comment]
child care: really good impression of goodhands ++++ should keep them in mind next time. but: we should ask attendees to confirm  their use of it maybe a week or 5 days in advance. 

demos: worked really well from lisa's computer. much better & smoother this way.

**Comment by lislis** [comment]
- mention available floating coaches earlier and more often

**Comment by vsmart** [comment]
* dont leave people standing outside in the cold
==> maybe we need a second channel for when the phone fails, e.g. twitter with pn or a second phone number

**Comment by vsmart** [comment]
agenda from retro here: https://github.com/clojurebridge-berlin/organization/issues/137
