### ISSUE TITLE
Wrap Up Mail (link collection)

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#133]
- Feedback Link https://aka.ms/clojurebridge-feedback
- Learners group http://clojurebridge-berlin.org/learners-group/
- Links to slides:
  - Jessica: https://jessica-jordan.github.io/things-i-love-about-my-detour-into-coding/#/
  - Laura: https://speakerdeck.com/lauralindal/empowerment-short-version-2016
  - Malwine: http://malweene.com/talks/finding-the-key.pdf
  - Ellen/Ariane: http://slides.com/anderspree/deck#/

**Comment by Malwine** [comment]
Add Bettina slides as well

**Comment by vsmart** [comment]
@ariaru or @ellenkoenig or @Realtin do you have a link to the learning group slides we can use in the round up email? Thanks!

**Comment by ellenkoenig** [comment]
@vsmart Sure: http://slides.com/anderspree/deck#/13

**Comment by ellenkoenig** [comment]
@vsmart Sure: http://slides.com/anderspree/deck#/

**Comment by vsmart** [comment]
Thanks @Malwine . I made this gist that I will include in the email. its too much info to put all inline :) https://gist.github.com/vsmart/0bc1cad6978537a5a408b1f1c21e0cb8

**Comment by lislis** [comment]
I believe the email was sent? 
Thank you all 🎉 
Closing
