### ISSUE TITLE
Send book vouchers to attendees

### ISSUE THREAD

**Issue by lislis** [clojurebridge-berlin/organization#134]
@plexus do you have the codes?
@vsmart do you have the attendee names?

**Comment by vsmart** [comment]
i have the names. will put them somewhere tomorrow. thanks for the reminder :)

**Comment by plexus** [comment]
I need the name + email + the book they want to send to pragprog. 

I can send Stefan's book if I know where to send it to.

**Comment by lislis** [comment]
I think the attendee who won Stefan's book will be at the study group on Wednesday.

**Comment by plexus** [comment]
I won't be there though.

**Comment by lislis** [comment]
@plexus do you think you can send the emails with the codes though? I guess @vsmart can send you the email addresses non-publicly?

**Comment by plexus** [comment]
There are no codes, we need to send PragProg their name+email+the book they want. Then they will get an email that looks like this.
![2016-11-29-131901_1359x486_scrot](https://cloud.githubusercontent.com/assets/32212/20709583/9165c73a-b636-11e6-8ece-ba31f2e51a23.png)

**Comment by vsmart** [comment]
we didn't ask them about the book they want. I think we should just pick one for them.

**Comment by plexus** [comment]
yeah that's cool, I  can look at the list what their experience level is, I just need to know who they are.

**Comment by lislis** [comment]
This has been taken care of! Thank you both!
