### ISSUE TITLE
emails still to be sent

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#136]
* [x] thank you email to sponsors 
* [ ] thank you email to speakers 
* [ ] email with freebies to attendess
* [ ] (maybe?) thank you to coaches
* [ ] (maybe?) a list of resources to those who didn't get in, with links to railsgirls etc

**Comment by plexus** [comment]
Did we already send an emails with the freebies?

**Comment by vsmart** [comment]
i guess not. we should add it to the list.

**Comment by vsmart** [comment]
I'm closing this - should plan out post-workshop-emails better next time :S.
