### ISSUE TITLE
2016 III - Retrospective minutes

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#137]
# Agenda

-   first time organizer perspective
-   coaches
    -   floating
    -   better training?
-   Nightcode
-   guest policy: guidelines for guests at after party/employees of host company
-   photo
-   food/drink
-   childcare
-   door phone
-   curriculum

# Positives

-   demos worked well from Lisa's computer

# Action items

-   review accounts, cycle passwords
-   ask in sign-up form where people are from to see if we can help
-   coaches training email: make it more clear that it's not Unter den Linden
-   have a way for coaches document install problems
-   pick a date for the first sustainability working group meeting
-   pick a date for the first curriculum working group meeting
-   add childcare to coaches & speaker sign-up forms
-   remove lightning talk field from coaches form
-   ask on the coaches sign-up form if they're ok with being floating coach
-   for sign-up form language, split it into: "German", "English", "Either but German preferred", "Either but English preferred"
-   send receipts to Arne
-   wrap up finances (Arne)

# Before event checklist stuff

-   test door phone, make sure it has a good ringtone
-   check swag for CoC violations
-   get people to confirm childcare a week in advance

# Notes

## first time organizer perspective

Concrete list of tasks would have been good. There are tasks on Github, but
it's not clear which things a person can pick up.

Main pain points seem to be time/task management

-   how much time should I set aside?
-   what should be done when?

How can we better set expectations?

How can we better get new organizers to feel part of the group?

## orga process

Franks felt quite overwhelmed this time, too many things she did because
otherwise maybe it wouldn't get done. Arne felt the same way the last few
workshops.

How can we prevent this happening? How can we actively make sure people are
happy and don't get burned out?

One thing is distinguishing between core (minimal viable workshop) stuff
and "fringe" stuff. Have the core team focus on the essentials, but also
encourage others to be creative within that framework.

We've been evolving towards having groups that take care of specific
things, like food, sponsorship, attendee care. We could push that further
with separate "working groups" that have a larger amount of autonomy.

We have a bit longer this time until the next workshop (6+ months), so some
of these could already start meeting early on.

We'll start with a sustainability working group which is responsible for
figuring out how to keep the ClojureBridge organization healthy and keep
people happy.

### floating

Make it part of the lunch-time coach check-in to evaluate if they can use
a floating coach, e.g. "are people advancing at different speeds?"

Encourage both the coaches and attendees more to reach out to the floating
coaches.

Encourage floating coaches to go up to groups to see how they're doing.

It's good to have experienced floating coaches, both in terms of coaches
and in terms of Quil.

### training

Seems not all coaches had studied the curriculum. Can we show more of it
already at the coaches training? Give people some pointers of how to go
through it, what to focus in.

We migh be able to cut out some of the current coaches training stuff.

We can invite people to the last learning group before the workshop to go
through the curriculum.

We got feedback of groups where there was a weird gender dynamic going
between the coaches and with the group. This is probably something we can
mention and talk about it during the training.

We could provide a time/space for coaches to check in with each other. We
could do it at the start of lunch, and give people a few questions to
discuss.

## Nightcode

Pain points this time

-   crashes a lot (Quil crashes causes the editor to crash)
-   before you could eval without selection, now you need to select the whole
    function
-   can't make text bigger/smaller

We also weren't using the latest version, those bugs could have been fixed
already.

Main takeaway is to communicate with the author before the workshop.

## curriculum

We had the offer of Stefan to take his German language Clojure book and run
with it. It's good to have that available for people who are more
comfortable reading German.

Complaints about current curriculum

-   it's too long
-   too much irrelevant stuff
-   current format is made for big group style teaching

We need to define what the goal of the workshop is, e.g.

-   have fun
-   make cool stuff in Quil
-   learn Clojure basics

### guidelines for guests at after party

Afterparty: Code of Conduct is still in effect, but it's a public venue, so
not everyone there will have agreed to it. There's not much we can do about
that, people affiliated with CB should still follow the CoC.

We could in principle ask bad actors to leave our table.

How about people inviting friends? If it's at an open venue then that
should be fine.

### employees of host company/other people related to the venue but not with us

It's always possible that people are around not directly related to CB. We
should at least ask that they wear some kind of badge/identification.

A good use case for the orga channel, we should have flagged this case.

## food/drink

The catering with Knoffi went quite well. There was some confusion about
vegan/not-vegan, but for most dishes it was clear.

We are offering a lot of sugary stuff, the breadrolls worked well, if you
offer spreads then people will eat them, so maybe we don't need muffins for
breakfast.

We also don't need 200 euro worth of cupcakes. A smaller amount of small
cupcakes would be better.

Maybe something extra for daytime snacking?

We'll let the food working group handle it further.

## photo

There are pros and cons to our current system but all in all it works, so
we'll keep it until further notice.

## childcare

Good that we went through the process. We now know where to go, the people
seemed professional. They also weren't upset when we cancelled very last
minute.

It would be good to let people confirm childcare a week beforehand.

## door phone

The phone should be fine, we just need to be more conscious about it so
it's not neglected.

Would be good to know beforehand who will be the door person, and brief
them.

Maybe have a backup like a twitter account with actual notifications enabled.

**Comment by vsmart** [comment]
Closing this! The action items are collected in https://github.com/clojurebridge-berlin/organization/issues/138
