### ISSUE TITLE
Post-workshop action items

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#138]
- [ ] review accounts, cycle passwords
- [x] ask in sign-up form where people are from to see if we can help
- [ ] coaches training email: make it more clear that it's not Unter den Linden
- [ ] have a way for coaches document install problems
- [ ] pick a date for the first sustainability working group meeting
- [ ] pick a date for the first curriculum working group meeting
- [x] add childcare to coaches & speaker sign-up forms
- [x] remove lightning talk field from coaches form
- [x] ask on the coaches sign-up form if they're ok with being floating coach
- [ ] for sign-up form language, split it into: "German", "English", "Either but German preferred", "Either but English preferred"
- [x] send receipts to Arne
- [x] wrap up finances (Arne)

**Comment by vsmart** [comment]
@plexus do you have all the finance stuff wrapped up?

**Comment by plexus** [comment]
Yes!

**Comment by vsmart** [comment]
Cycling passwords is tracked in #166, sustainability group is held in #139. 
The other points here are out of date.
