### ISSUE TITLE
Sustainability Working Group - Kickoff meeting agenda

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#139]
- how to keep everyone happy
- how to keep the organization healthy
- how to spread the load

**Comment by vsmart** [comment]
Still :heart: this idea, unfortunately no bandwidth for this right now. Let's revisit after the workshop :)

**Comment by daveliepmann** [comment]
I'm reopening (with the long-term/low-prio tag) so we remember to circle back to this circa November 2017.

I recommend that one part of this is identifying more clearly who the orga-team is as it changes over time. "Who has the keys to what" is still extremely opaque in-group knowledge.

**Comment by daveliepmann** [comment]
One part of that high opacity is, for instance, who should review PRs in each repo. Right now I request PRs pseudo-randomly, trying to get approval from someone who may have some sort of maximally-vague "ownership" related to the ticket. There's some threshold below which I feel empowered to merge my own PRs. Some more structure here could help.

**Comment by daveliepmann** [comment]
Some essential reading on the issue of hidden structures in flat organizations:

>"The Tyranny of Structurelessness" is an influential essay by American feminist Jo Freeman inspired by her experiences in a 1960s women's liberation group that concerns power relations within radical feminist collectives. ([wikipedia](https://www.wikiwand.com/en/The_Tyranny_of_Structurelessness))

[Full text [PDF]](http://struggle.ws/pdfs/tyranny.pdf)

**Comment by daiyi** [comment]
+1. I really want to step up for things and feel super motivated for certain tasks, but I super don't want to be stepping on peoples' toes, yet I don't want to be self-defeating. Having more clearly defined structure would help me funnel my energy in the most effective and least stressful way!
