### ISSUE TITLE
Set up learners registration

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#14]

**Comment by Malwine** [comment]
I will make a form with our new gmail account. 
clojurebridge.berlin@gmail.com

**Comment by Malwine** [comment]
Also I think we should set the form up in German as well.
Because some attendees might not be able to speak English.

**Comment by thatbettina** [comment]
@Malwine - since you were almost done with the form on Monday, I've assigned you the issue :)

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
It will be done soon. Then I close the issue.

**Comment by Malwine** [comment]
Done. Find the google doc in our ClojureBridge mail drive.
