### ISSUE TITLE
(Proposed) Timeline - Workshop 2017

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#142]
- Wk 0: May 29     
        -  Thursday June 1: Kickoff meeting
- Wk 4: June 26
        -  June 29th Orga Meeting 1 : Distribute Roles + Tasks
        -  Registration opens!
- Wk 8: July 24
        - Orga Meeting 2 : First Checkin
-Wk 12: End of August**
       - Orga Meeting 3 - Second Checkin
 - **Registration closes -  September 10, 2017**
- WK 15: Pre-final
       - Final Orga Meeting - September 21
- Wk 16: End of September 
       - **Coaches Training - September 28**
       - Attendees selected 
- Wk 18/later
       - **Installfest: 6 October**
       - **Workshop Day: 7 October**
- Mid-November
       - Retro + Team Celebration!

**Comment by vsmart** [comment]
You'll notice I left *a lot* of time/space in between orga meeting this time (roughly once a month). It'll be a nice experiment to have further spaced-out meetings and I hope it'll make us feel less stressed!

**Comment by vsmart** [comment]
Workshop date: 6/7 october

**Comment by daveliepmann** [comment]
We've decided on 6/7 October, right? 29/30 September is now deprecated?

**Comment by vsmart** [comment]
Yep, have updated OP with confirmed dates! :white_check_mark: @daveliepmann

**Comment by vsmart** [comment]
Took a quick look at the calendar --- how about hursday Nov 23 for Retro, Friday Dec 15 for celebration dinner? Let me know if those dates work :question: :thumbsup: :thumbsdown:
