### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#143]
With a date for next workshop confirmed, the next immediate step is to confirm the venue then. 

Since it's worked well for us in the past, I would consider Microsoft again. If I get some :+1: I'll get in touch and see if they are available. 

Thoughts/Comments? Or other venues you'd like to consider?

**Comment by ellenkoenig** [comment]
👍

**Comment by Realtin** [comment]
yep the structure of the microsoft office is really great for the workshop!
if it is somehow not possible to do it there we also have the option to ask the Amazon Warehouse Event Space.

**Comment by vsmart** [comment]
Ok, I got in touch with them! Only thing is, we'll need some help this time in form of an employee who helps out the whole Friday & saturday. Maybe we can offer them a workshop spot in exchange.

**Comment by Realtin** [comment]
What is with Ryan .. does he still work at wunderlist?

**Comment by Malwine** [comment]
Are you sure about MS? I heard new teams will be moving in on the 6th floor and thus making the space are inaccessible.

**Comment by vsmart** [comment]
@Malwine Hm, good to know. I'll ask katya about the details. I imagine that even if some rooms are not accessible it's still our best option. Do you have an alternative in mind?

**Comment by Malwine** [comment]
@vsmart You could ask Laura from RailsGirls about the rooms at HTW. (Pro: Accessible/Con: far out). 
I just want to make sure MS doesn't tell you last minute that you cannot have the space like 2 weeks before the event. There will be some construction works at some point this year- they wanted to build in an accessible toilet and one team + several colleagues moved in one of the rooms that we used before. Probably the space can still be used but there is a chance that it is not possible (as everybody would have to sign an NDA like for the floor above e.g.).

**Comment by vsmart** [comment]
I have confirmation that we can use Microsoft and they would also sponsor all drinks. I have yet to discuss Malwine's concern with them however.

**Comment by vsmart** [comment]
## alternative venue options 

* wunderlist - franka
* esmt - johanna @johannacarola
* aperto - anna looking into it
* htw - @daiyi to follow up with malwine/laura
* co_up - @dantoml / @vsmart (+ clue ? + redpineapplemedia) 
* gls sprachschule sponsored by ? - perhaps circleCI - http://gls-campus-berlin.de/veranstaltungsraeume-preise

Please post your findings in here.

**Comment by nblumoe** [comment]
If we need more options, I could ask at Wooga. Just let me know if I should reach out (seems like we have enough in the pipeline already).

**Comment by socksy** [comment]
It would be awesome if you could check if they could host it! All of the things in the pipeline are more just v. early considerations.

**Comment by vsmart** [comment]
yes please check! @nblumoe wooga is a great location! and they host game jams frequently which have similar requirements (one big meeting space, but then smaller rooms for quiet dev/coaching time) --- reminder, date is october 6/7th, but if they can only do the 7th, still worth considering.

**Comment by vsmart** [comment]
Update: 
* wunderlist - definitely out. only the retro space is free - confirmed by Katya from wunderlist  (could still be an option for coaches training + installfest?) 
* glsm has no availability - thanks @socksy for confirming
* wooga - looks like it's a go! 🎉 @nblumoe is in contact

**Comment by nblumoe** [comment]
For up to 40 people Installfest at Futurice could be an option.

**Comment by vsmart** [comment]
## Update: Wooga is happening :tada: 

@nblumoe and I went to speak with our contacts at Wooga today. The space looks great and I think will work well for us. There is a big auditorium and lots of small meetings room we can use, also for childcare and quiet rooms. One minus is they do not have accessible bathrooms. 

You can read the full questionaire at https://github.com/clojurebridge-berlin/organization/wiki/Venue-Questions:-Wooga
