### ISSUE TITLE
Email Address for Attendee/Coach/Newsletter Communication

### ISSUE THREAD

**Issue by Realtin** [clojurebridge-berlin/organization#144]
Using our gmail address leads to mail getting send to the spam folder (at least for other gmail users).

We could set up an email address from out Domain. Is that possible? Does someone has access to the account?

**Comment by plexus** [comment]
info@clojurebridge-berlin.org forwards to the gmail address, so you can use that. (just tested it and it seems to still work)

See https://github.com/clojurebridge-berlin/organization/issues/94

**Comment by vsmart** [comment]
Thanks @plexus!
