### ISSUE TITLE
Agenda - Orga Meeting #1

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#145]
When - Thursday June 29th, 7-9ish
Where - co_up, 3rd floor, Adalbertstr 8

please feel free to update the agenda to add missing points or post a comment below. 

# Agenda

* Venue: https://github.com/clojurebridge-berlin/organization/issues/143
* Discuss / and assign roles: 
  * catering
  * sponsors
  * speaker care
  * outreach
  * curriculum
  * coaches care
  * attendees care
* discuss and open registration form

**Comment by lislis** [comment]
I will probably not make it  to the meeting :(
Here some of my thoughts/ opinions:

- catering: Knofi has awesome food but we had issues with the 'all vegan' requirement. Question is do we live with that and go with a known option that is save or do we try a new (and maybe all vegan) caterer (I think we had some on a list somewhere?)

- outreach: do we want flyers? if so then we should make sure that we have them printed asap so we get a chance to distribute them well before we close registration.
We should probably also already decide on the number of attendees we want to accept and then decide how many coaches we need (I think the last workshop worked quite well?)

- Coaches care: Updating the coaches training slides to include description of floating coaches. We should be more explicit of what floating coaches are supposed to do and only have coaches assigned to it who are actually up for it. Plus also pay attention to have German speaking floating coaches. If this is not in the coaches form we should add it.

- attendees care: I'd be up again help with that. Provided @plexus sets up the awesome spreadsheet magic script again :)

Also, do we need to talk about  the curriculum already? Or does that have time until the next meeting?

**Comment by plexus** [comment]
just confirming that I'd be happy to get the attendomat going again. This can be done as soon as the attendee sign-up is live.

**Comment by nblumoe** [comment]
I also won't be able to join but I would be happy taking care of sponsorships and sponsor contacts.

Dave said something about updating the curriculum, maybe that should be on the agenda, too? Not sure though really, as I am not aware what the status is and who is involved.

**Comment by vsmart** [comment]
https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/49

**Comment by vsmart** [comment]
# preliminary task groups list
  * catering - Anna, saskia, julia
  * sponsors -  Nils, Dani
  * speaker care - Dani
  * outreach - Franka + Johanna
     * flyers/ posters / t-shirts??? - Tibor
  * coaches care - Chris & Saskia
  * attendees care - Lisa, Johanna
  * curriculum - Dave, rob
  * floating - Ben

**Comment by daveliepmann** [comment]
@codebeige do we have a t-shirt design or vendor? @socksy made a good point that t-shirts involve significant time pressure, so it would be good if we have everything ready before the time that we get sizes and can put in an order.

(I ping @codebeige because from the discussion last night folks said you wanted to handle this—please correct me if I am mistaken!)

**Comment by codebeige** [comment]
@daveliepmann Yes, there was a final design. I also asked for a quote on that from [cotton.de](http://cotton.de). See full discussion at #117. The Illustrator design file can be found in the repo [here](https://github.com/clojurebridge-berlin/organization/blob/master/design/t-shirt.ai). I am open to any change requests regarding the design and can take care of the order.

The main issue is all about the costs, though. We should probably not decide on spending such a significant amount of money before we have a final location and estimates for the mandatory costs.

**Comment by vsmart** [comment]
# Minutes from Orga Meeting 1

despite terrible rain, in attendance were: anna, johanna, ben, chris, dani, dave, david, lisa, franka

## Venue

There is a chance we might not be able to be at Microsoft since they are moving teams down to the 6th floor. Franka is in touch with them about this. Meanwhile, we are all exploring alternative venue options. 

=> *Action item* : Brainstorm venues and contact any you have been in mind. Keep us updated on this issue: https://github.com/clojurebridge-berlin/organization/issues/143 

## Task distribution

We talked through what each task entails. After that we came up with this preliminary list of people: 

  * catering - Anna
  * sponsors -  Nils, Dani
  * speaker care - Dani
  * outreach - Franka + Johanna
     * flyers/ posters / t-shirts??? - Tibor
  * coaches care - Chris & Saskia
  * attendees care - Lisa, Johanna
  * curriculum - Dave 
  * floating - Ben

Franka will set up issues for each of those with links to our documentation get people started on their item. (watch out for those this weekend!)

## Registration form

We made some updates to the registration form and it's ready to go live pending this:

=> *Action item* Check in with @plexus on how to send up the auto response in Google Forms.

**Comment by vsmart** [comment]
Moving to https://github.com/clojurebridge-berlin/organization/issues/155
