### ISSUE TITLE
Venue questionaire -- Wooga

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#146]
It looks like we'll be able to use Wooga for the Saturday. Yay! Thanks @nblumoe for making this happen. 🎉 

Here is the questionaire for the venue: https://github.com/ClojureBridge/organizing/blob/master/Hosting-venue-questions.md

For comparison, you can see the wunderlist one here: https://github.com/clojurebridge-berlin/organization/blob/master/2016-01-22/venue.md

**Comment by nblumoe** [comment]
Woah, ok, pretty long list. :) Do you just forward that in the past?

**Comment by vsmart** [comment]
@nblumoe I think the most important parts are the first three sections: Space, Security, Equipment. The parking/catering/etc is not relevant for us.

**Comment by vsmart** [comment]
I would say it's too optimistic to let them fill it out. As I said in slack, I think the best course of action is for you to schedule a time with them to have a coffee, discuss these questions in person, and have a look around the venue to see which rooms they will give us. I would like to also be present for this if possible.

**Comment by nblumoe** [comment]
Thanks, sounds like a good plan. Let's proceed like that, just sent the email.

**Comment by vsmart** [comment]
Awesome, thanks again @nblumoe! I think wooga will be a great venue!! 👯

**Comment by vsmart** [comment]
I've added the filled-in questionnaire here https://github.com/clojurebridge-berlin/organization/wiki/Venue-Questionnaire-----Wooga
