### ISSUE TITLE
Contact Sponsors

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#147]
This is a list of potential sponsors! We don't need to contact all of them, it's just a pool.

Last sponsoring issue: https://github.com/clojurebridge-berlin/organization/issues/98

### How to contact a sponsor! 
* Pick a sponsor you'd like to contact from the list below, or other
* Write an email to contact them - it's best if you have a personal contact there, rather than emailing generic hello@company
* You can draft your own email, or use one of our [templates](https://github.com/clojurebridge-berlin/organization/wiki/All-email-templates#sponsors)
* Make sure to include a link to our [sponsor tiers](http://clojurebridge-berlin.org/sponsor-us/) in your email.
* In the email, put `clojurebridgeberlin@gmail.com` in cc 
* Update this list: box ticked like `[x]` means the company has been contacted. Also put your name after the company name in -- or comment underneath the issue - that way we can track which companies we're in touch with.

### confirmed sponsors

* CircleCI -- platinum 
* Mapbox -- gold
* Zimpler  -- tshirts 

### Potential sponsors 

~~strike through~~ == out
**bold** == accepted
- [ ] 8th Light
- [ ] ableton - Julia 
- [ ] Adjust 
- [ ] Asquera - Julia ?
- [ ] babbel (Nicola)
- [ ] bitcrowd - chris
- [x] Blacklane - Franka
- [x] **CircleCI** (Dani)
- [ ] codecentric
- [x] Cognitect (Arne?)
- [ ] Contenful
- [ ] Dawanda
- [x] Futurice -- Nils
- [ ] Github - Dani
- [ ] Hitfox
- [ ] ImmoScout
- [ ] InnoQ
- [ ] Jayway
- [ ] Juxt 
- [ ] Lambdawerk
- [x] Mapbox (franka)
- [ ] Metosin
- [x] Microsoft / Todo Team (Franka?)
- [ ] Mixcloud
- [ ] MixRadio
- [ ] Mozilla - chris
- [x] **NextJournal** (Saskia / chris / arne?)
- [x] N26 - Nils
- [ ] O'Reilly
- [ ] Otto
- [ ] Pragmatic Programmers
- [ ] PurelyFunctional.tv
- [ ] Red pineapple media
- [ ] Siili
- [ ] Small Improvements
- [x] ~~SoundCloud - chris~~
- [x] Thoughtworks - Franka/Nicola/chris
- [ ] Ticketsolve
- [ ] Twilio
- [ ] Zalando
- [ ] Studio NAND

![money cat](https://media.giphy.com/media/ND6xkVPaj8tHO/giphy.gif)

**Comment by Malwine** [comment]
OMG! I just came here for the gif. 😆 So COOL!

**Comment by nblumoe** [comment]
contacting Futurice. seems like I cannot edit the list that @vsmart posted directly

**Comment by lislis** [comment]
- [x] zimpler 
```
Contact
Jean-Louis Giordano
jean-louis@zimpler.com
```

**Comment by lislis** [comment]
I opened an issue for t-shirt sponsorship as well https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/53

**Comment by lislis** [comment]
I made a PR to add a tshirt sponsorship to the website https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/55
Let me know what you think

**Comment by vsmart** [comment]
@saskali @daiyi Could you contact NextJournal?

**Comment by saskali** [comment]
I want to talk to them tomorrow and will let you know what they say!

**Comment by lislis** [comment]
Gonna write zimpler an email later today

**Comment by daiyi** [comment]
^Jean-Louis from zimpler is going to be at the clojure berlin meetup this week if you'd like to speak in-person!

**Comment by lislis** [comment]
@daiyi yeah, we had a brief exchange via email. He will look at the zimpler budget and we will talk details on Wednesday :)

**Comment by daiyi** [comment]
I reached out to folks at Thoughtworks and Soundcloud :ok_hand: (waiting to hear back!) (and these are big companies so I assume others should also try to make contact if they can?)

**Comment by vsmart** [comment]
@daiyi sure! It's worth mentioning that they have sponsored us in the past, and thank them for that.

**Comment by lislis** [comment]
So, Jean-Louis confirmed that zimpler will pay for all the tshirts!! We can have t-shirts!! 
It would be easiest to just forward them the invoice from the print shop (print shop should accept cc).
If possible they would also like some t-shirts for themselves, so we can order some extras

**Comment by vsmart** [comment]
we need to :thought_balloon: who to match with what
maybe 
circle ci  ==> lunch catering
mabpox ==> coaches + installfest catering

**Comment by vsmart** [comment]
Judging from the list of sponsors I saw in #168 (circle, mapbox, cognitect, zimpler, nextjournal) 
we have enough sponsors and can close this issue. 

Awesome work y'all 👏 👏 👏 💸 💸 💸
