### ISSUE TITLE
Open registration form 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#148]
At the last orga meeting, we went through the form and updated it to match the latest info. 

We still need to:
* [x] set up auto response form
* [x] verify it works
* [x] set form to public/accepting responses

**Comment by plexus** [comment]
Auto-responder can be set up with this add-on https://chrome.google.com/webstore/detail/form-notifications/bbpdeojefjfhaelgljjcadpcckdfcdod

**Comment by vsmart** [comment]
@lislis will take a stab at this! :hocho:

**Comment by lislis** [comment]
I set up the auto response and it works.

This is the copy, let me know if you want to change it:

> **Thank your for applying at ClojureBridge Berlin | Danke für deine Bewerbung für ClojureBridge Berlin**  

> We received your application. Thank you!
You'll hear back from us once we'll close the application form.
--
> Wir haben deine Bewerbung erhalten. Vielen Dank!
Wir melden uns bei dir sobald wir die Anmeldefrist vorbei ist.
>  ClojureBridge Berlin

Other than that I'm good to go

**Comment by vsmart** [comment]
@lislis is this a new copy or reusing the one we previously had?

**Comment by lislis** [comment]
@vsmart new copy, I couldn't find the older version.

Also, is there a date this should go live?

**Comment by vsmart** [comment]
@lislis I'll try to dig up the old version just to see if there was anything important in there that we may have missed 🤔 
How we about we push it live this Thursday at the orga meeting?

**Comment by lislis** [comment]
@vsmart sure. If I have internet on the train I can join or at least put it live then

**Comment by vsmart** [comment]
@JohannaCarola will check the response text! Then we can compare them!

**Comment by JohannaCarola** [comment]
This is the response text from last time:

Hi,

Congratulations, you are now registered for ClojureBridge Berlin! The workshop takes place on a Friday evening and Saturday during the day, 25th and 26th of November. Make sure to mark the date in your calendar!

Unfortunately places are limited so we can't yet guarantee you a spot. We will get back to you once registration closes (6th of November).

Best,

ClojureBridge Berlin Team

---

Hi,

du hast dich erfolgreich für ClojureBridge Berlin registriert. Der Workshop findet am Freitag, den 25. November und Samstag, den 26. November statt. Wir bitten dich, diese Daten zu notieren.

Leider gibt es immer mehr Bewerbungen als wir Plätze anbieten können, deswegen melden wir uns nochmal nach dem Ende der Anmeldefrist (am 6. November) und teilen dir mit, ob du ausgewählt wurdest.

Bis dann,

ClojureBridge Berlin Team

**Comment by JohannaCarola** [comment]
if we're re-using last year's auto-reply we should maybe adjust it to indicate that the Friday portion of the workshop is only in the evening? 

I also don't really like that the German text from last year uses the word "ausgewählt". Maybe we could change it to:
"... und teilen dir mit, ob du einen Platz bekommen hast." 

What do you think?

**Comment by vsmart** [comment]
SUBJECT: [ClojureBridge Berlin] Thanks for signing up!

---

**Thank your for applying to ClojureBridge Berlin | Danke für deine Bewerbung für ClojureBridge Berlin**

Hi,

Thank you for applying to ClojureBridge Berlin. We have received your application.
The workshop takes place on a Friday evening and Saturday during the day, October 6th and 7th . Make sure to mark the date in your calendar!

Unfortunately places are limited so we can't yet guarantee your spot. We will get back to you once registration closes - 10th September.

Best,
ClojureBridge Berlin Team 

---

Hi,

Wir haben deine Bewerbung erhalten. Vielen Dank! Der Workshop findet am Freitagabend und Samtag, 6. und 7. Oktober statt. Bitte merke diese Termine vor!

Leider gibt es immer mehr Bewerbungen als wir Plätze anbieten können, daher ist dein Platz noch nicht garantiert. Wir melden uns nochmal bei dir nach dem Ende der Anmeldefrist - am 10. September.

Bis dann,
ClojureBridge Berlin Team

**Comment by vsmart** [comment]
hi @lislis :wave: Could you update the autoresponse to the text above ^^^ 
(for reference, taken from  https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Attendee-Signup-Confirmation-Email) 
Once that's done, we can make it public and set it to accept responses \o/

**Comment by lislis** [comment]
Updated the email response. 
Do you want to go online asap or wait until Monday?
Also, do we have a PR for the website ready + announcement for the mailing list?

**Comment by lislis** [comment]
Made a PR for the website https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/54
Will we use the same form for the coaches?

**Comment by lislis** [comment]
Alright!
I copied and prepped the coaches form (https://github.com/clojurebridge-berlin/organization/issues/157) and as per https://github.com/clojurebridge-berlin/organization/issues/138 also added a field to both attendee and coaches form to ask whether people plan to travel to Berlin just for the workshop so we can maybe help them out and prepare better.

**Comment by lislis** [comment]
this is done! I'll set a reminder in slack to close it on September 10th
