### ISSUE TITLE
Catering - Lunch 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#149]
The biggest meal we provide during the workshop is lunch catering. 

Here are some resources to get you started: 

🍔 *Lunch Fun Facts*: 🍔
  * should preferably be all-vegan
  * should be warm and hearty - since it's a cold season, but also since attendees tend to be VERY hungry! 
  * approximate numbers, judging from last workshop: ~65 people
  * caterer must be prepared to cater to allergies -- glutenfree, etc 

Here is a [list of potential caterers](https://github.com/clojurebridge-berlin/organization/wiki/List-of-Potential-Caterers) from last time. I think especially the first listing, notiers.de sounds interesting. 

## How to contact a caterer 

* Send an email - or call them. (Have made better experience with calling them directly) 
* Include the *lunch fun facts* in your enquiry
* Get an $$ offer from them 
* Come back to this issue, so we can compare options and offers! :100: 

![turn food into code](https://media.giphy.com/media/5wWf7HapUvpOumiXZRK/giphy.gif)

**Comment by saskali** [comment]
Potential caterers

strike through == out
bold == accepted
box ticked == caterer has been contacted

- [x] noTiers (Anna)
- [x] Playing with Eels (Anna)
- [ ] Suppen Cult
- [ ] Sfizy Veg
- [x] Knofi (Anna)
- [ ] Miriam Lappenberg
- [ ] Bleibtreu 
- [x] Red Star Catering (Anna)

**Comment by Realtin** [comment]
Catering for InstallFest & Coaches Training --> https://github.com/clojurebridge-berlin/organization/issues/165

**Comment by daveliepmann** [comment]
Let's not forget breakfast: http://www.schlomos.com/

**Comment by pepper-aenn** [comment]
I got the first menu from a caterer called Lebenswelten. Here is their proposal:

WORKSHOP LUNCH - TOTALLY VEGAN
Kürbis- Apfelcremesuppe-  glutenfrei- zwiebelfrei 
Märkisches Landbrot und kleine Brötchen
glutenfreie Brötchen
Avoccadodip/ Paprikadip
Gelbes Thai Curry mit Mango und Gemüse- glutenfrei- zwiebelfrei- pilzfrei
Süss saures Gemüse mit Ananas, Koriander und Ingwer  -glutenfrei- zwiebelfrei- pilzfrei
Paprika- Pilzgulasch mit Seidensaitan
Kleine Rosmarinkartoffeln
Duftreis,Polenta -Ab 60 Pers  9,00 Euro p Pers

V salad bar additional 2,00 p.P.

additional costs: Logistik / Aufbau/ Abholung berechnen wir mit 69,00 € pro Stunde, abgerechnet nach tatsächlichemAufwand.alle Preise zzgl 7% Mwst.

what do you think?

**Comment by Realtin** [comment]
I like it! @pepper-aenn

**Comment by pepper-aenn** [comment]
Update: 

Lunch Catering with Lebenswelten is confirmed!

**Comment by vsmart** [comment]
Lunch was delicious and plentiful \o/ Thank you so much @pepper-aenn for getting this sorted. 
Let's discuss any remaining payment questions in #176
