### ISSUE TITLE
Add us to the main ClojureBridge site

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#15]
- Give them the Github username of the person who acts as the "face" of the event
- Write the event description using current events as a template
- list sponsors with logo files (or URLs) and a link to their home page 
- Include sign up form link for learners

**Comment by thatbettina** [comment]
So we're almost ready to get listed on ClojureBridge. 

I copied ClojureBridge London's event description and edited it for Berlin; I would like your feedback on all of the text, especially the stuff I wrote in caps.

---

This workshop will be in held Berlin, Germany and is intended for those with none/some programming experience. We will use Clojure, a modern programming language running on the Java virtual machine, to introduce you to fundamental programming concepts. We plan to have 33 learners and 11 coaches. You will learn and practice in small groups of 2 to 4 attendees each. To register, you must identify as a woman. Men, you are welcome to come if you find a woman who wants to learn Clojure who will register and bring you as a guest.

Core Organizers: @ThatBettina @martinklepsch @plexus @Malwine @nicsnet @jellea HOPE EVERYONE'S TWITTER HANDLES ARE THE SAME AS THEIR GITHUB ONES?

E-mail: MALWINE's EMAIL HERE???

Additional Info You Should Know
In this workshop, we'll take you through building a sample app using Clojure. We'll meet up Friday late afternoon to install all of the software you need, and then spend Saturday learning and writing code. Each participant needs to bring her or his own computer with fairly recent Mac, Linux or Windows installation. If you have questions about your hardware, send an e-mail to the organizers before the event!

Sometimes people ask if the Friday night Installfest is mandatory, and yes, it is! It's a crucial part of the weekend, even if you’ve already gone through the instructions independently. There are a ton of moving parts when setting up a development environment, and the reason that we’re able to get through the curriculum on Saturday is that every single student has had their dev environment checked and has been awarded a temporary tattoo for their successes.

If you have questions or ideas for us, the best way to get in touch is to send an e-mail or tweet to the organizers. To receive updates you can follow us on Twitter WHICH TWITTER HANDLE??

ClojureBridge Berlin takes place at AHOY / DAWANDA?. Drinks will be provided throughout the event on Saturday by DaWanda, and we are still looking for sponsors for lunch on Saturday. We want to provide a safe and welcoming environment for everyone, so we will be asking all learners and event volunteers to respect our CODE OF CONDUCT, which will be strictly enforced. Our aim is that ClojureBridge Berlin will introduce learners to new possibilities in programming and make the tech community in Berlin a more diverse and interesting place.

Sponsors for Berlin ClojureBridge Workshop
DaWanda 
Ahoy?

**Comment by martinklepsch** [comment]
> To register, you must identify as a woman.

> WHICH TWITTER HANDLE?

I have @clojureberlin and could share the login details so someone can keep people updated through that channel. I can also be that someone but I'm happy to have more people tweeting from that account :)

**Comment by martinklepsch** [comment]
> To register, you must identify as a woman.

While this is probably a broader thing with regards to ClojureBridge these events should also attract really **any** underrepresented group in technology right? To me this also includes homosexuals and non-white people. It's not a big deal as most people will probably be women but I just wanted to leave that as a thought here.

> We plan to have 33 learners and 11 coaches.

How about 35 learners and 15 coaches... nicer numbers to my eyes, hehe :)

> WHICH TWITTER HANDLE?

I have @clojureberlin and could share the login details so someone can keep people updated through that channel. I can also be that someone but I'm happy to have more people tweeting from that account :)

> Sponsors for Berlin ClojureBridge Workshop

Probably we don't need to list Ahoy as it goes through DaWanda? Also there might potentially more sponsors later on?

**Comment by Malwine** [comment]
Dear Bettina! Thanks a lot for the writing/editing the text! :+1: 

My twitter handle is **@malweene**  

**Sponsors**  

> Probably we don't need to list Ahoy as it goes through DaWanda? Also there might potentially more sponsors later on?  

Well yes, Ahoy has not much to do with it, i guess.

**Email**

> E-mail: MALWINE's EMAIL HERE???

I would prefer having a general mail like in London: _E-mail: clojurebridge.london@gmail.com_
Like clojurebridge.berlin@gmail.com
I can open this account!

**Twitter**
I think its best to use clojureberlin because there are already some followers :smile:

**Comment by Malwine** [comment]
I opened an account for clojurebridge.berlin@gmail.com !

**Comment by Malwine** [comment]
This workshop will be in held Berlin, Germany and is intended for those with none/some programming experience. We will use Clojure, a modern programming language running on the Java virtual machine, to introduce you to fundamental programming concepts. We plan to have about 30 learners and 10 coaches. You will learn and practice in small groups of 2 to 4 attendees each. To register, you must identify as a woman. Men, you are welcome to come if you find a woman who wants to learn Clojure who will register and bring you as a guest.

Core Organizers: @ThatBettina @martinklepsch @plexus @malweene @nicsnet @jellea 

E-mail: clojurebridge.berlin@gmail.com

Additional Info You Should Know
In this workshop, we'll take you through building a sample app using Clojure. We'll meet up Friday late afternoon to install all of the software you need, and then spend Saturday learning and writing code. Each participant needs to bring her or his own computer with fairly recent Mac, Linux or Windows installation. If you have questions about your hardware, send an e-mail to the organizers before the event!

Sometimes people ask if the Friday night Installfest is mandatory, and yes, it is! It's a crucial part of the weekend, even if you’ve already gone through the instructions independently. There are a ton of moving parts when setting up a development environment, and the reason that we’re able to get through the curriculum on Saturday is that every single student has had their dev environment checked and has been awarded a temporary tattoo for their successes.

If you have questions or ideas for us, the best way to get in touch is to send an e-mail or tweet to the organizers. To receive updates you can follow us on Twitter: @ClojureBerlin

ClojureBridge Berlin takes place at DaWanda's rooms of Ahoy co-working space. Drinks will be provided throughout the event on Saturday by DaWanda, and we are still looking for sponsors for lunch on Saturday. We want to provide a safe and welcoming environment for everyone, so we will be asking all learners and event volunteers to respect our CODE OF CONDUCT, which will be strictly enforced. Our aim is that ClojureBridge Berlin will introduce learners to new possibilities in programming and make the tech community in Berlin a more diverse and interesting place.

Sponsors for Berlin ClojureBridge Workshop:
DaWanda 

[LINK TO SIGNUP](https://github.com/clojurebridge-berlin/organization/issues/16)

**Comment by Malwine** [comment]
What do you think?

**Comment by martinklepsch** [comment]
I think it's great! :tada:

**Comment by Malwine** [comment]
I want to add the link to the form before we send them the text.

**Comment by Malwine** [comment]
Deutsch:
Diese Workshop findet am 10. & 11. Juli in Berlin statt und ist für Anfängerinnen bestimmt mit keiner oder wenig Erfahrung im Programmieren.
Wir geben euch eine Einführung in die moderne Programmiersprache Clojure, um euch einige fundamentale Programmierkonzepte vorzustellen. Im Workshop werdet ihr auch eine kleine App mit Clojure bauen.
Wir treffen uns am Freitag Abend, um die Software zu installieren, die wir brauchen werden.
Am Samstag werden wir dann den ganzen Tag lernen und programmieren.
Ihr werdet in kleinen Gruppen zwischen 2 - 4 Personen lernen.
Um euch anzumelden, solltet ihr euch als Frau identifizieren.
Männer sind willkommen, wenn sie als Begleitung einer Teilnehmerin kommen.

English:
This workshop will be in held Berlin, Germany and is intended for those with none/some programming experience. We will use Clojure, a modern programming language running on the Java virtual machine, to introduce you to fundamental programming concepts. We plan to have about 30 learners and 10 coaches. You will learn and practice in small groups of 2 to 4 attendees each. To register, you must identify as a woman. Men, you are welcome to come if you find a woman who wants to learn Clojure who will register and bring you as a guest.

Core Organizers: @ThatBettina @martinklepsch @plexus @malweene @nicsnet @jellea

E-mail: clojurebridge.berlin@gmail.com

Additional Info You Should Know
In this workshop, we'll take you through building a sample app using Clojure. We'll meet up Friday late afternoon to install all of the software you need, and then spend Saturday learning and writing code. Each participant needs to bring her or his own computer with fairly recent Mac, Linux or Windows installation. If you have questions about your hardware, send an e-mail to the organizers before the event!

Sometimes people ask if the Friday night Installfest is mandatory, and yes, it is! It's a crucial part of the weekend, even if you’ve already gone through the instructions independently. There are a ton of moving parts when setting up a development environment, and the reason that we’re able to get through the curriculum on Saturday is that every single student has had their dev environment checked and has been awarded a temporary tattoo for their successes.

If you have questions or ideas for us, the best way to get in touch is to send an e-mail or tweet to the organizers. To receive updates you can follow us on Twitter: @ClojureBerlin

ClojureBridge Berlin takes place at DaWanda's rooms of Ahoy co-working space. Drinks will be provided throughout the event on Saturday by DaWanda, and we are still looking for sponsors for lunch on Saturday. We want to provide a safe and welcoming environment for everyone, so we will be asking all learners and event volunteers to respect our CODE OF CONDUCT, which will be strictly enforced. Our aim is that ClojureBridge Berlin will introduce learners to new possibilities in programming and make the tech community in Berlin a more diverse and interesting place.

Sponsors for Berlin ClojureBridge Workshop:
DaWanda 

LINK TO SIGNUP // TODO

**Comment by Malwine** [comment]
It needs some rework though. Not sure if I should translate the whole text or also shorten the english text.

**Comment by martinklepsch** [comment]
I think a portion in German is enough — realistically people with no English "skills" would have a hard time participating as the curriculum is only available in English?

**Comment by Malwine** [comment]
And there is a point I disagree. :disappointed_relieved:

I was thinking about my fellow students. Some of them are beginner programmers but their English is not that well. Or even worse, the whole description in English would block them from applying.
If we say that people with poor English skills cannot participate then we are **not inclusive**.

I know that the examples in the curriculum are in English. And that is fine.
But we should offer **description, application and coaches language** in German as well.

**Comment by nicsnet** [comment]
I agree wholeheartedly with Malwine. I can assist with any outstanding translations. I would also   volunteer to coach in German.

**Comment by martinklepsch** [comment]
Is it realistically possible for someone to get coached - not taught -
without being able to read the curriculum?

I'm very much in favor of being as inclusive as possible I'm just not sure
if it's a good idea without a translation of the curriculum (which is
probably a worthwhile thing to tackle in any case).

**Comment by martinklepsch** [comment]
Maybe there has been a misunderstanding here. Are we aiming to have attendees that cannot read English?

**Comment by Malwine** [comment]
@martinklepsch Yes, I think it is an misunderstanding. I will contact you later to sort it out. :smile:

**Comment by thatbettina** [comment]
@Malwine @martinklepsch @nicsnet We should meet to finish the text soon, even over Google Drive because then we can all edit the same document without being in the same place. I am, however, for a core organizers' meeting separate from our coding night. I will send around a Doodle so that we can find a time.

**Comment by Malwine** [comment]
:+1: for the meeting 
and I put the text in Google Drive and give you access.

**Comment by Malwine** [comment]
@thatbettina and everyone who is interested: 
I edited our text for the website and are nearly done now.
Moreover, I took overhead information out and transated the main part to German.
Please have a look at the document in Google drive.
I send you the link to your mail accounts.

**Comment by Malwine** [comment]
:dancer:

**Comment by thatbettina** [comment]
http://www.clojurebridge.org/ 

For any edits or updates, please make a comment here. I will email them on Thursdays with all the changes we may have as the website maintainer will update on Fridays.

**Comment by Malwine** [comment]
Thank you Bettina!

First remark:
They only linked the english application :(
This is **not** cool.
But I don't know if they have possibilities to link 2 forms.

**Comment by Malwine** [comment]
I would like to ask them if we can have the german application as a link.
Maybe they didnt recognize that it were two different apllication forms.

**Comment by Malwine** [comment]
DaWanda can be added as a sponsor on Friday.

**Comment by thatbettina** [comment]
Hey @Malwine -- I'll ask them again; there probably isn't two big buttons they can make for us. I'll cc our gmail account

**Comment by Malwine** [comment]
I saw her mail, she added a link. That is fine I think :blush:

**Comment by Malwine** [comment]
Let's make a list for next friday(you can edit):
- Include DaWanda as a sponsor, file from here or I will also upload in our drive
  ![dawanda](https://cloud.githubusercontent.com/assets/5123681/7438027/1fbe1e4c-f05e-11e4-891b-1f05f28d982d.png)
- add out mail-address to the description or in contact section clojurebridge.berlin@gmail.com

**Comment by thatbettina** [comment]
I started a new issue for edits and adds (https://github.com/clojurebridge-berlin/organization/issues/25) since this issue was to get us up on their website. Let's please close this because I LOOOOVE closing issues and getting things done :)

**Comment by Malwine** [comment]
:+1: Close all the things :smile:
