### ISSUE TITLE
Order new stickers

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#150]
We need new stickers!

* Possibly 🏳️‍🌈 stickers
* Possibly some that look good on a black background

cc @martinklepsch

**Comment by Malwine** [comment]
@vsmart @martinklepsch Maybe we could have the pride/rainbow stickers with a transparent ClojureBridge lettering. So it will be black lettering on black computers. Then it is also better readable then white lettering on yellow underground :) 

P.s. I am very excited about the rainbow stickers.

**Comment by martinklepsch** [comment]
All stickers ordered already. Adjusted the colors on the rainbow a bit so
that the contrast is better. The white lettering looked better compared to
black when I tried it.

Got 500 each of the following:
- clojurebridge regular
- clojurebridge pride
- Clojure Berlin
- Clojure Berlin (generative)

All 45mm on matte white foil. I'll upload the files used for printing later
as well. Hope to pick them up Wednesday next week.

**Comment by plexus** [comment]
Cool stuff! Where did you order them from?

**Comment by martinklepsch** [comment]
Ordered them from Typographus.de as per Lisa's recommendation :)

**Comment by vsmart** [comment]
Yay, thanks @martinklepsch! Excited for new stickers!

**Comment by martinklepsch** [comment]
@vsmart @codebeige I added the files to `./design` including the TIFF files used for printing (+ small README) and the source file (Affinity Designer). 

For posterity here's a screenshot of all the 4 motives, you'll have to imagine that they are all round for now 😛 

<img width="1244" alt="screen shot 2017-07-13 at 11 02 39" src="https://user-images.githubusercontent.com/97496/28166281-93bffd36-67d7-11e7-8139-3d7d2bd396a5.png">

**Comment by vsmart** [comment]
ohhh is the second one from that talk we saw?

**Comment by vsmart** [comment]
Thanks @martinklepsch! new stickers are ⭐️ ⭐️ ⭐️
