### ISSUE TITLE
Posters and Flyers

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#151]
We will need posters & flyers again for outreach. 

Steps to get this done are: 

* [x] Update design files from last year to update dates 
* [x] optional: any other design changes
* [x] Send off for printing! 

Our design files are in this repo: https://github.com/clojurebridge-berlin/organization/tree/master/design

We should try to print less flyers this year, I still have ~200 at home from last year. 

@codebeige volunteered to take this on again, after doing a great job last year! :tada: 
@codebeige, let us know what support or input you need for this. 

It would be great to finish this out by the end of July, so we can start outreach soon.

**Comment by codebeige** [comment]
I would love to take care of this. 👨🏼‍🎨

Are the dates already finalized yet? Any change requests for the copy text?

Flyer and Poster designs from last here can be previewed and/or downloaded here:
- [Flyer](https://github.com/clojurebridge-berlin/organization/blob/master/documents/11:16%20flyer%20final.pdf)
- [Poster](https://github.com/clojurebridge-berlin/organization/blob/master/documents/11:16%20poster%20final.pdf)

**Comment by vsmart** [comment]
Hi @codebeige. Dates are finalized: October 6th and 7th. Registration closes  September 10, 2017. 

I gave a quick glance over the old posters, I think the copy text is great as it is! 

And thanks for offering to jump on this again! :heart:

**Comment by codebeige** [comment]
I am in the works of updating the design and plan to be finished by the end of the week.

**Comment by codebeige** [comment]
This is what I came up with this time. Looking forward to your feedback tomorrow...
![170724 poster and flyer_poster](https://user-images.githubusercontent.com/91858/28642399-9ad891fc-7252-11e7-9f64-9ad3e23289c2.png)

---

![170724 poster and flyer_flyer front kopie](https://user-images.githubusercontent.com/91858/28642408-9f600048-7252-11e7-9963-0827df847c8a.png)

---

![170724 poster and flyer_flyer front](https://user-images.githubusercontent.com/91858/28642410-a2d63274-7252-11e7-8764-f7f20417e252.png)

**Comment by martinklepsch** [comment]
Love it! Legibility of the Twitter handle could maybe be improved if anything.

**Comment by codebeige** [comment]
Here is an updated version of the flyer front. This can also be used as a banner for emails.

![flyer alternate](https://user-images.githubusercontent.com/91858/28685931-ca783022-7309-11e7-934d-14ce9374cfe1.png)

**Comment by vsmart** [comment]
@codebeige looks awesome! Thank you! :clap:

**Comment by lislis** [comment]
@codebeige when do you think you can have the flyers printed?

**Comment by codebeige** [comment]
I am currently preparing the final data for the printer and will order later tonight. The posters and flyers should arrive some time next week. (08.08.)

@vsmart What is the exact address for delivery?

**Comment by codebeige** [comment]
Order is placed.

I have also created a dedicated image that can be used inside emails: [banner.png](https://raw.githubusercontent.com/clojurebridge-berlin/organization/master/design/email-banner.png)

**Comment by daveliepmann** [comment]
Thank you, @codebeige ! 👍 💯

**Comment by vsmart** [comment]
@codebeige ![thank you](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif) !!
did you ship them to coup? or your house?

**Comment by codebeige** [comment]
@vsmart Shipping to you at co.up coworking as I will be on vacation most of August.

[Ihre Bestellung PDB17134221 bei PinguinDruck.pdf](https://github.com/clojurebridge-berlin/organization/files/1195253/Ihre.Bestellung.PDB17134221.bei.PinguinDruck.pdf)
