### ISSUE TITLE
Attendee Outreach 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#153]
Once our registration form is open (tracked in #148), we can start reaching out to various groups and organizations! 

We have a list of email templates here: https://github.com/clojurebridge-berlin/organization/wiki/All-email-templates#attendees

For any group that has a technical audience (e.g. Women Who Code) please also include a sentence that we're looking for coaches: "We are also looking for coaches, especially nb people and women! Get in touch if you'd be interested."

Check off any group you've contacted, and put your name - or post a comment below. 

## Our media channels

* [x] post on twitter
* [x] announce on our mailing list 

## Posters and Flyers 

* [x] Get them ready: #151 
* [x] Put them up around town - street posts, libraries, bars, etc

## Post on mailing lists, facebook groups

- [ ] rubymonstas
- [x] rubycorns (Lisa)
- [x] Berlin geekettes 
- [ ] FU frauen@   
- [ ] FU lesbitransintera@ 
- [ ] FU  info@
- [ ] reflect-info mailing list
- [ ] HTW FIW 
- [ ] RailsGirls Berlin General Newsletter 
- [ ] NodeSchool Berlin Newsletter
- [x] Heart of Code Slack (Lisa)
- [ ] Women In Tech Slack # loc-europe 
- [ ] women-in-tech-eu slack #berlin 
- [ ] BerlinJS Slack #events
- [ ] lambdaladies 
- ~[ ] Upfront Meetup~ Upfront is on summer break until after our application deadline
- [ ] Ruby User Group
- [ ] women tech makers group: https://www.facebook.com/groups/1106085959408694/
- [x] HU mailing list [johanna]

## Email event calendar sites 

- [x] http://maedchenmannschaft.net/ - post(at)maedchenmannschaft.net 
- [ ] http://missy-magazine.de - redaktion at missy-mag.de
- [ ] stressfaktor - http://stressfaktor.squat.net/terminator.php 
- [ ] http://www.l-mag.de/l-termine/termin-aufgeben.html 

## Poster

- [x] TU (Ben)

## Other ideas? 

Please comment below with more ideas! 

posting an octopus gif because i picture us reaching out to friends like an octopus with tentacles, only even nicer!

![octopus](https://media.giphy.com/media/xT1XH40OxC6wDmNwPK/giphy.gif)

**Comment by JohannaCarola** [comment]
I can also send something to the HU mailing list, or are there any objections to these university wide mailing lists?

**Comment by vsmart** [comment]
@JohannaCarola yes definitely!! you can have a look at these templates here https://github.com/clojurebridge-berlin/organization/wiki/All-email-templates#attendees . I've added it to the list.

**Comment by daveliepmann** [comment]
A suggestion came in, perhaps for next time, to reach out to Unicorns in Tech.

**Comment by vsmart** [comment]
Signs up are closed now with 109 interested attendees! :tada:
