### ISSUE TITLE
Agenda - Orga Meeting 2 -Thursday 27/7

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#155]
Catch up on the latest update: https://github.com/clojurebridge-berlin/organization/issues/154
Last meeting's agenda:  https://github.com/clojurebridge-berlin/organization/issues/145

## When & Where

* Thursday October 27 - 7-9pm
* Where: co-up 3rd floor
* snacks are welcome :sparkles: 

## Agenda for Thursday

* 19:00 arrivals and snack
* 19:15 status checkins:
  * venue https://github.com/clojurebridge-berlin/organization/issues/143
  * sponsoring #147 
  * speakers #152 
  * registration form #148 
  * catering #149 
  * outreach #153 
  * design/flyers #151 
  * curriculum 
* 20-21:00  shared working time 

After the status updates and checkins, we can spend an hour doing shared work time, sitting together and getting a head start on various tasks. 

Did I miss anything? Let me know! 

![doggo](https://media.giphy.com/media/mCRJDo24UvJMA/giphy.gif)

cc @DanToml @daiyi @pepper-aenn @lislis @socksy @nblumoe @codebeige @daveliepmann @saskali @Realtin @JohannaCarola

**Comment by lislis** [comment]
What about the coaches signup form? Will we use the same as last time?

**Comment by vsmart** [comment]
@lislis good question! we have an issue for that now #157 \o/
