### ISSUE TITLE
Curriculum discussion

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/organization#156]
A quick review of today's orga meeting curriculum discussion (27 July 2017):

For several months I have been gathering reports from ClojureBridge coaches and learners, both individually in Berlin and at the last two EuroClojures. I also facilitated discussion, partially for the purposes of gathering ideas related to ClojureBridge, at an Unsession on the topic of "The Beginner Experience in Clojure" at EuroClojure 2017 in Berlin. 

As I described in the meeting, I received the following reports:

   - nearly every coach and orga team member volunteered their opinion that they felt the curriculum needs work
   - many said something like, "we've tried to make changes at the edges, and failed" (--> it's basically impossible to write via consensus! ...and it's hard to decide where to start with any changes)
 - learners vary, particularly along axes like: `[totally new to all programming OR experienced in other languages]` and `[want to explore programming OR want to be shown a clear path to running something like a Rails app]`
  - orga-team said a lot of "help is wanted" and "please make changes" to curriculum
   - the [introductory slides/presentation](http://clojurebridge-berlin.org/curriculum/outline/intro.html#/) that, for example, overviews all of Clojure's data structures is overwhelming for programming novices and seen by many as boring ("not practical or hands-on enough", as one learner put it) (ClojureBridge Stockholm simply removed the slides altogether, and reports great results)
   - many coaches expressed to me that they feel the slides and intro material are *too* comprehensive—they cover too much
   - several expressed preference for a much shorter overview followed by throwing learners into a REPL
   - several prior attempts tend toward a one-page introduction (e.g. Land of Quil, or Robin & Tibor's work)
   - paraphrased quote from a coach: "they don't need stuff like `loop/recur`--just show them how to call a function, and get right to the REPL"
   - paraphrased quote from a coach: "the Berlin [curriculum] has diverged considerably from the original one, and I'm not sure a merge would really be possible at this point."
   - paraphrased quote from a coach: "the curriculum [is] too long and slow - most learners don't really get as far as playing with Quil which I think frustrated them when it came to demos"
   - some learners want a linear guide, some want a random walk
   - coaches and learners would both benefit from a collection of short examples (an excellent suggestion from Robin) 

To best address these reports, I proposed some ideas:
 - we should consider switching to a much shorter introductory curriculum
 - we should cut the introductory slides and presentation, or shorten them to a two-minute "Hi, we're going to program today!"
 - we should try to cover *fewer* things across our entire curriculum, whether we switch to a different curriculum and environment or not
 - we should consider the benefits of putting learners directly into a REPL, rather than a full-featured IDE
 - we should explore the possibility of opening up the afternoon (after students are done with an extremely brief introduction to Clojure in the morning) so that students pick what topic they pursue, from a selection of 3 to 6 options

My proposal, broadly speaking, is to put learners directly into a REPL environment with the absolute minimum of talking and pre-discussion. Then, harvest the benefit of learners achieving a quick milestone by using an extremely short introductory curriculum. Then, let learners direct their own learning by exploring their choice of topic.

**Comment by daveliepmann** [comment]
From Chris: if we use an alternative environment, make sure to test extensively in Windows!!!

**Comment by daveliepmann** [comment]
For instance, I humbly propose that we don't need a slide like this:

># [The benefits of prefix notation](http://clojurebridge-berlin.org/curriculum/outline/simple_values.html#/7)

This is not relevant to our learners. Why not replace these 17 slides with 2 or 3 that we can just gloss over, as in, "Like most modern programming languages, Clojure understands numbers, words (they're called 'Strings'), and anything else you might need." We could just not mention ratios and Booleans and keywords at all.

Nor is it necessary to throw words like "Concurrency" at a totally-new-to-programming person in the [third slide](http://clojurebridge-berlin.org/curriculum/outline/intro.html#/2).

**Comment by daveliepmann** [comment]
Maybe someone could explain the schedule in more detail, so I'm sure I understand the role of the slides?

According to the [Schedule](https://github.com/clojurebridge-berlin/organization/wiki/Schedule):
>`09:30 – 09:45` Welcome Talk
>`09:45 – 10:15` Intro to Clojure
>`10:15 – 13:00` Coding in Groups

That seems to be only one half hour of slides, followed by coding for three hours—perhaps *without* slides? Yet the [curriculum docs say the slides add up to 4+ hours](https://github.com/clojurebridge-berlin/curriculum/blob/gh-pages/TEACHING.md#outline) of teaching, arranged vaguely like:

 1. `slides`
 2. `code in groups on exercises from slides`
 3. `more slides`
 4. `more exercises from slides`
 5. `repeat`

Is this how we do things? Do we use all 6 sets of slides in Berlin?

**Comment by Realtin** [comment]
I only ever got as far as the Function slides and then we went into the creative coding part.

**Comment by daveliepmann** [comment]
@Realtin Do learners go through the slides in small groups, then? And they can decide when to give up on the slides as a team?

Which slides do the whole event (all ~50 people) go through together?

**Comment by JohannaCarola** [comment]
@daveliepmann that's what my group did during the last workshop and also what I heard from other groups. As far as I understood it the slides are not meant as a rigid tool that every group has to go through entirely but more like a pick-and-choose thing (except for some basics maybe?). We also skipped some of the more detailed slides in my group and focused on certain things that the group had issues with / was more interested in. 

If I remember correctly we did not do the Intro slides with the whole group but also in the small groups. I think we only did the orga stuff (what's the schedule for the day, code of conduct, sponsors, volunteers, etc.) together with everyone.

@Realtin @vsmart and everybody-else-who-was-there: feel free to correct me if my memory has failed me on this!

**Comment by daveliepmann** [comment]
@JohannaCarola Thanks so much for that explanation. That really helps.

I'm still curious about what is part of the `09:45 - 10:15` "Intro to Clojure" part of the schedule, but it sounds like at least most of the slides aren't used as part of a group presentation.

**Comment by daveliepmann** [comment]
Here's a list of the functions/syntax introduced in the curriculum slides, in this order. Any transcription errors are mine.

 1. `+`
 1. `max`
 1. `print-str`
 1. `;; and ;`
 1. `fill` (implicitly referenced from quil)
 1. `clojure.repl/doc`
 1. literal integers
 1. literal decimals
 1. literal ratios
 1.  `-`, `*`, `/` 
 1. literal strings
 1. literal `true`, `false`, `nil`
 1. literal keywords
 1. `def`
 1. literal vectors: `[1 2 3]`
 1. `vector`
 1. `conj`
 1. `count`
 1. `nth`
 1. `first`
 1. `rest`
 1. literal maps: `{:data "stored associatively"}`
 1. `assoc`
 1. `dissoc`
 1. `merge`
 1. `get`
 1. `keys`
 1. `vals`
 1. `update`
 1. literal nested maps: `{:outer {:inner "hi!"}}`
 1. `update-in`
 1. literal vectors of maps: `[{:type "map in a vector"} {:type "also a map in that vector"}]`
 1. `map` (unofficially, in the context of vectors of maps, so before it's really explained)
 1. keywords as functions (in `map`, so 2 new things at once)
 1. `defn`
 1. `map` (officially, with explanation)
 1. `remove`
 1. `even?`
 1. `reduce`
 1. `filter`
 1. `fn`

Is this the material we want to introduce? Is this the order we want to introduce it in? Is there anything we should add (Quil-specific stuff?)? Is there anything we want to remove (**ahem** *dissoc, update, decimals, ratios, update-in* **cough**)

**Comment by daveliepmann** [comment]
Some notes from a face-to-face discussion about what to cover in slides: 

 - coaches as facilitators not teachers
 - coaches probably won't know the answer to lots of your questions!
 - what to learn from your coaches: not what they *know* but how they *approach the problem*

**Comment by daveliepmann** [comment]
Some explorations in this direction are reviewable here: https://github.com/clojurebridge-berlin/curriculum/compare/gh-pages...clojurebridge-berlin:simplify-reduce-remove

**Comment by daveliepmann** [comment]
Re: `09:45 - 10:15`, from face-to-face meeting with @vsmart, this was actually a Berlin-specific presentation (given in one year by Jelle and Bettina in another, perhaps?) about "10 cool things to do with Clojure". Motivational, to bridge "welcome" and the small-group work.

**Comment by vsmart** [comment]
@daveliepmann Here is a link to the `9:30 - 9:45` intro talk: https://docs.google.com/presentation/d/1zzsYHQ0YL0YBeS-Q6dcIbk0lJnj6WjXZxmHbjbxlIV0/edit?usp=sharing

**Comment by daveliepmann** [comment]
Folks interested in seeing some of my thoughts in action can browse the [`simplify-reduce-remove` branch](https://github.com/clojurebridge-berlin/curriculum/tree/simplify-reduce-remove). I changed a lot of the slides while still under the impression that they were given as a presentation, so I may want to roll back some (but not all) of those changes. 

If you [compare my branch to `gh-pages` branch](https://github.com/clojurebridge-berlin/curriculum/compare/gh-pages...clojurebridge-berlin:simplify-reduce-remove) you'll see that I focused on the following: 

 - pointing all links to clojurebridge-berlin, not the mothership
 - updated gems (to run locally)
 - removed an enormous amount of deprecated files and content that we don't use in Berlin, simplifying the README and Teacher's Guide
 - renamed all slides so filenames numbered
 - rephrased and condensed much of the slides to avoid an "academic" or "grammar book" feel

**Comment by vsmart** [comment]
@daveliepmann Can we close this issue, or would you like to further continue discussion here past the context of this workshop?

**Comment by daveliepmann** [comment]
Close
