### ISSUE TITLE
Open coach registration form 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#157]
* copy old coach registration form 
* update coach form to include question for child care https://github.com/clojurebridge-berlin/organization/issues/138
* set up "save responses in google spreadsheet"
* setup coach form auto response -- email template is here https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Coach-Signup-Confirmation-Email
* test that sign up and response is working properly
* set form to public 
* link new form in https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/54

Assigning to @lislis who said she could pick this one up!

**Comment by lislis** [comment]
- copied form
- added/ removed fields according to #138 
- setup auto response
- collect answers in spreadsheet
- set form to accept responses

**Comment by lislis** [comment]
Closing this, all we need to do is merge the PR
