### ISSUE TITLE
Coaches Outreach 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#158]
We want to reach out to our previous coaches and tap into new sources of coaches! As always, we also try to have more women + nonbinary coaches as well. 

When you outreach to these groups, make sure to include a link to the coach Info page: http://clojurebridge-berlin.org/coach

## Our channels 

* [x] tweet out from our Twitter account
* [x] announce to our mailing list

## Others

- [x] women who code berlin meetup announcement
- [x] clojure dojo meetup 
- [ ] email to lambda-ladies mailing list 
- [x] women in tech slack 

A few of the points of contact from [Attendee Outreach](https://github.com/clojurebridge-berlin/organization/issues/153) can be copied too!

**Comment by daiyi** [comment]
I made an announcement at the Clojure Dojo meetup wednesday 9 August!

**Comment by JohannaCarola** [comment]
I mentioned this in the slack channel already, but just for the record:
I posted an announcement a few days ago in a FB group for Berlin based game developers. 
A few people seemed interested so: fingers crossed! :)

**Comment by vsmart** [comment]
The next WomenWhoCode meetup is next Tuesday (Aug 22). @daiyi mentioned they will be there and could make an announcement: https://www.meetup.com/Women-Who-Code-Berlin-Germany/events/241952251/

**Comment by vsmart** [comment]
Looks like this [tweet](https://twitter.com/franschm/status/898999539083825152) got some traction. 🎉 

@daiyi Did you end up attending the WWC meetup? :)

**Comment by daiyi** [comment]
Yes! Got some enthusiasm for attendees, but no one asked me any question about coaching.

**Comment by vsmart** [comment]
@daiyi awesome, thanks for attending 💯

**Comment by vsmart** [comment]
We have 29 signups for coaches, probably more than we need. Thanks everyone for helping with this issue, especially @daiyi for announcing at ClojureDojo and WomenWhoCode! 
Closing this.
