### ISSUE TITLE
Venue for Coaches Training & Installfest

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#159]
We still need a venue for Coaches Training & Installfest! 

## Coaches Training  -- 28 September 2017

* When: 28/9,  ~7pm to 9pm 
* Who: ~30 people, coaches
* Where: **Wunderlist**

Ideas: 

* [x] Wooga -- @vsmart to check 
* [ ] **Wunderlist** -- @vsmart to check
* [ ] Contentful

## Installfest -- 6 October 2017

* When 6/10, ~6pm to 9pm
* Who: ~50 people, attendees + volunteers
* Where: **Wunderlist**

Ideas: 
* [x] Wooga is :no_entry_sign: for this date
* [ ] **Wunderlist** - @vsmart to check
* [ ] ?

**Comment by vsmart** [comment]
I messaged Wooga again to see if they can host us for the coaches training. 
I have a "probably 95% yes" verbal yes from Wunderlist for Installfest.

**Comment by daveliepmann** [comment]
That's fantastic, thanks @vsmart

**Comment by vsmart** [comment]
From wooga: `On September 28 we already have another event in the office, so unfortunately we can't host the coaches training.`

I guess we need to check in with wunderlist again.

**Comment by vsmart** [comment]
We got final confirmation that Wunderlist works for both dates! Yay! Closing this.
