### ISSUE TITLE
Include sign up form link for learners like for coaches

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#16]
Solingen has a good list of questions we can use as a template: http://www.clojurebridge.org/events/2015-06-12-solingen-germany

**Comment by Malwine** [comment]
:+1:

**Comment by thatbettina** [comment]
Closing because duplicate issue https://github.com/clojurebridge-berlin/organization/issues/14 exists with more info.

**Comment by Malwine** [comment]
:+1:
