### ISSUE TITLE
Update morning presentation

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/organization#160]
[Slides for the morning "Welcome talk" presentation](https://docs.google.com/presentation/d/1GVumSytqdonSdabtSrbeY6F2jXS-TNUPlGNgxSirEro) have deprecated content. We must update before the event. Most info does not yet exist. I have put TODO in places where we must update.

- [x] *Sponsors* (list of logos)
- [ ] Lightning *Talks* list
- [ ] "10 cool things you can do in Clojure/Script" talk — @vsmart Do we have slides for this? Are we giving it again? Who will do so?
- [ ] Wifi password and other *Practical Stuff*
- [ ] *Groups* map
- [x] *After Party* location info

**Comment by vsmart** [comment]
@vsmart to make groups map

**Comment by lislis** [comment]
Updated the slides with the info that we have. Still missing is the WIFI, the 10 cool things (@ping @jellea ) and one of the lightning talks. (plus the groups map)
