### ISSUE TITLE
Add workshop date to clojurebridge.org

### ISSUE THREAD

**Issue by daiyi** [clojurebridge-berlin/organization#162]
We should add the upcoming workshop to the [mothership](http://clojurebridge.org) via a PR: https://github.com/ClojureBridge/Workshops

I can totes do this if no one else is already taking care of it!

**Comment by vsmart** [comment]
Thanks @daiyi ! 💯  
We add the workshops by opening issues. You can see the issue from the previous Berlin workshop here: https://github.com/ClojureBridge/Workshops/issues/44 

It should be mostly the same content :)

**Comment by vsmart** [comment]
You can use this template to do open the issue: https://github.com/clojurebridge-berlin/organization/wiki/Text-for-Event-on-ClojureBridge.org

**Comment by daiyi** [comment]
Issue opened here: https://github.com/ClojureBridge/Workshops/issues/63

**Comment by vsmart** [comment]
Thanks @daiyi 🎉 ❤️

**Comment by daiyi** [comment]
no problem <3
