### ISSUE TITLE
Clojurebridge-Berlin.org content and design audit & update

### ISSUE THREAD

**Issue by daiyi** [clojurebridge-berlin/organization#164]
I'm doing a content & design pass for the website http://clojurebridge-berlin.org

See the issue on the website repo for more details: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/67

**Comment by daveliepmann** [comment]
Do you have a public branch you'll be working on? I only see master at the moment.

**Comment by daiyi** [comment]
I'm working on redesign first, because I feel like the main frustrations I have at the moment are:

- important links (e.g. signup, sponsoring) are not easy to find at a glance
- information ordering is non-intuitive

And while I'm at it, I'd like to rewrite the content a bit to show the spirit of the Berlin Clojure community (which is the nicest thing!!)

Made this issue in the website repo: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/67

**Comment by lislis** [comment]
@daiyi I was just wondering
> better bilingual support with proper fallback when javascript is disabled

The current website doesn't use JS at all and content is bilingual (could use language attributes, source code structure and so forth though...). 

What are you thinking about changing?

**Comment by daiyi** [comment]
I like how most of the page is laid out with the two languages! I think there should be a set of navigation links to the different parts of the webpage though, because it is a very long webpage. Thinking about a bilingual navigation menu, it would be pretty unwieldy with both words side by side. I think the current bilingual buttons are pretty unwieldy (or maybe it's just the layout/colours?) So I figured I'd throw in a simple toggle to switch between EN/DE where we use language attributes and it uses "display:hidden" to switch between the languages. We could style them so if JS is disabled, it would show both, and they'd sit side by side as it already does. 

Another big motivation for me is that I want to reword some of the website (at least the English parts, I have no idea how it sounds in German) to talk more about how ClojureBridge is about community as much as it is about coding! And remove the old references to deprecated curriculum stuff.

**Comment by lislis** [comment]
Something I was wondering about is if we should split the index into two pages anyway?
We could make one `<html lang="en">`  `de` the other which search engines will appreciate more.

This way we could work with regular links and would not need JavaScript.

Hierarchy-wise we could move all pages that have translations (the startpage and the study group page) to either `clojurebridge-berlin.org/en/` or `/de/`. The english only pages could stay where they are, eg `.org/sponsor-us`.

This would probably be more work though. What do you think @daiyi ?

**Comment by daveliepmann** [comment]
@lislis I like that approach, but I worry about content/wording updates being difficult to manage. They might diverge. But I still like it.

**Comment by lislis** [comment]
Good point. We could add a localization plugin https://github.com/prometheus-ev/jekyll-localization 
But this would not work with 'just' deploying to gh-pages. We would then need to setup Travis to build and deploy. 
I guess it's too much work :D never mind then :)

**Comment by daiyi** [comment]
That sounds like the proper solution \o/ 

Although for now, with my caveperson tools and brave command of vanila javascript and css, I threw together something that can accommodate the existing structure of the pages and introduce incremental change. (Also I started doing it before I read your comments, oooops)

demo: http://www.daiyi.co/clojurebridge-berlin.github.io

It defaults to English (I inferred this is an English-first website because the English translation appeared first when reading left-to-right, and also later on in the page the German translations are italicised as if whispered. Let me know if we should do German-first!) if there's no javascript or language preferences set in the browser. I tested it with javascript blockers and it does fine.

You can set the language with url params to test all the settings:
http://www.daiyi.co/clojurebridge-berlin.github.io/?lang=en
http://www.daiyi.co/clojurebridge-berlin.github.io/?lang=de

Both languages at the same time:
http://www.daiyi.co/clojurebridge-berlin.github.io/?lang=all
(Should look almost identical to the existing website)

I was gonna make a button at the top too, so people can choose their language at will, but I'll hold off until we decide it's a good idea, because putting a menu will be a bit of work that I don't want to do if this all doesn't go through.

lemme know what you think \o/

**Comment by lislis** [comment]
@daiyi that's pretty dope! Let's roll with that! Thanks for putting all this work into it!

**Comment by lislis** [comment]
Another thing I forgot to mention
> to talk more about how ClojureBridge is about community as much as it is about coding

While this is true and I wholeheartedly agree, most attendees want to participate because they want to learn how to code. 
People outside of tech don't know how tech/ open source communities work. It's a strange concepts when you see it with the eyes of an outsider working in a completely different field.

I guess what I want to say that: yes community is a big (biggest?) part but it's not what attracts people in the first place. Just as a reminder when writing copy and stuff

**Comment by daveliepmann** [comment]
![join us!](https://media.giphy.com/media/HX4QGHMYe2fsI/giphy.gif)

The single language versions look nice. I await a language-toggle button.

**Comment by daiyi** [comment]
I'm closing this to make individual issues! gonna make @daveliepmann proud (:
