### ISSUE TITLE
Catering - Coaches and Installfest 

### ISSUE THREAD

**Issue by saskali** [clojurebridge-berlin/organization#165]
Potential caterers

strike through == out
bold == accepted
box ticked == caterer has been contacted

- [ ] ~~noTiers~~
- [ ] ~~Playing with Eels~~
- [x] **Suppen Cult (Julia)**
- [ ] ~~Sfizy Veg~~
- [ ] ~~Knofi~~
- [ ] ~~Miriam Lappenberg~~
- [ ] ~~Bleibtreu Catering~~

**Comment by vsmart** [comment]
Thanks @saskali! I think Suppenkult would be a great option again. 
See https://github.com/clojurebridge-berlin/organization/issues/107 for the ticket from last time. Here is how many portions we ordered last time: 

* Coaches Training | September 28 | ~25 portions

* Installfest | October 6 |  ~55 portions

**Comment by Realtin** [comment]
I send the email to suppen cult and with ~ those numbers. (Send from the ClojureBridge account)

**Comment by Realtin** [comment]
Suppen Cult replied that they would be available for Installfest & Coaches training and will send an offer in the next days! (will be send to our clojurebridge gmail account)

I'll be unavailable for the next two weeks, @saskali can you monitor the email conversation in that time?

**Comment by saskali** [comment]
perfect, thanks Julia! I'll keep an eye on it

**Comment by saskali** [comment]
I called Suppenkult today and confirmed their offer for the coaches training and install fest. We should call them two weeks ahead of time to choose which soups we want and what dietary restrictions people have!

**Comment by vsmart** [comment]
Awesome, thanks @saskali ❤️ ❤️

**Comment by plexus** [comment]
I will contact Cognitect to let them know this is what they're paying for. The invoices will need to have Cognitect's address as billing address.

Do we know how much this will be in total? It seems (from today's email from Suppencult) that the price for the coaches training will be € 218,60 for 25 portions. If the installfest costs `(* (/ 218.60 25) 55)` for 55 portions then this will cost € 699,50 euro in total, while Cognitect only sponsors for 500...

**Comment by lislis** [comment]
If we get two separate invoices we can forward one to Cognitect and cover the other with Nextjournal moneys

**Comment by vsmart** [comment]
![screenshot from 2017-10-10 20-30-17](https://user-images.githubusercontent.com/2796920/31403611-daecb132-adf9-11e7-9f24-975c246b141a.png)

As always, Suppenkult soups were delicious :yum: 
Thanks @saskali and @Realtin for organising this!!
Let's track any remaining payment questions in #176
