### ISSUE TITLE
Orga Meeting 3 - August 24

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#168]
Catch up on the last agenda: https://github.com/clojurebridge-berlin/organization/issues/155

## When & Where

Achtung: *new location*

* Thursday August 24 - 7-9pm
* Where: Travis CI, Rigaer Str 8, 3rd floor (Ring at "Tessa")
* snacks are welcome :sparkles: 

## Agenda for Thursday

* 19:00 arrivals and snack
* 19:15 status checkins:
  * sponsoring #147 
  * speakers #152 
  * catering #149 
  * outreach & signups checkin #153 
  * curriculum #156 
  * tshirts #163 
  * coaches training #169 
  
* Afterwards: (optional)  shared working time 

After the status updates and checkins, we can spend some time coworking, sitting together and getting a head start on various tasks. 

Did I miss anything? Let me know! 

![cats](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)

cc @DanToml @daiyi @pepper-aenn @lislis @socksy @nblumoe @codebeige @daveliepmann @saskali @Realtin @JohannaCarola

**Comment by lislis** [comment]
We're at Travis this time and since we never have any snacks and drinks in the office (except coffee/tea) let me know if I should buy some stuffs or bring it yourself 💃 
Also I will try and get our new projector to work!

**Comment by daiyi** [comment]
Let's take a team photo for https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/57!

**Comment by socksy** [comment]
Notes:
* Sponsors:
  - we have,
   * circle => lunch catering (most likely invoice/receipt needed, ping @DanToml)
   * mapbox => Gold (500€)
   * cognitect => Gold (500€)
   * zimpler => T-Shirts (~1500€)
   * nextjournal
     - They want to be platinum sponsors
     - They asked for a Rechnung
     - [] *Next step:* See if they're ok with receipt (if not, find something to bill them directly?)
    - @socksy and @saskali will be on it
* Speakers
  - @DanToml's domain, she's on holiday
  - one signup for speaker's
  - @Saskali could speak, but is hesitant
  - @pepper-aenn will talk to a friend
  - study group advert talk? Last time was @Realtin and @ariaru
* Catering
  - Playing with Eels never got back to @pepper-aenn
  - NoTiers is going on holiday for a week and are hard to contact, but still proceeding for now
    * normally she doesn't cater any more, just for special events, and she regards this one as one of those
  - SuppenKult for Installfest and Coaches training, so now to proceed on requests
    * We will need to specify which soups... which ones are vegan and what will our dietary requirements be?
 - Breakfast???
   * Bagels?
     - there might be bagels in P'Berg
     - P'Berg is a legit word
   * @vsmart??
     - LPG Biomarkt???
     - ?
     - what is life
* Outreach
  - Going well
    * Currently we have 81 signups(!)
  - Coaches...
    * Currently we have 22 signups
    * @daiyi announced at last ClojureMeetup and we got a couple new signups from that
    * @lislis says that @robsteranium for sure will coach
    * @JohannaCarola asked at the Berlin Game Jam and got a few leads
    * Dave is asking the Clojurians Slack #berlin channel
      - *Next items:* we all must react to Dave's post
    * where's @martinklepsch?
* Curriculum
  - Dave
    * :+1:
  - There's a few teams that want to do Maria curriculum, others will stay on slide one
    * What about install fest? If people use Maria they won't be able to continue at home
    * Could show people the website *after* the Nightcode install at the Installfest (check that it works)
    * Will announce at the Coaches training, people should approach @daveliepmann if they want to learn
* Boat
  - Tibor's on a boat
* T-Shirts
  - @codebeige is sorting it out for 100 T-Shirts
  - Zimpler are waiting on an invoice
* Coaches training
  - We need a venue...
  - Maybe Wunderlist? @vsmart will know the status there
  - Maybe Travis, depending on size
  - What is Coaches Care? asked by @saskali
    * Emails
    * Not the Coaches Training
    * Dealing with the whole floating coaches shenanigans
  - @lislis does not like being alone in the coaches training. Wants volunteers to help
* Do American movies rip-off Japanese originals?
  - @JohannaCarola says yes
  - @lislis says no

**Comment by daveliepmann** [comment]
Addendum to curriculum portion: I merged [the PR we talked about](https://github.com/clojurebridge-berlin/curriculum/pull/37), which brought some cosmetic changes to the [curriculum slides](clojurebridge-berlin.org/curriculum/) and in general cleaned up the repository.

**Comment by vsmart** [comment]
Re installfest / coaches training venue status -- I'm still in touch w Wunderlist people about this. I've just pinged them again to get a final answer...

**Comment by daiyi** [comment]
Is that the final list of sponsors? I'll [make an update](https://github.com/ClojureBridge/Workshops/issues/63) to the overarching ClojureBridge site with Nextjournal and Cognitect if this is the case! 

(also should probably update https://github.com/clojurebridge-berlin/organization/issues/171)

**Comment by vsmart** [comment]
@daiyi i updated the final list in #171 -- would be greatd if you could update the ClojureBridge site! We also need to update them on our website (https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/82)
