### ISSUE TITLE
Coaches Training [overview]

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#169]
We have scheduled the coaches training for September 28. 

This is what needs to be done to make this happen ✨ 

* [x] Pick a venue: #159 
* [x] Organise catering: #165 
* [x] Bring coaches training slides up to date https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/68
* [x] Find one or two volunteers to lead the training:  ➡️ ** @JohannaCarola  + @socksy  ** ⬅️ 
* [x] Send [email reminder](https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Coaches-Training-Reminder) to registered coaches one week out - *September 21* 
* [x] Hold coaches training
* [x] Send out Information for the coaches https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Informations-for-the-Coaches

**Comment by vsmart** [comment]
Update: got the dates wrong, now corrected in OP. Thanks @JohannaCarola for better 👀!

**Comment by lislis** [comment]
![I volunteer](https://media.giphy.com/media/EfHmlClbuNAGc/giphy.gif)

**Comment by lislis** [comment]
I realized I will not be in the country on the coaches training :/ (calendars, how do they even??)
so somebody needs to take over

**Comment by JohannaCarola** [comment]
I can help with the coaches training! As I haven't done any clojure stuff since the last workshop I could only do the "how to teach" part and would need support from someone else for the "what to teach" part :)

**Comment by vsmart** [comment]
Email reminder sent!

**Comment by vsmart** [comment]
@JohannaCarola and @socksy ran a great training, @saskali & @Realtin  coordinated delicious soups.

Next actions -- 

* [x] @vsmart to cross-check attendance list with google form
* [x] send out coaches info email for everyone who's confirmed https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Informations-for-the-Coaches

**Comment by vsmart** [comment]
Updated attendance list in the google sheet and sent out the important coaches info email.

**Comment by vsmart** [comment]
Our coaches were trained \o/ Thanks esp to @JohannaCarola and @socksy for running this. :sparkling_heart:
