### ISSUE TITLE
Notebooks 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#170]
We have a stack of notebooks sitting at Wunderlist HQ with our name on them. 

Someone (happy to take this - @vsmart) needs to check if they're still there, how many we have left, and then get them to Wooga in time before the workshop. 

Opening this issue to keep track of that.

**Comment by JohannaCarola** [comment]
@vsmart have you had a chance to check with Wunderlist about the notebooks? 
I guess we could pick them up after the Coaches meeting or during the Installfest? Supposing they're still there and we can have them :)

**Comment by plexus** [comment]
There might be some other things still lying around at Wunderlist. First thing that comes to mind are the organizer lanyards. Possibly also the installfest thumb drives, although those might also be lying at my place. I can check tomorrow. I think I also still have a big stack of white sticky labels for nametags.

**Comment by vsmart** [comment]
Ok, I will stop by Wunderlist next week and see what's there. 
Yes, we can ship the notebooks over before/during/after the coaches training. I'll try to get an overview of how many there are and if we can carry them :thinking:

**Comment by vsmart** [comment]
I stopped by at Wunderlist today (and got a free lunch out of it - they happened to have team lunch 😎 ) . There are 120 notebooks - still enough for 2 workshops. 🙇‍♀️  We can take half of them over to Wooga next week. We can leave the rest of the stuff there. 
I couldn't find the lanyards and other stuff. Will try to get in touch with @Malwine  - maybe she knows where they are.

**Comment by plexus** [comment]
I have the thumb drives and one organizer lanyard at home (forgot to give it back last time). I'll bring them to the coaches training.

**Comment by vsmart** [comment]
Notebooks were delivered to our attendees and coaches! :books: :sparkles: 
There's a remaining stack of 60 notebooks at Microsoft.
