### ISSUE TITLE
Catering - Breakfast 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#173]
Previous issues: #106 

This is what we had last time; 

```
35 chocolate muffins
35 carrot cake muffins
15 Brezels
15 white bread rolls
15 whole wheat bread roll
selection of vegan spreads
selection of fruits (bananas + apples)
```

I would lean towards getting this same recipe ^ again. 
If we do, this needs to be done: 

* [x] [one week out] order muffins, brezels, rolls from LPG bakery @ Senefelder Platz
* [ ] [day off] pick up everything from bakery

We could also try something new if someone has capacity to research this, I saw a mention of bagels fly around? :)

**Comment by pepper-aenn** [comment]
somebody threw in Schlomos last time. They offer 4 different vegan bagels. (http://www.schlomos.com/) 

I can ask them for an offer. I personally would prefer bagels over muffins :) 

UPDATE:

their offer:

**Bagels**

all of the varieties of bagels (plain, everything, sesame, poppy, rye, onion, and cinnamon sugar) are vegan. 
- 12 for 15€ --> so for 72 bagels with nothing else 90€. 
- Spreads can be be bought additionally: fruit jams, vegan butter, peanut butter, guacamole, and hummus. (72 bagels with spreads would be 210€)

**Full sandwiches** 

- package of 12 vegan mixed sandwiches for 77€ (all cut in half)
(72 of them would be 462€)
"Our available sides that are vegan would be the vegetable salad, veggie sticks and hummus, and our banana muffins."

**Comment by vsmart** [comment]
Thanks @pepper-aenn \o/ ✨  Let's discuss which option is best tonight!

**Comment by vsmart** [comment]
:+1: Let's order 60 full sandwich bagels. cc @pepper-aenn  
Coffee is provided by wooga. 
@pepper-aenn will enquire about delivery

Billing address is Travis Foudnation

**Comment by pepper-aenn** [comment]
60 Full Sandwiches cost 385 €, the caterer said we even might get a free delivery!
I'm confirming now.

What time should the bagels be delivered?

**Comment by vsmart** [comment]
Awesome \o/ That's cheaper than we thought, right? 
8:45am sounds good - delivery to Wooga 
thanks @pepper-aenn! 🎉

**Comment by pepper-aenn** [comment]
got a confirmation- breakfast will be delivered at 8:45, I will receive the invoice afterwards and will forward it aswell to @plexus  .

**Comment by vsmart** [comment]
The breakfast bagels were great \o/ Thanks @pepper-aenn for organising this. 
let's track any remaining payment questions in #176.
