### ISSUE TITLE
Catering - afternoon treats

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#174]
Previous issues #109 

We've previously ordered beautiful vegan custom cupcakes with our logo on them. 
Details in the issue linked above. 

Should we get those again? We could also skip the cupcakes and only get donuts from Brammibals. What do you think?

**Comment by pepper-aenn** [comment]
I think one of both is enough. My two cents though.

**Comment by Realtin** [comment]
I also think one is enough, we are also getting desserts with lunch.

I vote donuts :3

**Comment by vsmart** [comment]
@pepper-aenn will order 75 donuts. 
We will ask about delivery options.

**Comment by pepper-aenn** [comment]
[seems like they raised their prices]

donuts would be 2 €/ p.piece + tax
delivery would be an additional 20 € (seems fine to me)

so if i counted right it would be 198,50 € in total. 

@vsmart @Realtin last years cost on donuts was 80 € , cupcakes even more- so i guess im giving it a go?

**Comment by vsmart** [comment]
yea we spent a lot of money on cupcakes last year :D 

200eur sounds good to me, esp if it includes delivery. 
I'd say deliver for 14:30h?

**Comment by pepper-aenn** [comment]
sure, confirming now then. :)

![11247207_368595769997736_1123796691_n](https://user-images.githubusercontent.com/29863133/30916353-7e67ad14-a399-11e7-95b5-fd314cd14a7e.gif)

**Comment by pepper-aenn** [comment]
@plexus I've got an invoice already. we discussed in the last meeting that will go to travis foundation. I forwarded the email to the clojurebrigde account, can you then take care of it? please keep me updated,
thanks!

**Comment by plexus** [comment]
yes @pepper-aenn, just send it there. Thanks!

**Comment by vsmart** [comment]
Donuts were delicious! :yum: Thanks @pepper-aenn for ordering them, and @plexus for following through with payment.
