### ISSUE TITLE
Wrap up finances for October 2017

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#176]
Overview of our finance situation for October. 

## Company sponsorships

| Company        | Amount           | Using for  |  Contact | Next steps | Wrapped up?  :no_good_woman: or :white_check_mark: 
| ------------- |-------------| -----|----|----|---|
| Nextjournal | 1000 |  travel support? childcare?  | @saskali @daiyi  | @plexus will forward receipt from Travis | ✅   |
| Zimpler | 1500 | Tshirts | @lislis @codebeige  |   | ✅ |
| circleCI | 1000 |  lunch catering  | @DanToml |  | ✅  |
| Mapbox | 500 |  child care | @vsmart | | ✅ |
| cognitect | 500  | Suppenkult (install fest+ coaches training) | @plexus | Invoice has gone to Cognitect, assuming this is ok | ✅ |

## Other payments 

| Expense | Amount | Contact | Next steps | Wrapped up? 🙅 or ✅  |
|---|---|---|---|---|
| Posters / Flyers | 139.38 | @codebeige |  | ✅ |
| Nametags order | ? | @vsmart | @plexus will pay back @vsmart  | ✅  |
| donuts | 184.30 | @pepper-aenn |  | ✅ |
| bagels | ? | @pepper-aenn | ?  | ✅ |

I added some next steps for the contacts. 
Let me know if I forgot anything / anyone, and let's keep this issue updated.

**Comment by vsmart** [comment]
We got an offer from the child care for 416 Eur. This seems like a good fit for Mapbox. Updating the table to reflect this.

**Comment by vsmart** [comment]
@plexus Could you update the table above? E.g. Cognitect is wrapped up as far as I know. 

@pepper-aenn @DanToml Any next steps for the circle payment? 

@plexus @saskali Is anything else needed for Nextjournal?

**Comment by saskali** [comment]
I got a printed copy of the transfer made by Nextojournal that I need to hand to @plexus !

**Comment by plexus** [comment]
I bundled the stuff up that I had and forwarded it to Travis

- For Nextjournal I should get a receipt back which I'll forward to Nextjournal
- Tibor already paid for the flyers/posters, I reimbursed him and will get the money back from Travis
- I paid for the donuts, I'll get the money back from Travis
- For the small expenses (nametags, lanyards) I'll reimburse @vsmart as soon as I get her bank details

The only open question are the bagels. I've pinged @pepper-aenn about them.

**Comment by vsmart** [comment]
Update: 
* @pepper-aenn got us the bagel receipt \o/, and  @plexus paid the bagels 💯 Thank you both! 
* we contacted Travis again to get the nextjournal receipt

**Comment by vsmart** [comment]
All finances are wrapped up, we forwarded the final receipts to Nextjournal. Closing 🎈
