### ISSUE TITLE
Workshop Day 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#178]
## MCs

* @lislis 
* @pepper-aenn 

## Attendee care person

@JohannaCarola 

## Coaches' care person

@daiyi 

## Child care person

@vsmart 

## Speaker contact 

@DanToml or @lislis 

## Catering

@pepper-aenn 

## Phone person 

@vsmart 

## Registration on Friday (2 people) 
 
@zucker + @saskali 

## Registration on Saturday (2 people) 

@zucker + @saskali 

## Person who leads people to Volksbar

?

## Kitchen duty (2 people) 

@socksy + ?

## Extra volunteers (signing in people, etc) 

@JohannaCarola  @codebeige @socksy @daiyi (willing to arrive arbitrarily early for prep)

---

# Jobs on Day Of

(tag yourselves)

### some time before the workshop 

* [ ] get the key to the fuse box 
* [x] get the hausmeister's number 
* [x] get some spare key cards 
* [x] extra verlaengerungskabel + chargers?
* [ ] prepare badges: visualize role on the badge: coach, attendee, volunteer
* [x] acquire badges/name tag stickers
* [x] acquire markers and pens for study group sheet and name tag creation
* [x] decide on quiet room - make sure it's easily/discreetly accessible
* [ ] print list of venue emergency contacts
* [x] print sign for quiet room saying `Quiet room | Ruhe Raum`
* [x] print sign for toilets incl. all gender bathroom sign
* [x] print check-in lists for coaches/attendees
* [x] print study group signup sheet, one for learners and one for coaches
* [ ] prepare a list of who is inside the building for emergency (may be a column in the above)
* [x] print code of conduct + guest policy
* [x] print out [responding to CoC guidelines](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports)
* [x] print out (...and write) a form for project group sign up

### Morning of Workshop

* [ ] Set out breakfast 
* [ ] turn on coffee machine 
* [ ] prepare a name tag table 
* [ ] put up all-gender bathroom signs and signs pointing out the direction of toilets
* [ ] put up signs leading from entrance to auditorium
* [ ] put study group signup sheet next to name tags with pens
* [ ] have someone standing downstairs & upstairs 
* [ ] check people in (on a list)

### Jobs
~~Moved to https://docs.google.com/spreadsheets/d/1NqQPMjuEyXB0sqELGk0Dv54atP8tmih0rvqoyRIgvB0/edit#gid=0 ( @daiyi can see this now!)
made a new tab for 2017 workshop (and kept 2016 for reference)~~

Added all missing jobs to the top.

**Comment by daiyi** [comment]
What is the day-of schedule for the orga? (when is the earliest I can arrive to begin putting up signs and such?)

**Comment by saskali** [comment]
I'd be up for doing registration on both days if still needed!

**Comment by vsmart** [comment]
Thanks @saskali ! I put your name down. :+1:

**Comment by vsmart** [comment]
A bunch of items on the workshop day to-do list are printing documents. I"ll do that today.
