### ISSUE TITLE
Afterparty

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#179]
To be held at Volksbar 

@lislis to confirm.

**Comment by vsmart** [comment]
@lislis 👋 Could you give Volksbar a call?

**Comment by lislis** [comment]
Reservation for 18:00 at Volksbar under 'Lisa'

**Comment by vsmart** [comment]
The afterparty was had, and beers were had too. :beers: Thanks @lislis for comms with Volksbar :tada:
