### ISSUE TITLE
Design Tattoos

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#18]
We want some cool temporary tattoos for the event :balloon:

**Comment by nicsnet** [comment]
I think we should base our tattoo design on the official ClojureBridge sticker design.

![clojurebridge-3300](https://cloud.githubusercontent.com/assets/1889716/7160376/f68db44c-e388-11e4-8e62-ed2c7f4bf8ac.png)

Or should we come up with our own designs? Also what kind colour palette should we base the design on?  Do we still want to go for metallic ones?

**Comment by thatbettina** [comment]
I like the CB logo + Alexander tower. I like black and silver but am open to all ideas.

**Comment by Malwine** [comment]
The logo is nice but think if people will really put it on their skin. It must be at least a bit funny.
Maybe we can get some inspiration here:
http://de.dawanda.com/shop/tattootattaa

Maybe like this:
http://de.dawanda.com/product/51321718-Temporary-Tattoo---burger
But instead of the burger the Clojure Bridge logo? and "I love ~~you~~ Clojure "

**Comment by nicsnet** [comment]
That would definitely be more fun! In addition I can also get just generic ones at a wholesale price, if we like any of them. Not any interesting designs, but I can get at a good price. Around 0.80 - 1.50 euros per tattoo sheet.

![img_4302](https://cloud.githubusercontent.com/assets/1889716/7185930/6714d1e0-e466-11e4-8161-09cd21ef0f28.JPG)
![img_4289](https://cloud.githubusercontent.com/assets/1889716/7185948/8fc48c84-e466-11e4-9415-18474ec2868e.JPG)
![img_4286](https://cloud.githubusercontent.com/assets/1889716/7185976/bd175ec8-e466-11e4-8961-cdbf722d29c7.JPG)

**Comment by thatbettina** [comment]
Hi @nicsnet -- So I just heard back from Soundcloud! They will sponsor us for up to 400 euros! Can you work with that budget? They would like to be invoiced directly. I will forward you the email about that.

**Comment by thatbettina** [comment]
No tattoos for this workshop...
