### ISSUE TITLE
Order new lanyards, name tags, stickers

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#184]
I ordered these on amazon: 

* 20 orange lanyards for orga  https://www.amazon.de/SBS-Schl%C3%BCsselband-Orange-Lanyard-Trageband/dp/B014FEJDEK/ref=sr_1_2?ie=UTF8&qid=1506360947&sr=8-2&keywords=orange+lanyards
* 50 black lanyards for coaches https://www.amazon.de/Lanyard-Badge-Holder-50-St%C3%BCck-schwarz/dp/B01FZ9OGQE/ref=sr_1_2_sspa?s=officeproduct&ie=UTF8&qid=1506361158&sr=1-2-spons&keywords=lanyard&psc=1
* 250 nametags https://www.amazon.de/Herma-4412-Namensetiketten-Namensaufkleber-Textil-Namensschilder/dp/B0076XER4O/ref=sr_1_3?s=officeproduct&ie=UTF8&qid=1506361278&sr=1-3&keywords=namensschilder+kleben
* 50 ausweishuellen https://www.amazon.de/LEORX-Ausweish%C3%BClle-Ausweishalter-wasserdichte-ID-Card-Inhaber/dp/B016ULH76W/ref=sr_1_1?s=officeproduct&ie=UTF8&qid=1506361562&sr=1-1&keywords=ausweishuellen
* stickers for photo yes/no - 416 red, 416 green
 https://www.amazon.de/Avery-Zweckform-3012-Markierungspunkte-St%C3%BCck/dp/B000122SC0/ref=sr_1_3?s=motorcycles&ie=UTF8&qid=1506361374&sr=8-3&keywords=sticker+punkte
https://www.amazon.de/Avery-Zweckform-Markierungspunkte-Klebepunkte-Durchmesser/dp/B0013DEJ7S/ref=sr_1_7?s=motorcycles&ie=UTF8&qid=1506361374&sr=8-7&keywords=sticker+punkte

Total sum: 70,13 EUR

**Comment by lislis** [comment]
Did we have orange stickers for 'please ask' or was that a conference?

**Comment by vsmart** [comment]
oh yea, we did. I forgot about those. Would you like to have the orange stickers again?

**Comment by lislis** [comment]
I can't remember if people actually used them? But I think it's a nice option?
