### ISSUE TITLE
[psa] on safety, CoC, guest policy

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#186]
Hi orga-team, 

it's important that everyone who wears an orange orga lanyard at the event is aware of our CoC violation process. 

## knowing what's up - Code of Conduct 

It's paramount that you're familiar with our Coc. Please review it here: http://berlincodeofconduct.org/

Next please familiarize yourselves with this guide from geekfeminism: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports 

There are a few processes we will have in place: 

## name badges & lanyards 

All orga people and coaches wear lanyards visibly at all times, attendees are heavily encouraged to wear a nametag. This is one way we ensure that attendees can quickly find an orga team member if they need help. It's also a method to identify persons in the venue who are not registered. 

## communication across orga 

@vsmart will set up a private slack group for the workshop day. Please log in to there on your phone and enable push notifications. this is useful so that we have a quick & immediate way to push info out to all orga members. 

## monitoring communication channels 

We encourage people to report issues via email too, since some people might prefer a non-verbal report. @vsmart will be monitoring the email inbox throughout the day. 

## if someone reports a CoC incident...

Of course, the correct steps vary vastly on the type of incident. What should apply in most cases is to  immediately inform the other orga members in the Slack group, and grab at least one more orga person to help out with the situation. Take the reporting person to the orga room to discuss the matter in private. Ideally, get a written account of their report. Be respectful and prioritize the person's autonomy & wishes on how to proceed. 
More notes here: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Responding_to_reports 

## guest policy 

ClojureBridge berlin has a guest policy. Please review it: https://github.com/clojurebridge-berlin/organization/blob/master/documents/guest_policy.md

The most important point is: only pre-registered people may enter the venue. This includes attendees, coaches, speakers, orga team. Excluded from this are vendors (child care people, caterers, security staff). 
If someone un-registered wants to enter, *2 orga team members* must agree to this, and the unregistered guest must sign in & agree to our code of conduct. 

## non-CoC safety incidents 

There is a checklist of important contacts posted in the orga room -- security staff, Wooga host contact, child care people. 

## Other stuff

What did I miss? Please comment.

**Comment by vsmart** [comment]
PS: Please leave a comment or :+1: to let me know you reviewed this.

**Comment by nblumoe** [comment]
Are we prepared to have guests sign a CoC if we would need that? Should we have printouts to be signed?

**Comment by vsmart** [comment]
Yep, printing out CoC is part of our on-day checklist https://github.com/clojurebridge-berlin/organization/issues/178

**Comment by vsmart** [comment]
As far as I'm aware, there were no CoC incidents at this event. There was one unregistered guest -- someone that a speaker brought along -- and I'm glad we had the guest policy in place for that. 
I'm looking forward to reading attendee feedback to get more insight. We can discuss how well these safety processes served us at the retro.
