### ISSUE TITLE
Twitter stuff

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#187]
Our sponsor policy promises shout outs on our social media pages. 
I think one tweet per top sponsor (nextjournal, circleci, zimpler), and one group tweet for the rest? 

Drafting up ideas here. :pencil2: 

Todo: 

* [x] nextjournal
* [x] circle ci 
* [x] zimpler
* [x] lambda island <3
* [ ] ~~group tweet for cognitect  mapbox~~
* [ ] ~~hosting location tweet for wooga + MS~~

**Comment by daiyi** [comment]
I'll help out with this!

Do you have twitter credentials? If so, I'll find you this morning and fetch them from you (:
