### ISSUE TITLE
Post-workshop action items 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#189]
Let's take a moment to celebrate an amazing workshop we put on last weekend. :sparkling_heart: :sparkles: 

Now, there are some remaining action items: 

* [x] #176 Wrap up finances 
* [x] Prepare feedback form @vsmart  & @JohannaCarola
* [x] Send out roundup email https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Roundup-email-attendees  --- @JohannaCarola
* [x] Send out goodies email https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Post-workshop-goodies
* [x] Add new attendees to study group mailing list --- @vsmart
* [x] Send out sponsors thank you https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Sponsor-Email-Thank-You-%28Version-2%29
* [x] Send out coaches thank you -- with feedback form 
* [x] Schedule a retro - November 16
* [x] Schedule a celebration dinner :tada:  - December 15

Let's aim to wrap these up in the next *2 weeks* so we can leave this workshop behind us and get some well-deserved rest :bed: :zzz:

**Comment by lislis** [comment]
Some attendees raised the question of staying in touch after the workshop. The current roundup mail does not include any info about our slack group. Should we mention that already?

**Comment by JohannaCarola** [comment]
the feedback form needs to be updated before we can send out the roundup email to attendees / the thank you email to coaches @lislis do you know how to do update this?

**Comment by JohannaCarola** [comment]
oh, it's part of the list anyway.. haha :D sorry

**Comment by vsmart** [comment]
@lislis I'm undecided on this one -- I'd like to keep the slack group as a place for people who continue to engage with the community / learners group (also remotely), but not as a catch-all for past attendees. Mentioning the slack group without an invite seems strange too. What do you think?

**Comment by lislis** [comment]
I think if attendees have a way of talking to each other and the thing that connects them is Clojure/ ClojureBridge that's a good incentive to engage with the community. Wdyt?

We can setup an invite thing on heroku similar to the web audio slack https://web-audio-slackin.herokuapp.com/ and paste the link into the email.
Then the attendees can decide whether or not they want to join. Thoughts?

**Comment by vsmart** [comment]
@JohannaCarola the feedback form is in the google drive. Steps to update are: 

* [x] locate feedback form in workshop 4 folder
* [x] make a copy, place it to Workshop 5 folder 
* [x] update form questions as needed 
* [x] under settings, click "accepting responses // add spreadsheet for responses" 
* [x] under settings, mark form as public

That should be all. 🤔

**Comment by JohannaCarola** [comment]
@vsmart OK, thank you! Will try it tomorrow evening! 😊

**Comment by vsmart** [comment]
@JohannaCarola 

![image](https://user-images.githubusercontent.com/2796920/31542641-1e66038a-b013-11e7-8985-af924a2cfa3a.png)

**Comment by vsmart** [comment]
I sent the sponsors thank you email.

**Comment by JohannaCarola** [comment]
I sent the attendee roundup email! :)

**Comment by endocrimes** [comment]
@lislis that sounds good to me

**Comment by lislis** [comment]
Sent out the goodies email ✅

**Comment by vsmart** [comment]
Coaches thank you sent! :muscle:

**Comment by vsmart** [comment]
I also sent a quick speakers thank you.
