### ISSUE TITLE
T-Shirts

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#19]
An organiser of CSSConf.eu told me cotton.de is awesome.

I have a T-Shirt from 2013 at home which I could bring to some potential meeting next time so we can see if we are all happy with it.
- [x] check with a contact at cotton.de to get an offer 
- [x] ask if it's possible to have different colors + fittings in one order.
- [x] design (probably clojurebridge logo + something) 
- [x] ensure we have a sponsor (maybe add them to the design?)

**Anything missing?**

**Comment by martinklepsch** [comment]
@clojurebridge-berlin/owners What do you think about putting sponsors on those T-Shirts? Probably not with their logo but rather a small 2-liner "supported by: DaWanda 6Wunderkinder..."?

**Comment by Malwine** [comment]
Ok, maybe a good idea, but are people going to wear it?
Then the design must be really cool!!!

**Comment by martinklepsch** [comment]
I can try to come up with something...

**Comment by Malwine** [comment]
:+1:

**Comment by thatbettina** [comment]
Why don't we have the same design on the t-shirt as on the tattoos (see https://github.com/clojurebridge-berlin/organization/issues/2#issuecomment-93409211)? Or is that too uncreative? ;)

**Comment by martinklepsch** [comment]
What I currently have in mind looks somewhat like the thing below. Ideally "Berlin" would be written in a similar typeface as text thats part of the logo. We could use 3 smaller lines below "Berlin" to mention supporters which I believe will be a nice selling point to sponsors.

This design probably doesn't work for tattoos. It should be fairly easy to adapt it for different t-shirt colors which we could use to help people identify coaches during the event :tada: 

![screenshot 2015-04-15 21 59 50](https://cloud.githubusercontent.com/assets/97496/7168056/cba1aa40-e3ba-11e4-9e7f-98363b160a4f.png)

**Comment by Malwine** [comment]
I like the idea.
Though I have to admit that we printed recently large logos on shirts and its a bit weird to wear.
Maybe we should make the logo smaller over the heart area for example?

**Comment by martinklepsch** [comment]
Yeah, maybe the proportions are a bit off. Do you mean weird in sense of wearing it or how it looks?

**Comment by Malwine** [comment]
It looks good, really! For the design part its great!
But the print is going to fall in peaces very soon. If it is a cheap print.
But even if we print offset it is better to have smaller details.
We also discussed that on the eurucamp conference last year :blush:

**Comment by Malwine** [comment]
Btw. I like "Stanley and Stella" as a base shirt because their cotton is really nice and it is a light fabric. And not so heavy.

**Comment by martinklepsch** [comment]
I have a shirt from CSS Conf 2013 which is also nice. I'll ask the printing company what brand it was and bring it to the meeting. Maybe you can bring yours as well so we can figure out whats better.

I'll send an email to the printing company asking for a rough quote now.

**Comment by martinklepsch** [comment]
Oh and we're definitely going to print offset. It's the cheaper option with an edition of 50 I think.
Why is it better to have smaller details when printing offset?

**Comment by Malwine** [comment]
Not only because of offset but the feeling when you wear it. Large prints are not so comfortable. But maybe thats just my opinion.

**Comment by martinklepsch** [comment]
I made another version: 
![clojurebridge-shirt](https://cloud.githubusercontent.com/assets/97496/7177947/40c2b1fa-e42b-11e4-999a-7f2ec8ab1ad1.png)

Regarding size of the ClojureBridge circle, I'd suggest we optimize around everything being still easily readable and not putting to much paint on it. I'll also ask the printing company for advice on that.

**Comment by plexus** [comment]
This meeting you speak of isn't actually planned yet, right?

**Comment by martinklepsch** [comment]
@plexus It's in the process of being planned, @thatbettina sent an email that you received as well I think.

**Comment by plexus** [comment]
ok I found the doodle now, nevermind :joy:

**Comment by Malwine** [comment]
I love the Berlin part with the special font :smile:

**Comment by Malwine** [comment]
@martinklepsch If we really move the event to 6Wunderkinder we need to change the order of the sponsos :)

**Comment by martinklepsch** [comment]
> Grundsätzlich merkt man schon, dass da Farbe auf dem Shirt ist. Sie ist flexibel, aber eben vorhanden. Wenn es nicht 100% farbtreu sein muss, könnten wir per Discharge drucken. Das Resultat ist dann meist ein wenig beige/hellgrau, aber der Druck ist nach der ersten Wäsche fast nicht mehr zu spüren.

[Discharge printing](http://forwardprinting.com/what-is-discharge-printing) might be an option to make the print less stiff.

**Comment by plexus** [comment]
:+1: I really like discharge prints :)

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
Hej @martinklepsch 
Showing the design to woman today and reading the [article](http://geekfeminism.wikia.com/wiki/T-shirts) @plexus shared earlier I found out that there could be a **problem** with the current design.

_From the article:_
"Text or images across the chest area of a shirt draw attention to that area. Many women are uncomfortable having attention drawn to their breasts in this manner."

What we could do is. Redesign again with a fitted cut:
![screen shot 2015-04-27 at 11 35 25](https://cloud.githubusercontent.com/assets/5123681/7345035/8d323bec-ecd1-11e4-8eb5-b2fb9c82382f.JPG)

_From the article:_
Some ideas for less-problematic designs:
- All-over designs, or large designs not centred on the bust line. 

Railsgirls Example:
![screen shot 2015-04-27 at 11 44 55](https://cloud.githubusercontent.com/assets/5123681/7345223/f0c69670-ecd2-11e4-81d1-375869fec8f3.JPG)

**Comment by martinklepsch** [comment]
@Malwine What exactly do you mean with _"What we could do is. Redesign too with a fitted cut"_?

For what it's worth RailsGirls shirts are also pretty [chest-centered](https://www.google.de/search?q=rails+girls+shirt&espv=2&biw=1440&bih=757&source=lnms&tbm=isch&sa=X&ei=AAU-VdG0NsK5Oum2gLgK&ved=0CAYQ_AUoAQ).

**Comment by Malwine** [comment]
Yes, but I mean the Berlin chapter of Railsgirls. I dont know what the rest of the world does.

I mean, we should see if the design still works with fittet cut.
The problem with the fitted cut is that the circle becomes more an oval over the chest area and the sponsors would be hidden under the breast.

**Comment by thatbettina** [comment]
Why don't we move the circle up?

**Comment by nicsnet** [comment]
We could have a smaller logo on one side, and the sponsors on the other. Or on the back?

**Comment by plexus** [comment]
Here's another proposal/suggestion, to widen the discussion a bit :)

![on-t-shirt](https://cloud.githubusercontent.com/assets/32212/7365841/26c8dfc8-ed94-11e4-9ee5-337b4a95b43e.png)

**Comment by nicsnet** [comment]
Cute! I love the parentheses with the enclosed text on the back!! I also like Martin's design. I was thinking maybe we should not do fitted T-shirts, but just have them loosely fitted. Then the logo would not change proportion too much.

**Comment by Malwine** [comment]
Thats a possible solution! I like it. :100:
I love the code on the back!!
Could also be very cool with discharge printing.
I am not sure if we are allowed to change the logo with the TV tower. :cold_sweat: 
But I like that more than a big circle on the breast. Although it would look good but just on a straight shirt worn by a guy.

**Comment by martinklepsch** [comment]
I feel like it's going to be very hard to make the "perfect" T-Shirt design, another guideline from the geekfeminism wiki to illustrate: 

> Vertical lines in the breast area will not appear straight up and down, but will stretch outward with the bustline, leading to the impression that the wearer is "too fat for the shirt." If using boxes or vertical lines in the design, consider what it will look like stretched this way.

---

> I am not sure if we are allowed to change the logo with the TV tower. :cold_sweat: 

There is no policy on using the logo but the original designer asked me to run our design by her if possible which makes me think that she would be happy if we don't modify it to much.

**Comment by thatbettina** [comment]
Let's not be shy and run it both designs by her!

On Tue, Apr 28, 2015 at 7:06 PM, Martin Klepsch notifications@github.com
wrote:

> I feel like it's going to be very hard to make the "perfect" T-Shirt
> design, another guideline from the geekfeminism wiki to illustrate:
> 
> Vertical lines in the breast area will not appear straight up and down,
> but will stretch outward with the bustline, leading to the impression that
> the wearer is "too fat for the shirt." If using boxes or vertical lines in
> the design, consider what it will look like stretched this way.
> 
> ---
> 
> I am not sure if we are allowed to change the logo with the TV tower. [image:
> :cold_sweat:]
> 
> There is no policy on using the logo but the original designer asked me to
> run our design by her if possible which makes me think that she would be
> happy if we don't modify it to much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clojurebridge-berlin/organization/issues/19#issuecomment-97139190
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by Malwine** [comment]
@martinklepsch I see your point. 
... ow... its hard :cold_sweat:

**Comment by thatbettina** [comment]
I like @nicsnet's idea of a single slim shirt using discharge printing on a design that is not chest-focused. 
One of my favorite t-shirts is the black one on the left: 
![image](https://cloud.githubusercontent.com/assets/2124990/7438269/acd482fa-f061-11e4-9edb-b40b579718f2.png)

"The black shirt is printed with discharge ink creating a unique effect on the tri-blend material", which is however a polyester-cotton blend.

It's not fitted for ladies, but it's not hugely wide or anything that makes me feel like I'm wearing a potato sack.

**Comment by Malwine** [comment]
Just for the material:
http://www.cotton.de/fair-bio/stanley-and-stella/stanley-acts/
It is a very good Tshirt. Also not too wide. eurucamp 2013 had that. And its still my favorite shirt :)

**Comment by plexus** [comment]
@martinklepsch did you manage to get any feedback from the original designer? Any chance we could invite them to this conversation?

Last Monday we had a chat about the t-shirts again with @nicsnet and @Malwine.  One idea (that I like) is to put the round logo + "Berlin" small on the front left, and the "clojure code" sponsors snippet on the back.

**Comment by plexus** [comment]
Just to show, this is what we had in mind (rough sketch)

![on-t-shirt-2](https://cloud.githubusercontent.com/assets/32212/7801674/e5c23e20-0328-11e5-8daf-e0843c7f75a6.png)

**Comment by Malwine** [comment]
I will make a request at www.cotton.de later.

**Comment by martinklepsch** [comment]
@Malwine What do you want to request? Is it about the new shirt type and back/front printing? 

I already was in touch with someone there, probably it's best if I (or you) pick up that thread again.

**Comment by plexus** [comment]
@martinklepsch could you comment on the above? Did we get any feedback from the enigmatic "original designer"? What's your opinion on the last proposal?

**Comment by martinklepsch** [comment]
The original designer is Jamie Kite, the person @thatbettina has also been in touch with for changes on the ClojureBridge website (I believe). I sent her an email around 6 days ago but haven't heard back unfortunately. As it stands we should probably just go ahead.

@plexus I'm happy with the last proposal :+1: **added:** I can make it print-ready when we need it.

**Comment by plexus** [comment]
Cool! Thanks for the update <3

**Comment by jgkite** [comment]
It's me, and I'm so sorry I haven't gotten back to you. I do have some notes I'll write up this morning and post to this thread.

**Comment by martinklepsch** [comment]
@jgkite no worries :)

**Comment by plexus** [comment]
@jgkite welcome :) thanks for chiming in!

**Comment by Malwine** [comment]
@martinklepsch Ok cool.
If you get back to cotton.de, it would be great to get a cost proposal for 50 shirts with our design sketch and best case this kind of shirt:
fitted cut: http://www.cotton.de/fair-bio/stanley-and-stella/stella-wants/
straight cut: http://www.cotton.de/fair-bio/stanley-and-stella/stanley-acts/

So we can get in touch with Ticketsolve about the final price.

**Comment by jgkite** [comment]
OK. My computer has been kernel panicking all morning, so pardon my brevity while I try to get this comment out before it happens again.

I don't love the stylistic alternate chosen for the "L" in the word Berlin. It's a little less flashy, but I think much more legible to use the context-aware version:

![berlin-logo](https://cloud.githubusercontent.com/assets/731773/7815669/e73fa020-0397-11e5-893d-753d294a29c0.png)

For the back, the only note I have is that GitHub has a capital "H" and that some of the sponsors may prefer to have their logo used rather than their name in a font not associated with their brand. I know that kills the "code" concept, but it may be worth asking before the t-shirt goes to print.

**Edited to add:** I can provide  PSD version of the above if needed.

**Comment by Malwine** [comment]
Ok good point, thanks for mentioning the logos @jgkite

**Comment by martinklepsch** [comment]
I've asked my contact at cotton.de for a quote for the Stanley and Stella Shirts + front and back discharge printing. 

@jgkite thanks for your input regarding the "L". Very much agree. I had trouble fine tuning all the open type features using the software I was using. If you could send me the "Berlin" part of the logo as `.svg` that would make my life a little easier :smile: 

I also like the ideas of putting sponsor's logos on the back. :)

**Comment by thatbettina** [comment]
Is it too late to add Soundcloud to our t-shirt?

**Comment by plexus** [comment]
Personally I don't like putting the sponsor logos on the t-shirt, or it would have to be pretty subtle. It makes me feel like I'm a walking billboard. Looking at my stash of conference shirts it's quite rare to see sponsors on there. 

Did we already list somewhere what we can or do offer sponsors? Some things that come to mind 
- logo / link on the website 
- mention from our twitter account 
- mention during the event 
- opportunity to do a lightning talk maybe? For one or two top sponsors 
- ?

**Comment by martinklepsch** [comment]
![screenshot 2015-05-28 16 57 31](https://cloud.githubusercontent.com/assets/97496/7863122/aed738aa-055a-11e5-9220-0700423a209d.png)

**Comment by plexus** [comment]
That's 300 euros more than budgetted... I'll check with Ticketsolve how far they're willing to stretch their budget. What are our options for making this cheaper?

**Comment by martinklepsch** [comment]
Yeah, the shirts @Malwine suggested are a bit more expensive than the ones I originally asked for (= based the estimation on) + back and front print also makes a difference.

**Comment by Malwine** [comment]
@martinklepsch Did they tell you how much time they need? That would be an important question.

Maybe we can use other shirts than Stella&Stanley but they are the nicest ones to really wear and they keep in a good shape for at least 2 years. Weather my B&C shirts or froot&loom shirts are all looking crappy after some washing and wearing + they don't feel nice on the skin.

**Comment by martinklepsch** [comment]
They need 10-15 working days.

**Comment by plexus** [comment]
Ticketsolve is cool with picking up the full tab for the T-shirts. We can invoice to them directly \o/

**Comment by Malwine** [comment]
:100:

**Comment by martinklepsch** [comment]
🙌

**Comment by Malwine** [comment]
The shirt sizes are the following:

| Size | Amount |
| --- | --- |
| S (fitted cut) | 9 |
| M (fitted cut) | 16 |
| L (fitted cut) | 1 |
| XL (fitted cut) | 0 |
| XXL (fitted cut) | 1 |
| ____ | ____ |
| S (straight cut) | 1 |
| M (straight cut) | 21 |
| L (straight cut) | 7 |
| XL (straight cut) | 1 |
| XXL (straight cut) | 2 |
| ____ | ____ |
| TOTAL | 59 |

@plexus suggested to have one more for every much requested size. For surprises or emrgencies.  
This table does NOT contain extra shirts.

**Comment by plexus** [comment]
Actually not so sure anymore if that'll be necessary. Since we expect at least a few no-shows there will be some t-shirts left as well.

**Comment by Malwine** [comment]
Ok, then not :blush: 
The table only contains the amount of shirts of all participants/coaches/orga.  No extra shirts.

**Comment by martinklepsch** [comment]
I updated the table and spreadsheet with Matt's size (M straight cut).

**Comment by Malwine** [comment]
Ok :blush:

**Comment by Malwine** [comment]
@martinklepsch I know you wanted to finalize the design , so I was thinking if the design looks good on the fitted shirt  :question: 
(The font could be smaller, I think)
![fitted_shirt_with_logo](https://cloud.githubusercontent.com/assets/5123681/8227088/7e4a7fd0-15a4-11e5-9f93-d38ba108a880.jpg)

**Comment by martinklepsch** [comment]
![shirts](https://cloud.githubusercontent.com/assets/97496/8230770/942610f2-15c3-11e5-9081-a0e7054b8418.jpg)

I was I had the idea of using EDN (clojure data) for the text on the back as it's actually more "data" than "function" (?!). Let me know what you think. :smile_cat: 

PS. I found the model pictures on [designbyhumans.com](http://www.designbyhumans.com/designguide) — pretty handy.

**Comment by Malwine** [comment]
I love it! :heart: 
(Check spelling please :blush: SoundCloud DaWanda GitHub)

**Comment by plexus** [comment]
Looks very nice!

**Comment by martinklepsch** [comment]
@Malwine haha, I thought about Github vs. GitHub doing it and was fairly certain its "Github". :laughing: 
Thanks!

**Comment by martinklepsch** [comment]
As per Telegram the opinion regarding colors seems to lean towards grey/anthracite.

Which leads to a slight problem with our straight shirts: The [Stanley Acts](http://www.cotton.de/fair-bio/stanley-and-stella/stanley-acts/) is not available in Anthracite. There's the [Stanley Leads](http://www.cotton.de/textilien/t-shirts/stanley-leads/) but it's about 1.70 Euro more.

```
32 (# of straight shirts) * 1.70 = 54.4 Euro
```

Options:
1. Pay 50 Euro more
2. Go with Navy or Black for the straight cut

**Comment by Malwine** [comment]
I am still for navy :blush:

**Comment by plexus** [comment]
It's a bit late to raise the budget for T-shirts _again_.

My vote is on anything colorful :)

**Comment by jgkite** [comment]
> I had the idea of using EDN (clojure data) for the text on the back as it's actually more "data" than "function" (?!). Let me know what you think.

:heart_eyes: Love what you did there!

**Comment by martinklepsch** [comment]
@jgkite Thank you! :smiley:

**Comment by jgkite** [comment]
@martinklepsch do you still need the vector version of the logo shown [here](https://github.com/clojurebridge-berlin/organization/issues/19#issuecomment-105574781) or are you good to go? I am finally on a non-crashing Mac, so I can recreate the one above, eaten by a vicious kernel panic.

**Comment by martinklepsch** [comment]
@jgkite I'm good to go. I've been using Sketch before which had very limited OpenType support but bought Affinity Designer today which actually has quite good support for this stuff so everything has been working fine :)

**Comment by jgkite** [comment]
@martinklepsch :+1: I really like how the design has evolved. Great work all!

**Comment by Malwine** [comment]
Hi @martinklepsch if you ordered them you could close the issue :blush:

**Comment by martinklepsch** [comment]
Hey all, I planned to make the order today but failed :/
Given that going with Anthracite is not really an option due to price, should I order 59 T-Shirts with the sizes listed above in Navy? 

@plexus thanks for the Ticketsolve details, will relay those to cotton.de when ordering.

@clojurebridge-berlin/owners Anyone final thoughts?

**Comment by Malwine** [comment]
:+1:

**Comment by thatbettina** [comment]
Tshirts have been ordered.
