### ISSUE TITLE
Find sponsors

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#2]
- Pineapple Media
- SoundCloud
- 6Wunderkinder

**Comment by martinklepsch** [comment]
I can talk to Pineapple Media about this next week.

**Comment by martinklepsch** [comment]
Futurice? /cc @nblumoe

**Comment by nblumoe** [comment]
Yes, interested. We are also doing GirlsDay and RailsGirls. Do you have
some more details? nblu@futurice.com

**Comment by martinklepsch** [comment]
I guess it would be good if we could prepare a list of what expenses are necessary and which are "bonus" so we can communicate that to potential sponsors. I created a wiki page ["Expenses"](https://github.com/clojurebridge-berlin/organization/wiki/Expenses) for that. It doesn't contain anything of substance yet though. 

Maybe we could talk to some RailsGirls organisers to figure out what's needed etc.

**Comment by nicsnet** [comment]
Andrei is going to talk to Chad Fowler from 6Wunderkinder about sponsoring and possibly hosting.
Also they have quite a few Clojure devs over there who might be interested in coaching.

**Comment by thatbettina** [comment]
We need sponsors
- for Friday night food
- for Friday location
- for Saturday lunch
- for Saturday coffee and drinks -- COLD DRINKS SPONSOR FOUND!

We would like to have sponsors for
- T-shirts -- 400 euros for 15 t-shirts?
- temporary tattoos
- other swag

**Comment by Malwine** [comment]
Dawanda would be interested in sponsoring drinks.

**Comment by thatbettina** [comment]
Soundcloud wants us to be online first. I will contact Soundcloud as soon as its up.

**Comment by Malwine** [comment]
Moved table to bottom. To not confuse it. (2015-05-06)

**Comment by martinklepsch** [comment]
> **Clojure cookies**
> 
> We have a history of having cookies with the Clojure logo printed on them so students can "take a bite out of Clojure." These can get expensive, though, so make sure you have enough sponsorship before you order these. Most bakeries can do logo cookies.

Haha, we need those :stuck_out_tongue: 

@Malwine is 6€ per T-Shirt (50 attendees) realistic? 

Regarding Friday: I assume this is what's in the docs is called Installfest? 
Is that a full day thing or just an evening?

I remember being at ResearchGate for a meetup and they had a nice big room,
maybe I can ping them about it.

**Comment by martinklepsch** [comment]
> Regarding Friday: I assume this is what's in the docs is called Installfest? Is that a full day thing or just an evening?

Answer is yes. See #11

**Comment by Malwine** [comment]
The T-Shirt question is still open. Should we have them for all people?
Or just for coaches?

**Comment by martinklepsch** [comment]
Would be ideal to have them in two colors, one for coaches, one for attendees — might not even make a price difference... 

I just had a chat with Kristina Schneider who's organizing CSSConf in Berlin. They usually order their shirts from cotton.de — I think in 2013 they had [these](http://www.cotton.de/textilien/t-shirts/anvil-fashion-t/). It would be around `5,34 * 50 * 1,19 = 318€` I think.

Should we have two styles for woman and man or just one for both?

**Comment by Malwine** [comment]
@martinklepsch  
It would be neat if you could take care of the T-Shirts organisation. 
So that you contact the print company as soon as we find a sponsor.
We can ask for the Tshirt Size in the application! What do you think?

**Comment by plexus** [comment]
Yes, we should ask for the T-shirt size, and if they prefer a fitted or straight T-shirt

http://geekfeminism.wikia.com/wiki/T-shirts

**Comment by martinklepsch** [comment]
I was worried that it would be hard to gather that information up front but you're right, we can just ask for it in the attendee forms. I'll open another issue for tracking T-Shirt progress (see #19).

@plexus thanks for the link, very helpful!

**Comment by martinklepsch** [comment]
It might be a good idea to send an email the the Berlin Clojure User Group mailing list like "ClojureBridge Berlin: Call for Sponsors". There are quite a few Soundclouders and some Nokia people on there.

**Comment by Malwine** [comment]
@martinklepsch Can you give me the mail address? Or ping me for the credetials for our mail account.

**Comment by martinklepsch** [comment]
https://groups.google.com/forum/#!forum/clojure-user-group-berlin — It's just this list.
I'd even send it from a personal mail account but let's wait until we have a clear idea of what we need and some quotes for things like food, shirts, stickers and so on.

**Comment by andreiursan** [comment]
I had a quick chat with Chad yesterday about sponsorship - I have positive feelings that we are going to sponsor - probably also the Friday Evening Location.

I will keep you guys updated with the official answer.

**Comment by jellea** [comment]
Asked Hitfox (@peterlih) today.

**Comment by martinklepsch** [comment]
Had a chat with Red Pineapple Media today and they're interested in sponsoring something as well. 

Super cool that there are so many companies happy to sponsor this kind of event! :heart_eyes_cat:

**Comment by nicsnet** [comment]
I got a quote from my tattoo contact. Minimum order is 1000. It depends on the size what the cost would be, but at least around 400 euros + shipping expenses + tax. If we don't get enough sponsorship we could also ask the ClojureBridge people in Solingen if they also would like to have some. Then we could split the costs.

**Comment by thatbettina** [comment]
I have a contact in Solingen; I will email @nicsnet their email.

**Comment by nicsnet** [comment]
We should also approach ThoughtWorks Berlin if there are interested in sponsoring.

**Comment by zahara** [comment]
GitHub is also worth a try
https://community.github.com/

**Comment by Malwine** [comment]
**Update** 2015-05-06
**New:** 6w sponsors location/ DaWanda is out for location

**Update** 2015-05-26 InnoQ has agreeed to sponsor Friday's dinner

Find table also in the [README](https://github.com/clojurebridge-berlin/organization/blob/master/README.md)

| What | Cost |
| --- | --- |
| Friday night food | **InnoQ** (400 Euro) |
| Friday location | **6wunderkinder** |
| Saturday location | **6wunderkinder** |
| Saturday lunch | 500 Euro |
| Saturday drinks (water and beer only + local coffee machine) | **6wunderkinder** |
| Saturday nonalcoholic drinks (lemonade, mate) | **DaWanda** (200 Euro ) |
| T-shirts | **Ticketsolve** (350 Euro) |
| 1000 temporary tattoos | 500 Euro |
| stickers (as many as we can get within our budget) | **Babbel** 100 Euro |
| 50 cupcakes with logo | **Babbel** 70 Euro |
| **TOTAL** | **2100 Euro** |

**Comment by Malwine** [comment]
Companies we want to ask, when we are live on the official website:
- Pineapple Media
- SoundCloud
- DaWanda :heavy_check_mark:
- Hitfox
- ThoughtWorks
- GitHub
- ...

**Comment by Malwine** [comment]
DaWanda on Board for nonalcoholic drinks! Yay! :tada: :lemon: :tropical_drink: :cocktail: :baby_bottle: https://github.com/clojurebridge-berlin/organization/issues/24

**Comment by thatbettina** [comment]
I don't think all of our numbers for the budget are updated to reflect the fact that we have twice the number of coaches as we aimed for. Can someone check the numbers? Originally, we were budgeting for ten coaches and now we have 20 I believe.

**Comment by Malwine** [comment]
@thatbettina 
Well, considering that some might drop out... 
And we can also choose 15 out of them. And tell the other to be backup.
(Also depending on the requested language by the attendees.)

So we have 15 coaches and 30 learners plus us organizers is +- 50 persons.
I would not raise the numbers higher as it is our first event.

(I can just imagine that T-Shirts will be more expensive.)

**Comment by nicsnet** [comment]
The experience from previous Clojure Bridge workshops held is that one should factor in a 25 - 50 % drop out rate. So if we have 20 coaches sign up to begin with, we could still end up with only ten. This depends of course on weather, events, time of year.

**Comment by martinklepsch** [comment]
Contact Github :white_check_mark:

**Comment by plexus** [comment]
Ticketsolve would be happy to sponsor the T-shirts

**Comment by Malwine** [comment]
:tada: Yay @plexus !!!

**Comment by Malwine** [comment]
I might put our sponsor table in the README

**Comment by Malwine** [comment]
@plexus Can you please have a look if the logo in https://github.com/clojurebridge-berlin/organization/issues/25 is the right logo? Thanks :blush:

**Comment by plexus** [comment]
yup looks good

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
Github on board, thanks to @martinklepsch :tada:

**Comment by martinklepsch** [comment]
@nicsnet said that Babbel would like to sponsor Stickers and cup cakes.

**Comment by martinklepsch** [comment]
Updated table from above:
Updated on 2015-05-31 (by Malwine)

:tada: **Soundcloud** is in with **400 Euro**.

| What | Cost |
| --- | --- |
| Friday night food | **InnoQ** (400 Euro) |
| Friday location | **6wunderkinder** |
| Saturday location | **6wunderkinder** |
| Saturday lunch | **Github** (500 Euro) |
| Saturday drinks (water and beer only + local coffee machine) | **6wunderkinder** |
| Saturday nonalcoholic drinks (lemonade, mate) | **DaWanda** (200 Euro ) |
| T-shirts | **Ticketsolve** (350 Euro) |
| 1000 temporary tattoos | 500 Euro :warning: |
| stickers (as many as we can get within our budget) | **Babbel** 100 Euro |
| 50 cupcakes with logo | **Babbel** 70 Euro |
| buffer money (posters, post-its, snacks) | 100 Euro :warning: |
| **TOTAL** | **2100 Euro** |

**Comment by Malwine** [comment]
Just FYI: We moved this table to the readme. :blush:

**Comment by martinklepsch** [comment]
Yeah I know. People will not be notified about changes to the Readme though so I thought it's better to continue updating it here :)

Which reminds me of my original question: have we heard back from Soundcloud? :smiley:

**Comment by plexus** [comment]
Somebody told me we might have a good chance with InnoQ. We wouldn't know anybody there? I've sent an email to get in touch but it's very via-via so maybe we can find a more direct contact?

**Comment by Malwine** [comment]
@martinklepsch then you might want to put Github in for Saturday lunch?

**Comment by plexus** [comment]
Claudia from InnoQ has just let me know they can cover for Friday's dinner :D :D :dancer: 

She also had a colleague sign up to be a coach.

Malwine and I talked to Sven yesterday to see if we can handle the financial part through Travis Foundation. It sounds like this shouldn't be a problem. Anika will check with their accountant what needs to happen exactly.

**Comment by plexus** [comment]
Thanks @skade for suggesting InnoQ and Dajana for putting me in touch :heart:

**Comment by Malwine** [comment]
InnoQ :heart_eyes: :heart:

**Comment by thatbettina** [comment]
Soundcloud can sponsor up to 400 euros !

**Comment by plexus** [comment]
Way to go Soundcloud! \o/

**Comment by thatbettina** [comment]
We got enough sponsors! Yay us!

**Comment by Malwine** [comment]
Moved final sponsors table out of readme.

### Sponsoring for the event on July 10/11

| What | Cost |
| --- | --- |
| Friday night food | **InnoQ** (400 Euro) |
| Friday location | **6wunderkinder** |
| Saturday location | **6wunderkinder** |
| Saturday lunch | **Github** (500 Euro) |
| Saturday drinks (water and beer only + local coffee machine) | **6wunderkinder** |
| Saturday nonalcoholic drinks (lemonade, mate) | **DaWanda** (200 Euro ) |
| T-shirts | **Ticketsolve** (350 Euro) |
| stickers (as many as we can get within our budget) | **Babbel** (100 Euro) |
| 50 cupcakes with logo | **Babbel** (70 Euro) |
| buffer money (snacks, croissants, coffee, nametags etc) | SoundCloud 400 Euro |
| **TOTAL** | **2020 Euro** |
