### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#20]
**Friday**
16:00 - 22:00 Installfest
**Saturday**
09:00 - 10:00 Welcome
10:00 - 13:00 Workshop First Part
13:00 - 14:00 Lunch
14:00 - 18:00 Workshop Second Part

**Comment by Malwine** [comment]
Please feel free to comment.

**Comment by thatbettina** [comment]
@Malwine -- When you mean the Installfest starts at 16, you mean that's when the setup would start (ie for the orgas) or for the coaches/learners? Ie, is this what we tell our sponsors when we need the room?

**Comment by Malwine** [comment]
Good question. Please dont close this issue. It's just for us to discuss.
I only made a rough plan. I have no idea yet. Maybe we have to plan more time.
Lets discuss this in person in the orga meeting.

**Comment by martinklepsch** [comment]
It's probably best if we communicate an hour earlier to the sponsors so we can make sure everything is in place, reception is setup, etc. Also some people might show up early.

**Comment by martinklepsch** [comment]
@Malwine I think closing the issue was not intentional :)

**Comment by thatbettina** [comment]
Nope, it was not intentional :)

On Wed, Apr 15, 2015 at 10:15 PM, Martin Klepsch notifications@github.com
wrote:

> @Malwine https://github.com/Malwine I think closing the issue was not
> intentional :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clojurebridge-berlin/organization/issues/20#issuecomment-93553200
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by Malwine** [comment]
@martinklepsch @thatbettina I know I just wanted to point it out. I :heart: you people. Please excuse my harsh communication :sob:

**Comment by martinklepsch** [comment]
❤️ 😸 ❤️

**Comment by thatbettina** [comment]
So what do you all think of the schedule I'm proposing?

### Friday

18:00 – 20:30 Installfest

### Saturday

9:00 – 9:30 Coffee & Registration
9:30 – 9:45 Welcome -- @Malwine in German and @thatbettina in English
9:45 - 10:15 ish Introduction into Clojure/script & Web Application Basics Talks -- @martinklepsch @plexus Do we need an intro or should we just dive into coding? 
10:15ish to 13:00 Coding in Groups
13:00 – 14:00 Lunch
14:00 – 14:30 Lightning Talks -- to be organized by @thatbettina
14:30 – 17:00 Coding in Groups
17:00 - 18:00 Demo of Code? -- @martinklepsch @plexus Will learners have anything to show at the end of the workshop? 
18:00   Goodbye & Official End of the Workshop

**Comment by plexus** [comment]
Looks good to me!

**Comment by Malwine** [comment]
:+1:

**Comment by martinklepsch** [comment]
> 9:45 - 10:15 ish Introduction into Clojure/script & Web Application Basics Talks

Whats this? Is this part of the curriculum or a lightning talk?

**Comment by thatbettina** [comment]
I thought there might be some parts of the curriculum that would be better as talk? Ie, how to use your editor / REPL tools and other basic stuff. 

Also, someone mentioned (mayble @jellea) about talking about Clojure/script as a language.

**Comment by Malwine** [comment]
The schedule worked well.
We started a bit later.
**Learning:** Registration, breakfast, T-Shirt-give-away and socializing took like 1 hour.
So then the schedule looked a bit like this:

09:00 – 10:00  Coffee & Registration
10:00 – 10:15  Welcome Talk
10:15 – 10:30  Intro to Clojure
10:30 – 13:00  Coding in Groups
13:00 – 14:00  Lunch
14:30 - Group Photo
14:30 – 15:30  Lightning Talks
15:30 – 17:30  Coding in Groups
17:30 – 18:30  Demo of Code 
19:00            Official End of the Workshop - Time to socialize

**Learning:** people loved the demo! it was amazing and encouraging to see the different results!

**Comment by thatbettina** [comment]
Oh @Malwine thanks for letting me know about the demo working really well. It's something we don't do at Rails Girls but we do at OpenTechSchool, so I wasn't sure about it for ClojureBridge.

I am also going to add group photo into the schedule, as it's something we always forget to do at OTS so I'm glad I "scheduled" it in for ClojureBridge and it happened!
