### ISSUE TITLE
Get a quote for lunch

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#21]
6W wants to help by sponsoring lunch and eventually a party.

It would be great if we can communicate some rough numbers to them of what we'll need.
This means someone needs to contact potential caterers and ask what things might cost.

Any takers?

/cc @andreiursan

**Comment by martinklepsch** [comment]
@plexus @thatbettina one of you two wanted to ask Toby about the caterer at Eurocamp I believe :)

**Comment by plexus** [comment]
Already did but he needed to ask Chris for more info. /cc @PragTob

**Comment by zahara** [comment]
Are you planning on getting dietary requirements in the signup form?

**Comment by martinklepsch** [comment]
That sounds like a good idea! /cc @Malwine

**Comment by Malwine** [comment]
Is already in. :smirk:

**Comment by martinklepsch** [comment]
- [x] @plexus: bitcrowd caterer
- [ ] @jellea: Mama's food
- [x] @thatbettina: iss kind iss
- [ ] @nicsnet: Knofi (eurucamp caterer)

How's progress on this?

**Comment by thatbettina** [comment]
I emailed iss kind iss and will report back as soon as I hear back.

**Comment by plexus** [comment]
How about Friday night dinner, should we ask for that as well?

We expect 50 mouths to feed for both?

**Comment by Malwine** [comment]
**Saturday:**
I wrote a mail today to `Gnamo` (who is already catering 6wunderkinder on their last day of every working week).
I asked them to give me an cost estimate for Saturday lunch.

**Friday:**
@nicsnet proposed to order pizza, which is also more of a "party" style :blush: 

Update on isskindiss:
@thatbettina forwarded their estimates and they were kind of too expensive.
Though I need to admit that they estimated 100 Euro for plates (although we have plates).
Still it was too expensive like 700 to 900 Euro.

**Comment by plexus** [comment]
Just got off the phone with Björn, the caterer that was at Bitcrowd in February. He will send a proposal. For Rug-B he made two different curries with rice.

**Comment by plexus** [comment]
> Hallo Arne,
> wie gestern mit Dir besprochen hier mein Angebot für das Catering am 11.6.2015.
> 
> Angebot - Mittagessen - 50 Personen - Budget 500 € netto
> 
> Für das Mittagessen habe ich folgenden Vorschlag.
> 
> Für die Fleischesser mache ich ein Südindisches Curry mit Hühnchen und lecker Gemüse.
> Für die Vegetarier gibt es ein sehr gutes Kichererbsen und Tofu Curry das von meinen Kunden immer wieder gerne bestellt wird.
> Dazu gibt es einen Cashew-Reis.
> Damit die Vitamine nicht zu kurz kommen noch einen Sauer-Süß-Apfel-Karotten-Salat.
> 
> Ich achte immer darauf das beim Lunch nicht zu schwere Zutaten eingesetzt werden.
> Ihr sollt arbeiten und denken können.
> Dementsprechend "leicht" mache ich das Essen auch.
> Grundsätzlich sind bei mir die meisten Zutaten BIO. Bei manchen Gemüse usw. macht es keinen Sinn und dann lasse ich es auch weg.

**Comment by plexus** [comment]
How do we proceed on this? Björn (Fineartz Cooking) is currently keeping the day blocked in his calendar. Let's say he's curious for news.

**Comment by Malwine** [comment]
I was writing to Gnamo (the caterer from 6wunderkinder). They didnt get back to me so far.
Just told me they're on vacation over last weekend. 

I like _Fineartz Cooking_ but the only problem we could have is that we have 2-3 vegans. No idea how to handle this.

**Comment by plexus** [comment]
> 2-3 vegans. No idea how to handle this.

That shouldn't be a problem. The above is a suggestion, he explicitly mentioned that if we wanted anything else like vegan we just need to ask.

As far as I'm concerned we could have everything vegan, or part vegan part vegetarian, but not sure if everybody would be cool with that :) How about we ask if he can replace the vegetarian option with a vegan option, so we have vegan/vegetarian + meat eater options?

**Comment by Malwine** [comment]
@plexus and all
What do you think about getting the pizza from here: http://sfizyveg.de/catering
Their vegan pizzas are awesome!!!!!
![screen shot 2015-06-01 at 12 22 49](https://cloud.githubusercontent.com/assets/5123681/7910934/fd19bb18-0858-11e5-94e3-5db5f86c3402.JPG)

**Comment by plexus** [comment]
suitably hip and, given that they use vegan cheese, not too expensive. cool with me

I mailed Fineartz yesterday about doing vegan/vegetarian.

**Comment by Malwine** [comment]
@plexus 
We should tell our Saturday caterer again the food preferences we have:

1) vegetarian
2) vegan (!) [really stress it :smile: ]

**More food restrictions:**
- Roggenallerie (rye allergy)
- Laktoseintoleranz (lactose intolerance)

**Comment by plexus** [comment]
They are well aware that we want vegetarian and vegan. I'll let them know about the allergies.

**Comment by Malwine** [comment]
Good, thank you. :)

**Comment by Malwine** [comment]
**Friday:**
La Pausa forgot our order and was around 90 min late.
The pizza we got then was good quality but half of it was with meat.
Though we ordered vegan and vegetarian.
**Learning:** We need a more reliable food provider next time.

**Saturday:**
As FineartzCooking really has bad luck atm (broke his both arms!)
Food wasprovided by Café Federica from Reichenbergerstr. 61a by Miriam L.
The food was on time,tasty and vegan!
**Learning**: we might consider her again for catering for different events!

**Comment by plexus** [comment]
La Pausa also cost more than expected because the prices on their website are wrong. They list €16,90 per pizza, but actually charge €18,00. I think we have reason enough to look for a different pizza supplier next time :)

**Comment by Malwine** [comment]
@plexus Oh no. So unreliable. I can't belive it. :cry:

**Comment by martinklepsch** [comment]
@plexus ugh. To be honest I think it's fair to ask for a 30% discount or something. They messed up terribly in all regards and should take responsibility for that.

**Comment by plexus** [comment]
Yeah I agree. I'm just not confident enough in German to make such a phone call or email. If anyone feels up to it that would be very cool. They can make a donation to Travis Foundation to make amends :)

Meanwhile I did the next best (or at least mildly satisfying thing), go to social media: https://twitter.com/plexus/status/620597638858190850

**Comment by martinklepsch** [comment]
I'll send an email tomorrow or call them depending on whether I have a phone available.

**Comment by martinklepsch** [comment]
I sent an email. Unfortunately we paid everything when we received the pizza which makes it harder to get a refund. We'll see. :)
