### ISSUE TITLE
New venue proposal: organise both events @6Wunderkinder HQ

### ISSUE THREAD

**Issue by andreiursan** [clojurebridge-berlin/organization#22]
6Wunderkinder would like to provide the space required for organising the workshop on:
- Friday, July 10, ~16:00-20:00
- Saturday, July 11, ~10:00-18:00
  (we are flexible on the times)

We are centrally located, @AlexanderPlatz, and we are more than happy to help with this initiative. 
We have enough space which includes:  an auditorium, a big kitchen, 2 open spaces, relaxation areas and meeting rooms. All of these are on a single floor.

Let me know if this will meet better your location requirements.

Note: Our building has some special security requirements.
Going up or down the elevator requires an access card.
I will be your main host and take care of any issues, also I will try to get some guest cards.

P.S. We also use and love Clojure.

**Comment by andreiursan** [comment]
If anyone is interested I would be happy to give you an office tour.

**Comment by Malwine** [comment]
@andreiursan I will come around as said in the chat :)
Very happy that we have a location for both events! :tada: :100: 
We can talk about the security requirements. I am sure we will find a solution.

**Comment by martinklepsch** [comment]
Jelle and I met with @andreiursan on Monday to check out the venue.

The space is really good I believe. It's one big space with a nice, casual auditorium a few tables, couches and so on. Maybe Andrei can send some pictures into the Telegram group if people are curious.

There are two things we need to solve/discuss:
1. Most likely there will be no accessible toilets. There are no on the 6Wunderkinder floors and we won't have access to other floors.
2. We will need to bring some extension cords to provide everyone with sockets. 6W can't provide many so we'll take care of it. I don't think this will be a big problem though.

**Comment by thatbettina** [comment]
@all - How do we feel about no accessible toilets? Is finding an accessible toilet nearby ok? I don't know how OTS solves this. Last Saturday's workshop someone could come up the elevator, but at least the bathroom I went to was too narrow to be accessible. 

@martinklepsch @andreiursan How many extension cords do we need? Otherwise worded, how many sockets can 6W provide? We ostensibly need 30 to 40 since not all 50 people need plugs at the same time, I hope.

**Comment by thatbettina** [comment]
We will have the events at 6W.
