### ISSUE TITLE
Cupcakes or cookies?

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#23]
@lauralindal ordered 50 Babycakes / Mini Cupcakes from http://www.cupcakeberlin.de/  
They were 1 Euro each. So 50 Euro. Plus 20 Euro for the logo. 
So in total 70 Euro. 
@martinklepsch \* wink \* to Pianapple Media

They need some time to prepare it. At least 4 weeks.

**Comment by thatbettina** [comment]
I like cupcakes and cookies. We should add this to our sponsorship list.

**Comment by Malwine** [comment]
Is in the table :blush: 
https://github.com/clojurebridge-berlin/organization/issues/2

**Comment by Malwine** [comment]
hej @nicsnet ,
are you on that? Because they told me they really need 4 weeks in advance.
:cookie:

**Comment by Malwine** [comment]
@nicsnet wrote in Telegram that she is on it.

**Comment by Malwine** [comment]
Is organized.
