### ISSUE TITLE
Nonalcoholic drinks

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#24]
**DaWanda** sponsors drinks, so what about:
- 48 bottles FRITZ ZITRONELIMO
- 48 bottles ALMDUDLER  (yummi)
- 40 bottles CLUB MATE
- 6 (1l) bottles BECKERS BESTER APFELSAFT TRÜB
- 12 bottles COCA COLA LIGHT (if diabetes or non sugar person)
- 12 bottles COCA COLA  

= **166 bottles**

**Comment by thatbettina** [comment]
Looks fine to me :)

**Comment by martinklepsch** [comment]
> 12 bottles COCA COLA

Are you thinking of big bottles here? I'd suggest getting Fritz Kola instead if not.
(Mostly because I don't want to support Coca Cola.)

**Comment by Malwine** [comment]
Ok, no problem, we can get Fritz Cola. Will adjust it. I didnt order so far. 
And also for the Light Cola we can get another non-sugar drink if you know one.

All of the botles are 0,5 or 0,3 l. Just apple juice is in 1l bottles.

**Comment by martinklepsch** [comment]
Maybe also Fritz if available? http://www.fritz-kola.de/fritz-kola-und-limo/fritz-kola-zuckerfrei/

**Comment by Malwine** [comment]
Jap, it's in their list. So I go for that :)
- with caffeine 
  24 bottles FRITZ COLA ZUCKERFREI (sugarfree if diabetes or non sugar person)
  24 bottles FRITZ COLA
  20 bottles CLUB MATE
- without caffeine
  48 bottles FRITZ ZITRONELIMO
  48 bottles ALMDUDLER (yummi)
  6 (1l) bottles BECKERS BESTER APFELSAFT TRÜB

= **170 bottles**

(Don't forget we have water, beer and coffee already provided.)

**Comment by martinklepsch** [comment]
> Jap, it's in their list. So I go for that :)

Perfect. :)

I'm sure no one will leave thirsty :+1:

**Comment by Malwine** [comment]
Ok, I will give DaWanda the order in time.
Closing.
