### ISSUE TITLE
ClojureBridge Website edits / adds

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#25]
Hi everyone,

To respect the website maintainer's time, let's collect all of our sponsors' names, links, and logos here as well as any edits we may have for our entry on the ClojureBridge website: http://www.clojurebridge.org/

Since she edits the website on Friday, I will email them to her in one email on Thursday(s).

**Comment by thatbettina** [comment]
From @Malwine 

Let's make a list for next friday(you can edit):
- Include DaWanda as a sponsor, file from here or I will also upload in our drive
  ![dawanda](https://cloud.githubusercontent.com/assets/5123681/7438027/1fbe1e4c-f05e-11e4-891b-1f05f28d982d.png)
- include ticketsolve logo
  ![ticketsolve](https://cloud.githubusercontent.com/assets/5123681/7494655/43ef898c-f409-11e4-8147-bb66ab861d45.png)
- add our mail-address to the description or in contact section clojurebridge.berlin@gmail.com

**Comment by thatbettina** [comment]
Also add some information about the core organizer team

**Comment by martinklepsch** [comment]
![github_logo](https://cloud.githubusercontent.com/assets/97496/7514126/ea4edfb0-f4ba-11e4-900d-ad9540ecb1f3.png)

Just heard back from Github! They're putting in 500 Euro! :+1:

**Comment by plexus** [comment]
\o/

**Comment by thatbettina** [comment]
I assume the right websites are:
-- http://de.dawanda.com/
-- https://github.com/
-- http://www.ticketsolve.com/

No response needed if those are the right ones.

**Comment by nicsnet** [comment]
![logo](https://cloud.githubusercontent.com/assets/1889716/7721952/3d6945ac-fedc-11e4-8393-337b1907c884.jpg)

http://www.babbel.com/

**Comment by Malwine** [comment]
Plus we need to get back to them concerning the "communication person".
Suggestion was that we say: 

> We are grateful for the involvement of **Clojurebridge Berlin Chapter**, who will be your host for this workshop.

And link our gmail account plus a group picture. That would be very fancy!!

**Comment by Malwine** [comment]
Ok here is a list with changes to the website:
- Add Babbel Logo/Link
- Link gmail account with group picture, set name to: "ClojureBridge Berlin Chapter"
- Link the form for coaches!
- Display our email in the contact box
- or link mail also in german text at: "schreib uns gerne eine Mail"
- Add a sentence: "The attendees will be chosen randomly."/ "Die Teilnehmerinnen werden zufällig ausgewählt."

**Comment by thatbettina** [comment]
Hi @Malwine - Thanks for letting me know that we don't need to give Jaime our photo if we link to our gmail account. What is the link for our gmail account? 

Also, are we really choosing attendees randomly? Or should we discuss if we want to make it for people with no / some experience or some other criteria?

Also, I will email her to add Soundcloud as a sponsor too.

**Comment by Malwine** [comment]
I dont really know how we can link the gmail account but we will find out.

Choosing attendees: Maybe we should discuss this in a further meeting.

![soundcloud](https://cloud.githubusercontent.com/assets/5123681/7903846/246dce9a-07e9-11e5-9c2a-dc76002dbea4.png)

We also need to add InnoQ to the sponsors! 
![innoq](https://cloud.githubusercontent.com/assets/5123681/7903831/c1dfb9f0-07e8-11e5-8051-6dddc9eddf17.png)
https://www.innoq.com/en/

**Comment by thatbettina** [comment]
@Malwine -- We can't display our email in the contact box, because that has to link to our google form.

I don't think the target group of the website is coaches, so I'd leave out the information for the coaches.

Can you translate this into German? 
EN: "Due to massive demand, the attendees will be chosen randomly." 
DE: "Die Teilnehmerinnen werden zufällig ausgewählt."

**Comment by Malwine** [comment]
@thatbettina 
ok, I see.
Can we put the mail then also in the german description?

DE: "Aufgrund der großen Nachfrage werden die Teilnehmerinnen zufällig ausgewählt."

**Comment by thatbettina** [comment]
Also I can't get Jelle's face into the circle :( https://plus.google.com/u/0/104816424693667644403/posts
Can someone help?

**Comment by thatbettina** [comment]
It's better on Gravatar: https://en.gravatar.com/clojurebridgeberlin

**Comment by thatbettina** [comment]
And yes, I will ask Jaime to link to the mail in the German exactly as you said.

**Comment by thatbettina** [comment]
We're done! I gave our last changes to Jaime! Hooray!
