### ISSUE TITLE
How to select attendees?

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#26]
@martinklepsch @thatbettina @plexus @nicsnet @andreiursan @jellea 

**How to select attendees?**

Possibility 1:
@jellea goes for first-in-first-serve, closing the application now and put others on the waiting list.

Possibility 2:
@malwine goes for doing it like the RailsGirls and keep the application open until July 1 and select 30 people randomly.

**Comment by plexus** [comment]
I'm for 2, that way we know what the real interest is, and we have a list of people to contact for a following workshop.

**Comment by jellea** [comment]
I'd like to close the application asap so we don't leave people in the dark for another 1,5 month and open up a mailing for future events. I don't like when events force you to block a weekend and say sorry one week before. I mean, let's respect the applicant's planning. This also has the effect of probably having a lower no-show-rate. Also, I would rather go for a random selection over the list we have now. Another thing to keep in mind are the t-shirts, we need more time than a week to get all the different sizes probably.

**Comment by plexus** [comment]
Ok, sure, there's no need to keep it open until the last minute either.

**Comment by Malwine** [comment]
So I just discussed with @nicsnet and @plexus and we came up with that idea:
- We could leave the application open until **June 10**.
  (Reason: We havent really reached the target group yet, which is beginners with no experience.)
- Then on June 10 we select people randomly.
  Send an email to the selected if they can make it.
- The ones that confirm get to the workshop.
  For the ones that say "no" we fill their place with the people on the waiting list.
  Does that sound like a compromise, @jellea ?

**Comment by plexus** [comment]
:+1:

**Comment by nicsnet** [comment]
:+1:

**Comment by jellea** [comment]
Sounds good to me! :+1:

**Comment by plexus** [comment]
![cat-high-five](https://cloud.githubusercontent.com/assets/32212/7688615/280b7c8e-fda6-11e4-97da-7e1728871aff.gif)

**Comment by Malwine** [comment]
Randomly chosen after the dates we decided.
