### ISSUE TITLE
Posters 

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#28]
I was thinking about some nice posters.
This is just an example.
I would like to have some funny code snippets (e.g. quizes).
![poster1_2](https://cloud.githubusercontent.com/assets/5123681/7816776/93834c78-03d0-11e5-96e0-a0ebd62e9e8c.png)

**Comment by Malwine** [comment]
"When in doubt - use vectors."
[1 2 3]

**Comment by thatbettina** [comment]
Maybe we could have the learners write inspiring posters for each other during our breaks. This would also work great on Twitter ;)

**Comment by Malwine** [comment]
:+1: I like that.

**Comment by Malwine** [comment]
IN the end I had no time to prepare that.
Next time then :smile:
