### ISSUE TITLE
Organize Lightning Talks / Idea Role-Play during Workshop

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#31]

**Comment by Malwine** [comment]
I would love to see talks on:
- "What can I do with Clojure" maybe held by @jellea  including music, animation etc. Also we could also show other awesome projects that were realized with Clojure, Clojurescript.  
- Continue learning in learning groups maybe by @andreiursan

**Comment by thatbettina** [comment]
# I am looking at the coaches' signup sheet.

Here are the topics they offered:
- Literate programming, Emacs Org, Software Engineering Overview
- Clojure, Machine Learning, Statistics
- flamboo
- repl based dev workflow
- Web Development, Clojurescript, APIs
- intro to web development/game development w/ clojure
- clojurescript
- Learn to Learn
- Clojurescript, Emacs

I noticed that I asked them for their "expert topics". 

I realize now that we don't really want "expert"-level talks, since we're addressing mainly beginners.

**Should I email all the coaches to ask if there are talks they'd like to give that address beginners?**

# Also, we'd like to encourage more women to take the stage.
- @Malwine or @nicsnet -- interested in speaking about something? Maybe about our CLJ art collective? 
- @martinklepsch is getting in touch with @kriesse to see if she'll talk about Berlin tech community initiatives (afaik she can probably also talk about front-end stuff). 

# Any topics you think we should have?
- Like @Malwine's ideas above.
- One I really liked from a Rails Girls workshop was a lightning talk of about "real programmers don't..." to bust myths about what programmers do or don't do (ie, don't google things, know names of every single thing, etc).
- CLJ Art Collective / Why we did ClojureBridge

**Comment by plexus** [comment]
+1 for @malwine @nicsnet and @thatbettina showing off what we did with CljArt :)

**Comment by Malwine** [comment]
I will probably do one half of the introduction presentation (general info about the workshop and maybe some basic clojure). 
At least the german part (as we need to give important info also in German. The lightning talks can be in english though.).
That is enough for me :blush:

**Comment by thatbettina** [comment]
@Malwine Good point about the language. I'll ask the coaches to present in either German or English, as they wish. Hope that's ok for you :)

**Comment by Malwine** [comment]
These awesome talks were held at ClojureBridge Berlin:

**Jelle:**  10 amazing things you can do with Clojure (in 10 minutes) (ENG)
**Maria:**  Summer of Code with ClojureScript (GER)
**Johannes:**  Advice to burgeoning programmers (ENG)
**Kristina:**  Open Tech Initiatives in Berlin (ENG)
**Andrei:**  Continue learning in learning groups *(ENG)
