### ISSUE TITLE
Friday Night Dinner

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#33]
This is something that hasn't received much attention yet because we would just "keep it simple" and "order some pizza". However we still need to figure out what we'll do exactly :) InnoQ will pick up the tab, so we have the € 400 as a budget.

The main question is finding a place that can prepare and deliver a large amount of pizzas. We were about 18 people at the coaches training. Add 30 attendees and subtract some no-shows and I think we could be around 40 people at the installfest. For the coaches training I ordered 12 pizzas, so about 2 per 3 persons. For the installfest I would go for 40 pizzas to be on the safe side. That should be plenty and would still leave us well within budget. I might check with InnoQ if we can split the budget between coaches training and installfest. The pizzas at the coaches training cost € 73,80, which I've advanced so far.

I sent an email to [Sfizy Veg](http://sfizyveg.de/catering) to see if they can do it and get a quote. Last weeks pizzas came from [Crunchy](http://www.crunchyberlin.de/). Not as fancy as Sfizy but the pizzas were decent IMO for a sharp price, so we can leave that as plan B.

**Comment by martinklepsch** [comment]
Potentially also consider the Soundcloud pizza dealer — whichever that is?
https://twitter.com/martinklepsch/status/610522389038952448

**Comment by martinklepsch** [comment]
Soundcloud pizza place is http://www.lapausa.de/

**Comment by Malwine** [comment]
http://lapausa.de/

**Comment by Malwine** [comment]
Called LaPausa on Monday with @plexus 
They said they can deliver and they want to get the order 2 or 1 week in advance.

**Comment by Malwine** [comment]
We should to order next week!

Including vegan options!!

**Comment by plexus** [comment]
Ordered 20 pizzas from La Pausa. 7 Vegan, 13 vegetarian. They're delivering Friday at 19:00.

These are huge pizzas so this is probably too much but it fits in the InnoQ budget, should be 338€.

**Comment by Malwine** [comment]
:+1: :pizza: :pizza: :pizza:

**Comment by Malwine** [comment]
Thank you Arneeee :blush:

**Comment by Malwine** [comment]
@plexus ordered.
