### ISSUE TITLE
Finances

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#34]
For sponsors and suppliers there are two possible scenarios. For some a sponsor is matched exactly to one cost, e.g. Ticketsolve+T-shirts. In this case the supplier can invoice the sponsor directly. For the cases where this isn't possible the sponsor can make a donation to Travis Foundation, and the foundation will give them a "Donation Receipt". Travis Foundation is a “Gemeinnützige Organisation” under German law, which means a "Donation Receipt" is fine for accounting/tax purposes. Travis Foundation _will not_ make invoices.
## Ticketsolve / T-shirts

T-shirts are sponsored by Ticketsolve, Cotton.de should make out an invoice directly to Ticketsolve. I've sent Martin the address and VAT number. I can chase them to make sure it gets paid.
## InnoQ / Pizzas (€ 400)

We'll split the budget from InnoQ (400 euro) to cover both the pizzas at the coaches training and at the installfest. I checked and it's cool for them. They will make a donation to Travis Foundation. I already advanced the money for the coaches training pizzas. I will also advance the money for the installfest pizzas, then take my receipts to the foundation to get refunded.

Pizzas for the coaches training cost € 73,80, so that leaves us € 336,20 for the installfest pizzas. 

We expected the installfest pizzas to be €338 (20 x €16,90) as that's the price listed on their website. In reality the price per pizza was €18,00 , so that came to €360.
## Github / Fineartz (€ 500)

@martinklepsch what exactly was agreed with GitHub? I think it might be easiest to get them to also donate to the foundation, we can figure out the rest ourselves from there.
## Soundcloud (€ 400)

This is "buffer money". They already made the order to transfer the money to the foundation, I'm waiting to get them their receipt. For any small costs (posters, tape, power sockets, stationary, croissants, etc) will go out of this budget. Keep your receipts when you buy anything, I will gather them all up and get you your money back.
## Babbel / Stickers (€ 87,24) / Cupcakes (€ 70)

Cupcakes were paid directly. Stickers should go through Travis foundation.

---
## Other costs

These go out of the buffer money
- Croissants (see #36), €84 euros. Need to paid on delivery Saturday morning. I can advance this and get the money back from Travis
- Stickers €87,24
- Take away coffee €54,40

**Comment by martinklepsch** [comment]
@plexus I'm trying to work out the details with Github, they've worked with the foundation before but they need some thing akin to an invoice to initiate payment. I hope our contact at Travis Foundation already knows what that means, if not maybe I can introduce them to Ciara, my contact at Github.

**Comment by plexus** [comment]
Ok we'll see how that goes. We can also let Fineartz invoice directly to Github.

**Comment by martinklepsch** [comment]
> We can also let Fineartz invoice directly to Github.

@plexus that actually sounds like a good idea.

The details I got from Github are below:

```
All I need you to do is please send the invoice to invoices@github.com, with a cc to sponsorships@github.com, and include the following details on your invoice:

* Event date and location
* Sponsorship amount, in USD
* Terms for payment. If there's no due date listed we will assume Net 30
* Basic details on what is covered by sponsorship. (Please ensure this is in English!)
* Banking information (either on the invoice itself, or on the attached wire request form)
* Name and Address of party receiving payment

Our address is: GitHub, Inc., 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA and our VAT registrant number is EU528001391 (if you need it!).
```

Do you think Fineartz is fine sending an invoice to a US company? The agreed sponsorship amount is 500 Euro, for the invoice it needs to be billed in USD though.

**Comment by plexus** [comment]
I'll check with Fineartz what they think.

**Comment by thatbettina** [comment]
Thanks @plexus for all this coordinating!

**Comment by plexus** [comment]
Fineartz is cool with invoicing to Github directly. I hope that works out well and they don't have to wait too long for their money... It seems they can request a shorter payment term than the typical 30 days, so I guess he could request to be paid within one or two weeks.

**Comment by plexus** [comment]
@nicsnet what's the score on the Babbel sponsorship? Are they paying for the cupcakes and stickers directly, or is there anything we need to coordinate?

**Comment by jellea** [comment]
I payed the stickers in advanced, will request a payback as soon Babbel payed.

**Comment by plexus** [comment]
Ah so Babbel is also going through the foundation? I'll have to know when they initiated the payment and who the receipt should go to.

**Comment by nicsnet** [comment]
I forwarded the invoice for the cupcakes directly to Babbel. This was not possible with the stickers since it required instant payment, so I gave them the info for the Travis foundation. @jellea can you send me the invoice for the stickers? I'll forward it to them, and then they can donate the money.

**Comment by plexus** [comment]
If Babbel still donates the sticker money to Travis foundation then we got 887,24 euro in donations. Pizzas, stickers, take-away coffee, croissants, cost 659.44 in total, so we should have 227.80 left as buffer for the future.

I just emailed all receipts that I had to Travis. The croissants are still a mystery though. I don't have a bill for them, and I don't know who paid them.

So finances is all wrapped up except for
- [x] confirming donation from Babbel and getting them their donation receipt
- [x] refunding whoever paid the croissants

**Comment by nicsnet** [comment]
Instructed a Babbel representative on how they can make a donation to the Travis Foundation. So we just have to wait for the receipt.

**Comment by thatbettina** [comment]
Hi @plexus -- I'll forward you the invoice for the croissants. I don't know who paid for them, however.

**Comment by thatbettina** [comment]
@plexus I just got an invoice for the croissants, so I guess I'm the one paying for them. Please let me know what I need to do to get the money back from the foundation. Thanks! (and it can wait until you're back from your travels)

**Comment by plexus** [comment]
Send the invoice and your account details to Anika, she should be able to
help you.

**Comment by plexus** [comment]
@thatbettina did that get wrapped up? did you get the money back for the croissants?

**Comment by thatbettina** [comment]
Yes! Thanks for asking :)

On Sat, Nov 21, 2015 at 11:55 AM, Arne Brasseur notifications@github.com
wrote:

> @thatbettina https://github.com/thatbettina did that get wrapped up?
> did you get the money back for the croissants?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clojurebridge-berlin/organization/issues/34#issuecomment-158627819
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by plexus** [comment]
done and done :)
