### ISSUE TITLE
Email Coaches

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#37]
@martinklepsch @Malwine @nicsnet @jellea @plexus -- I'd rather not be the contact person for questions as those two busy weeks I mentioned during our last orga meeting? That is this and next week! So can anyone else be open to answer questions? Also, someone who is coaching would be probably be better for answering the coaches' questions.

Anything else I need to add / change ? Thanks so much!

---

Dear Coaches,

Thanks for volunteering to coach for ClojureBridge Outreach Workshop for women next Saturday, July 11.

Here's more information about the event:

When:

Installfest: Friday, July 10 18:00 – 20:30 

Workshop: Saturday, July 11, Doors open at 9:00, Event starts at 9:30 and ends at 18:00

Where:

6 Wunderkinder's office

Karl-Liebknecht-Straße 32, 10178 Berlin, Germany

The nearest public transport stop is S + U Alexanderplatz.

Curriculum: 

The curriculum can be found here: https://github.com/ClojureBridge/curriculum . It is organized as a set of slides, mixed with exercises. Please go through them to get a feel of how you could approach things.

After the theory there are two tutorials for Quil apps. They are meant to solidify the day's learning, and provide an opportunity for exploring and being creative. You might not get to do both depending on the group's level and time, that's fine.

As an editor we will standardize on NightCode. It's minimalism is friendly to beginners, it has a built in REPL and code evaluation, and installing it is as simple as copying a single JAR file. Please install it and have a look before the workshop.

Food:

We will have drinks, dinner on Friday, light breakfast on Saturday and lunch on Saturday.

Lightning Talks: 

Some of you have already submitted expert topics on which you'd like to talk. Unfortunately, expert-level talks don't really fit a beginners' workshop, so if you'd like to give a 5-10 lightning talk for beginners, please let Bettina via email know what you'd like to talk about, how long it will be, your language of presentation, and if you have the slides already, a link to your slides.

Some talk proposals we have already, just to give you an idea : 
-- "What can I do with Clojure?" 
-- Continue learning in learning groups
-- Berlin tech community initiatives
-- CLJ Art Collective -- learning by playing

Please let Bettina know by July 6 if you want to do something (no slides needed!).

Timeline: 

Friday

18:00 – 20:30 Installfest

Saturday

9:00 – 9:30 Coffee & Registration
9:30 – 9:45 Welcome Talk
9:45 - 10:15 ish Introduction into Clojure/script & Web Application Basics Talks 
10:15ish to 13:00 Coding in Groups
13:00 – 14:00 Lunch
14:00 – 14:30 Lightning Talks 
14:30 – 17:00 Coding in Groups
17:00 - 18:00 Demo of Code? If learners have anything to demo.
18:00 Official End of the Workshop - Time to socialize

If you have any questions, please let me know via Twitter or email.

Thanks!
Bettina

**Comment by plexus** [comment]
@thatbettina I edited the part about the curriculum, and changed the last line of the schedule from `18:00 Goodbye & Official end of the workshop` to `18:00 Official end of the workshop - time to socialize`. I can send out the email.

**Comment by plexus** [comment]
Sent from the clojurebridge.berlin email. I've set up forwarding to my own email (better late than never) so I'll keep an eye on any repsonses.

:hankey: is getting real! :sunglasses:
