### ISSUE TITLE
Checkin

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#38]
How do we organize the checkin?
I created 2 good readable checkin-lists for coaches/organizers and attendees.
They are in the Google Drive as pdf-files!
They include the Shirt sizes(we need to give out, what is says on the paper, other wise it will be a mess :smile:  )

Questions:
- Is the Checkin downstairs possible?
- Or after we shuttle people in the 7. floor?
- When do we give out the shirts? (Friday/Saturday?)

**Comment by andreiursan** [comment]
I suggest to do the checking downstairs. Since that will simplify things.
We might try to leave the door @6th floor open, such that a 2nd card usage is not necessary.

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
Done.
