### ISSUE TITLE
Recruit coaches

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#4]

**Comment by martinklepsch** [comment]
:wave:

**Comment by thatbettina** [comment]
Awesome to see you here @martinklepsch ! Thanks for volunteering to coach and / or volunteering to recruit coaches?

**Comment by plexus** [comment]
I got a bunch of email addresses at the Clojure meet up. Would be good if
we could get a sign-up form for coaches going. Just a Google Doc is fine.
Needs to include languages (en/de) and operating systems they're familiar
with.

**Comment by nblumoe** [comment]
I would be interested in being a  coach, too

**Comment by thatbettina** [comment]
Should we have an Orga meeting to set up some of these structures?

On Thu, Mar 12, 2015 at 6:43 AM, Nils Blum-Oeste notifications@github.com
wrote:

> I would be interested in being a coach, too
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clojurebridge-berlin/organization/issues/4#issuecomment-78427105
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by thatbettina** [comment]
@plexus -- Google Doc is now created!

**Comment by martinklepsch** [comment]
@thatbettina I could share that via the @clojureberlin twitter account — should I do that? Any preferences regarding timing?

**Comment by thatbettina** [comment]
@martinklepsch just realized it's a huge privacy breach to have that Google Doc online. My next task is to make it into a form that populates the sheet, so please wait before you tweet it out! 

Also, if we decide to have a coaches training workshop beforehand, we should ask the coaches if they can make it to such a workshop.

I'd like also like to discuss with the core team if we should accept all levels of learners or focus on beginners or some combination?

**Comment by thatbettina** [comment]
Finally created the coaches / orga sign-up form: http://goo.gl/forms/75BhfI8Vqc 

Share widely and recruit awesome, generous people.

**Comment by martinklepsch** [comment]
Awesome, shared it :)

**Comment by martinklepsch** [comment]
@thatbettina can we add a field for notes to the form?

**Comment by plexus** [comment]
I added a field for "Notes / Comments"

**Comment by martinklepsch** [comment]
I just pinged Stefan Edlich from ClojureD if he could promote the event + the call for coaches.
He likes the program and will spread the word when he's back from vacation.
He mentioned that he think it'd be great if there's a more specific description of what we need.

Also other people I think are not familiar with the RailsBridge type of event and are not necessarily aware what coaching means in that context. I think it'd be good to write up a short blurb what coaches will do during the event. Many people expect that they need to give a presentation or workshop or something like that.

I might get to that later today, maybe tomorrow, but I'm also not super familiar so if anyone feels like he's in a good spot to describe the role of a coach please leave it here :smile:

Oh and he also asked that we post a list with things we need. Maybe an issue with a checklist that can be continuously updated would be good for that.

**Comment by plexus** [comment]
You can probably find a description in the ClojureBridge docs. They seem to be very good at documenting things :)

**Comment by plexus** [comment]
We should maybe also have a look at this, to see how we can split up the organizer roles https://github.com/ClojureBridge/organizing/blob/master/Three-Main-Roles.md

**Comment by martinklepsch** [comment]
Yep that sounds like a good idea. I'll try to read that cookbook over the next days, feeling pretty much like an amateur ;D

**Comment by thatbettina** [comment]
Hi @martinklepsch 

Great feedback from recruiting coaches! 
Would you like to write a more specific description of what coaching means for us? 
And giving a short presentation / lightning talk is NOT necessary, more like a little bonus. I will make that explicit in the coaches' signup form.

These are two great references:
http://docs.railsbridge.org/workshop/more_teacher_training
http://opentechschool.github.io/slides/presentations/coaching/

As for the checklist, that's what I'm using the Github issues for :) Any open issue means someone can step up and assign it to themselves, get it done, and close it.

**Comment by martinklepsch** [comment]
> As for the checklist, that's what I'm using the Github issues for :) Any open issue means someone can step up and assign it to themselves, get it done, and close it.

Sorry, that was a bit ambiguous. I think I was mostly referring to things other companies could help us: different things that need to be paid, locations, etc. I saw the Find Sponsors (#2) issue though which seems to do exactly that. Should I relay that list to some people or are we going to hold off on this until a "communicator" has been found (#13)?

**Comment by thatbettina** [comment]
@martinklepsch 

Yes! Finding sponsors is addressed in (#2). Different people have offered to get in touch with different companies, so it would be cool to have some way to organize that--maybe off Github for privacy reasons? 

I don't think we need to wait for a communicator for that, as finding sponsors usually requires a 1-to-1 contact, and the communicator is more for broadcast messages to many people.

**Comment by thatbettina** [comment]
We have 11 coaches signed up for July. Awesome!
