### ISSUE TITLE
Wrap up mails!

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#40]
Dear @clojurebridge-berlin/owners  and @martinklepsch 

We should send some wrap-up mails!

**Mail 1: Attendee feedback**
This mail only includes the link for the feedback form. We still have to implement that. But @thatbettina gave us a good template from OTS.
I already started a form in our Google Mail account. Please feel free to edit!

**Mail 2: Coaches feedback**
This mail only includes the link for the feedback form for coaches.

**Mail 3: Attendee Wrap-up** 
In that mail I would put all the links we promised to continue learning.
@andreiursan 's forms for the learning groups and a link to [BraveClojure book](http://www.braveclojure.com/)

**Mail 4: Sponsors Wrap-up** 
Let's also send our sponsors a mail with a picture and special thanks again.

**Comment by martinklepsch** [comment]
More things to add:
- Link to Chestnut Forum
- Link to Clojurians Slack instructions

**Comment by martinklepsch** [comment]
Draft for the attendees email here: 
https://github.com/clojurebridge-berlin/organization/wiki/Roundup-email-attendees

**Comment by Malwine** [comment]
Cool, thank you. Can we provide it in German too?

**Comment by thatbettina** [comment]
I like the draft! It's good information that should be preserved on the website ;)

**Comment by Malwine** [comment]
Mail 1- 3 is send! :tada: 
Only mail 4 is missing!

**Comment by Malwine** [comment]
Mails are all done.
