### ISSUE TITLE
Send T-Shirt to Supporters

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#41]
So we discussed that we can send the shirt we still have to our supporters.
Ali, our mentor, can get it when she visits Berlin in the next month.
And then we wanted to send one to @jgkite too, as she helped us with the website and shirts!

**Comment by martinklepsch** [comment]
@Malwine what are the sizes we still have? Straight S, M, L, if I remember correctly?

**Comment by jgkite** [comment]
@Malwine yay, thank you!! Where should I send details?

**Comment by Malwine** [comment]
@jgkite  I made a little form :smile:  http://goo.gl/forms/xZyAYwgNcU 
@martinklepsch I will check when I am at home. But I think you are right.

**Comment by jgkite** [comment]
@Malwine super cool, thank you!

**Comment by Malwine** [comment]
Dear @jgkite !
I send you the shirt a few weeks ago. I hope it will arrive at some point.
Sometimes that takes a long time.

**Comment by jgkite** [comment]
@Malwine Hey hey! I did receive the shirt last week and it's awesome!!! Thank you for sending it! :grinning:
