### ISSUE TITLE
What to do differently

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#42]
Our last workshop was a big success, and most things went well, so for this workshop I would like to not reinvent the wheel and do most things the same way again. Still there are some things that can/should be done better this time. Here's my initial dump of thoughts, please add your own in the comments.
## Signup form improvements

We already asked for dietary restrictions, disabilities, t-shirt size, preferred language, OS, bringing a +1

I would like to add
- Ask for the gender they identify as (free text). Better to make it clear and take the guesswork out of who is a +1, or signed up accidentally, etc.
- Ask for experience using these [levels as defined by ClojureBridge](https://github.com/ClojureBridge/organizing/blob/master/Class-level-grouping-guide.md#suggested-class-levels)
- Ask if people need childcare or a nursing room
- Ask for photo permission
## Accessibility and Childcare

6Wunderkinder is hosting us again, which is great, but they still don't have accessible toilets.

I would say that we wait and see. If for instance a wheelchair user signs up, then we can try our very best to find an alternative location. Similarly, if the question of childcare comes up, we try to find budget for it.
## Photos

I would like to make it clear up-front under what terms we take photos. My suggestion is to release them as CC-BY-NC-SA, i.e. Creative Commons, you have to give attribution, only for non-commercial works, derivative works need to be shared under the same terms.

Right now there is an implicit agreement that we use these to promote the event, but we were also recently asked if a group picture could be used in a conference slide deck. In this case it's not clear what the deal is.

For photo permission I would give three options: "Yes, it's ok, you can take photos of me", "No thanks, please don't take any photos of me", "I'm ok with being in the group picture, but no closeup/portrait/small group pics".
## Food & drinks
- Installfest pizza was late, not what we ordered, more expensive than advertised, and way too much (that last one is our fault, for the rest shame on La Pausa :P). Reconsider at least the supplier if not pizza in general. ClojureBridge suggest 2-3 slices of pizza per person, plus salad.
- Make sure we have a vegan breakfast option
- Make sure we have coffee
## T-shirt

Everybody loves the t-shirt so that's good. I do think the original idea was to do discharge printing. I think that would be really cool and would like to see if we can make that happen.
## Aftermath and communicating upstream

Due to timing we couldn't do a proper retrospective shortly after the workshops, which is a shame. We should schedule that ahead of time to make sure it happens.

I would also like to someone explicitly taking care of making sure improvements to the organization docs, teachers training slides, curriculum, make their way upstream.
## Afterparty

This is something the ClojureBridge docs mention several times. Should we consider picking an "official" venue instead of having people find their own way after the workshop?

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
## Coaches Signup form improvements
- What is your background? Which languages do you know well besides Clojure?
- Did you coach before? And if so, where? 
- How experienced do you see yourself in using Clojure? (just started 1 to 10 use in production)
- Do you prefer to coach beginners or advanced attendees?
- In which language do you like to coach? 
- What is your shirt size?
- Ask for the gender they identify as

**Comment by Malwine** [comment]
# T-shirt

If we take the same design again I would like to adjust the position of the front round CB logo. For women it needs to be a bit more to the middle to be placed nicely on the chest. Otherwise it gets crumpled to the side.

**Comment by Malwine** [comment]
## Photos

Maybe we can have lanyards or name tags in differents colors so people can easily see if they can take photos.

**Comment by Malwine** [comment]
## Friday Caterer

I want to propose http://suppen-cult.de/ for friday catering.
They have awesome vegan & vegetarian (& meat) soups.
We still need to **check if they are in our price range** (especially if the host can not provide enough bowls and we have to rent them). 
But in Winter a hot soup right when people enter for the Installfest could be awesome. :stew: :ramen:  :heart_eyes:

**Comment by thatbettina** [comment]
I just emailed Brezel Company to see which of their pretzels and croissants are vegan to see if we can use them again for breakfast.

But before I go too much into the details, let's see how many coaches we have to know how many learners we can invite as well as how generous the sponsors are to see how many meals we can provide.

**Comment by thatbettina** [comment]
Vegan food at Brezel Company:

101     Laugenbrezel 100g       0,70 €
858     Apfel Streusel (vegan)  19,26 €
866     Schoko-Kirsch-Streuesel (vegan) 19,26 €

Wir freuen uns über eine Vorlaufzeit von 2 Tagen.

**Comment by thatbettina** [comment]
We should answer this question at our next meeting: Should we consider picking an "official" venue instead of having people find their own way after the workshop? 
I think yes, and we should pick a venue that also offers non-alcoholic beverages. @plexus What about that place in Mitte after the RG workshop at Fyber?

**Comment by plexus** [comment]
You mean the Buchhandlung? https://de-de.facebook.com/BuchhandlungCaffetteriaBar/

It's a nice place, but probably too small for our group.

**Comment by vsmart** [comment]
How about Kaschk for the afterparty? It's a coffee shop + craft beer place, they have some space, most importantly it's very close by

**Comment by plexus** [comment]
That's a great idea. We should notify them that we're coming with a big group though.
