### ISSUE TITLE
Kicking off organization for the January 2016 workshop

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#43]
Hi everyone,

It's happening again, two months from now we'll have the second ClojureBridge Berlin, yay \o/ on Jan 22 and 23, 2016.

6Wunderkinder has agreed to host us again. This time Franziska will be our host instead of Andrei.

I think we already got most things right last time, so we should be able to replicate most of what we did this time. I compiled a ["fact book"](https://github.com/clojurebridge-berlin/organization/blob/master/2015-07-11-factbook.md) with all the small details for reference.

A few things we should reconsider. I captured the things I could think of in [a separate issue](https://github.com/clojurebridge-berlin/organization/issues/42). Have a look there and comment or add your own.

I am trying to document our way of working, and listing up all the tasks that need doing, split by area of responsibility and by organization phase (planning, pre-workshop, workshop, aftermath). Malwine started a document, [ClojureBridge Tasks and Roles](https://docs.google.com/document/d/1VfGy6WR2VSPQzLjTW6eX_IBD1wYuzidJsLefoaow7Q0/edit?ts=563d1c37#), and I'm continuing on that, currently going through the (very badly organized) ClojureBridge/organization repo to see what I've missed.

I will split that out into
- a markdown file with general info that all organizers should read
- templates for Github issues with checklists that are reusable

After that it's "just" handing out the work and getting it done :P

So far have responded to my call-for-organizers: Nicola, Jelle, and with a lesser time commitment: Malwine and Bettina. So far none of the alumni have responded.

I'll ask around a bit more and approach people personally. Please do the same, I really hope to split up the work on this one.

Alright, let's do this :dancer: 

@nicsnet @jellea @Malwine @thatbettina @vsmart @martinklepsch

**Comment by Malwine** [comment]
:100: @plexus

**Comment by thatbettina** [comment]
Wow, looks like @plexus got EVERYTHING. It's also stunning to see all the stuff we did for CB1 listed all out.

**Comment by vsmart** [comment]
sounds great! Sorry I haven't filled out the doc yet.  :rainbow:

**Comment by plexus** [comment]
That's cool, great to have you on the team in any case :)

@lislis also signed up, so I think with that we should have a pretty good team together.

**Comment by jellea** [comment]
🤘🏼Is it an idea to all pick a role/task already? I'm up for coaches org + merchandise role.

**Comment by thatbettina** [comment]
So are we meeting anytime soon to get this going? I propose this week Thursday or Tuesday night we meet over dinner.

**Comment by plexus** [comment]
@jellea totally - don't let me hold you back from doing stuff :D

@thatbettina I like the idea because I would love to see you all again. Organizationally I think we should be able to do most stuff online this time.

Thursday I'm planning to go to Rug::B, but Tuesday would work. Maybe you can just pick a place and then we'll see how many can join?

**Comment by thatbettina** [comment]
So Tuesday 7pm at this vegan burger place I've been meaning to try: http://letitbevegan.de/menu/ 

Who else should be contacted about this, in case they're not subscribed to this issue?

If people tell me that they're coming, I can reserve a table for us all.

**Comment by plexus** [comment]
Santa Maria Kreuzberg (Oranienstraße)? Haven't been there in ages cause it's always so crowded. Do they take reservations?

**Comment by plexus** [comment]
@jellea I made two issues with the main tasks I could see regarding coaches and merchandise, #45 & #46. Can you roll with that?

**Comment by plexus** [comment]
I made a general issue for the role of "attendee care". This is by far our most important job. Last time Malwine did all of it (and more) but she can't do that now...

Any takers? Maybe two people can team up on this?

https://github.com/clojurebridge-berlin/organization/issues/47

**Comment by jellea** [comment]
@plexus great, nice chunks! hope to send out a coach form tonight/tomorrow when google docs is online again.

Can move an appointment to make it Tuesday if we decide soonish.

**Comment by plexus** [comment]
I would go ahead for Tuesday, at a minimum it's you, Bettina, and me, which already isn't bad :)

**Comment by Malwine** [comment]
I can be there. But we need to give lots of money to the Rubycorns. :moneybag: :smile:

**Comment by thatbettina** [comment]
Hi, so we're at least 4 people for the vegan creperie and burger place? I'll make a reservation for us. (I decided that Santa Maria would be too noisy on Tuesdays. Plus, loitering is probably discouraged since there are usually people waiting to eat.) What about @nicsnet @vsmart @martinklepsch ? 

I can help with attendee care, but I would not be able to do all of that. I'd like to actually participate in the workshop, so I'd like to focus on the pre- and post-workshop tasks.

**Comment by lislis** [comment]
I can also be there and and not go the Rubycorns (just like @Malwine ;))

**Comment by thatbettina** [comment]
Ok @lislis I got you for the reservation, and I added the dates of the workshop to @plexus issue description above. Since I had to look that up to add it to my calendar, I thought that it might be useful for others too.

**Comment by vsmart** [comment]
I'll be there! Can we say 8pm though? If you haven't made the reservation yet.

**Comment by nicsnet** [comment]
Count me in as well!

**Comment by plexus** [comment]
Oh wow we're nearly complete! Last time it took two months and several doodles to find a date :D

**Comment by thatbettina** [comment]
Haha. I made the reservation already, but I think 7 people for 8pm should be ok. Is Github the best way to get in touch with everyone in case there's last minute changes from Let It Be?

**Comment by thatbettina** [comment]
PS: Message from Let It Be: they have to push together two tables which fits 6 people and then one of us has to sit on a stool at the head. So we can't have any more people come. Hope that's ok for anyone who is still thinking about showing up.

**Comment by plexus** [comment]
So reservation is at 8? Or still at 7 and we hang around long enough? :D

This is the address

Treptowerstr. 90
12059 Berlin

**Comment by thatbettina** [comment]
I made the reservation for 8 pm :)

**Comment by plexus** [comment]
Agenda
- Say hi to the new team and have some tasty food :)
- Say a few words about how we generally work, and how we use Github, Google Forms/Drive, Slack [see also: how we work](https://github.com/clojurebridge-berlin/organization/blob/master/how_we_work.md)
- Re-iterate the main things people need to know regarding finances and paperwork
- Have a look at the most urgent tasks
  - getting the attendee form up
  - getting the coaches form up
  - getting the clojurebridge.org event page up
  - find sponsors
- go over the main areas of responsibility as outlined [here](https://docs.google.com/document/d/1VfGy6WR2VSPQzLjTW6eX_IBD1wYuzidJsLefoaow7Q0/edit?ts=565dcaac#) and see if anyone is willing to take up any of these
- talk about the phrasing to use regarding our target audience, so we can be consistent in that

**Comment by martinklepsch** [comment]
Close this?
