### ISSUE TITLE
Coaches communication

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#45]
Planning
- [x] prepare application form
- [x] promote to potential coaches
- [x] create doodle for coaches preparation evening, find date
- [x] mail date to selected coaches

Pre-workshop
- [x] create meetup
- [x] review the "coaches training" material and host the training event
- [x] send them the details and reminders about the workshop

Installfest, Workshop:
- [x] Receive coaches, give them name tags, hand out t-shirts
- [x] Help coordinate groups, answer questions from coaches

**Comment by jellea** [comment]
Can somebody check the form before I mail this out to former coaches and spread on Twitter? http://goo.gl/forms/KlVJbDY5ak

**Comment by jellea** [comment]
@plexus ? ^

**Comment by plexus** [comment]
Malwine had several things to add listed [here](https://github.com/clojurebridge-berlin/organization/issues/42#issuecomment-158793975)

**Comment by plexus** [comment]
I guess you have most of those except
- What is your background? Which languages do you know well besides Clojure?
- How experienced do you see yourself in using Clojure? (just started 1 to 10 use in production)
- Do you prefer to coach beginners or advanced attendees?

All in all looks pretty good, it's becoming a big form but at least that way we only have to ask those questions once.

For the attendee form we're going to use the descriptions to provide German translations, so we can have one EN/DE form. Should we do that here too, or do we assume coaches know enough English?

**Comment by jellea** [comment]
I get the 3rd question, but don't see why we should ask the first two. Threw in the second one anyway because the linear scales look so beautiful in the new forms :P Check ones more :)

Going to do English only myself. Feel free to unleash your German if you want, but guess its overkill.

**Comment by plexus** [comment]
Yeah just throwing the German thing out there as an idea. I also don't think it's immediately necessary, it would also mean we have to do our coaches training in two languages which is hard given it's mostly group discussion. Still it's worth keeping in mind: are there people out there that are happy to coach in German but aren't very comfortable in English?

**Comment by plexus** [comment]
Did you make the form in the Clojurebridge.Berlin account? I can't find the doc...

**Comment by jellea** [comment]
No, i don't have access to the clojurebridge account. But can easily share it.

**Comment by Malwine** [comment]
@jellea I can give you the credentials.
I think its better if we have it in the Clojurebridge account for access of the data and for the overview.

**I have some comments on the form:**
- Advanced - Last time that was more like "Junior Dev Ruby" instead of advanced Clojure like "ppl who know a diff lang". Keep in mind we don't have many women in Clojure in Berlin. And if we have them they will coach.
- "What is your background? Which languages do you know well besides Clojure?" is very important for the attendee-coach matching. So if you make a group of attendees that know Ruby it is good to have a coach that knows Ruby as well. Because there will be questions like: "In Ruby you do it that way... how is it in Clojure?"
- Potential Expert Topic: as already discussed change to sth like: Potential Lightning Talk Topic  
- Shirts: maybe give a note that "fitted" might mean waisted cut

**Comment by jellea** [comment]
@Malwine I can make the clojurebridge account owner of the file and its basically the same.

Will do the changes tonight.

@vsmart Are you able to pick a date today for the coaches meeting?

**Comment by thatbettina** [comment]
@jellea I saw Thomas E who coached last time, and he said that he'll coach this time too :)

**Comment by jellea** [comment]
Shared the doc with the org account and edited it according @Malwine's feedback. Feel free to send it out now! :D

**Comment by jellea** [comment]
Here's the URL once more: http://goo.gl/forms/KlVJbDY5ak

**Comment by plexus** [comment]
As was mentioned in another thread it might be better to use the Berlin code of conduct (http://berlincodeofconduct.org/), it's more comprehensive, and it's available in German and English (and several other languages). I'll update the attendee sign-up form and make sure it's mentioned on the clojurebridge.org page.

**Comment by jellea** [comment]
Ok changed!

**Comment by vsmart** [comment]
@jellea Thursday 14th Jan for the coaches training works for wunderlist.

**Comment by thatbettina** [comment]
Is it too early for me to start contacting the coaches who volunteered to give a lightning talk? Is there a date when the coaches sign up closes?

**Comment by jellea** [comment]
How are the signups for attendees going? Is it time to start promoting to get more coaches? Just tweeted this, lets time the retweets a bit for more exposure: https://twitter.com/jellea/status/681201190957363200 Also make your own tweets, more stuff to retweet :)

Also maybe its an idea to ask ClojureD/BOB conf to reach out?

**Comment by plexus** [comment]
Coaches training is in just over a week. It's time to get reminders out to the coaches. I already had one guy contact me directly to ask what was up. @jellea do you have time to send out an email in the next day or two? If not I can do it.

We now have 16 coaches signed up, including two of the orga team (Jelle and Nicola). A few more would certainly be good. Last time we were with 17 coaches, and it's always possible a few don't show up.

**Comment by vsmart** [comment]
I think it'd be helpful if we had a rough time schedule for the training evening. e.g. 7-7.30 arrival & greeting & food (if we have any), 7.30 - 9. official discussion, or something like that. I think it went a bit too long last time (and didn't start till 8.30ish iirc). Ideally we could put that in the email too.

**Comment by plexus** [comment]
Keeping it to an hour and a half is a bit optimistic I think, but we can try :) I'll mention the schedule in the email.
