### ISSUE TITLE
Merchandise

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#46]
- [x] Decide on what to get exactly (t-shirt design, sticker design)
- [x] order in time
- [x] make sure it gets to the venue (pick it up or have it delivered)

**Comment by jellea** [comment]
@plexus Are you going to pick up the notebooks? When are we going to decorate them?

**Comment by plexus** [comment]
Yup I need to be in kreuzberg tomorrow, I'll pick them up. 

@jellea or @vsmart would it be possible to print the labels at Fy or Wunderlist? I'm free all day tue/wed/thu.
