### ISSUE TITLE
Attendee Care

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#47]
For our attendees you are the face of ClojureBridge Berlin. You take and process their applications, you handle communication with them, you make sure their needs and concerns are addressed.

Planning:
- [x] prepare 1 application form which includes both languages GER/ENG
- [x] set date on closing the form - Jan 8?

Pre-workshop:
- [x] select attendees (time intense)
- [x] mail “on board” and “waiting list” mails
- [x] get confirmation/cancellation
- [x] send mails to waiting list
- ~~[ ] report shirt sizes to merchandise role~~
- [x] match coaches with attendees to groups (considering experience and language) (time intense)

Installfest:
- [x] Receive attendees, give them name tags, explain what's going to happen

Workshop:
- [x] Receive attendees, give them name tags, hand out t-shirts
- [x] Handle last minute group changes (due to no-shows, level gaps, etc)
- [x] encourage people to show their results in the code demo

Aftermath:
- [x] Send thank you email with pointers to continue learning
- [ ] Help people find the way to the study groups

**Comment by lislis** [comment]
I think the first point is done. What about the 2nd one? There is no closing date on the form afaik or should we just close the form on the 8th?

**Comment by thatbettina** [comment]
@lislis I think if someone can write the closing date on the website, that would be great, but I think that's a "nice to have" only if someone has time. Otherwise, we just close the form on the 8th IMO.

**Comment by plexus** [comment]
Anyone opposed to closing the form? We already have 67 signups!

**Comment by thatbettina** [comment]
Do it!

**Comment by thatbettina** [comment]
@lislis and @Malwine Do you need any help selecting the attendees? :)

**Comment by Malwine** [comment]
@thatbettina @lislis I closed the application form. Next time we should give a date on the closing. I wrote a mail to Lisa with more information on the Attendee process.Because I am out due to more exams.

**Comment by vsmart** [comment]
Not sure if this falls under attendee care but @lislis - are you mc-ing in both German and English?

**Comment by Malwine** [comment]
Maybe this time 2 people can share the MCing. This was actually the plan for 2015 but Bettina couldn't attend as an MC that day.

**Comment by lislis** [comment]
I'm fine with doing both but it'd be also cool to have a second person :)

@Malwine I wanted to ask if you used/ have any slides or notes for the opening?

**Comment by Malwine** [comment]
@lislis https://clojurebridge-berlin.github.io/ClojureBridgeBerlin_Intro_Talk.pdf 
I probably have the presentation file itself at home. Let me check.

**Comment by Malwine** [comment]
@lislis Found: https://docs.google.com/presentation/d/1XD4dg94OW4l1RypbS85i7c7PZ_1vSSNJ4Ir9GyQskvM/edit?usp=sharing

**Comment by lislis** [comment]
@Malwine AMAZING :sparkles:

**Comment by thatbettina** [comment]
I could impromptu MC in English if you'd like @lislis

**Comment by vsmart** [comment]
aw no @thatbettina, you should be able to focus on the workshop day as a learner

**Comment by lislis** [comment]
@thatbettina that's fine. I'll just prep for both and you enjoy the workshop :D
