### ISSUE TITLE
Promotion of the event

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#49]
Please add more ideas how we can promote the event!
Especially if you have contacts.
- [ ] Radio Funkhaus Europa (@malwine)
- [x] Twitter (ClojureBerlin)
- [ ] Twitter from our private accounts (ongoing)
- [ ] News Papers / Magazines
- [ ] Online News Sites & Magazines
- [x] Juniors are awesome - Slack channel
- [ ] Facebook (@martinklepsch)

Mailing lists:
- [x] Alumni list on Clojureverse
- [ ] Rails Girls Berlin list
- [x] Rubymonstas list
- [ ] Clojure Berlin google group
- [x] HTW Mailinglist

**Comment by thatbettina** [comment]
@Malwine How much more promotion do we need? Are there enough learners and coaches who have signed up?

**Comment by Malwine** [comment]
We have some signups. But I am worried that we only reach the people in our community.
But Clojurebridge is especially about bringing Clojure to people who
- don't know Clojure
- don't know programming
- don't know the tech community in Berlin.

And giving them the opportunity to learn about these things.

**Comment by martinklepsch** [comment]
I'm thinking a Facebook event would help reaching a wider audience maybe? I could create one.

**Comment by Malwine** [comment]
Yeah, that's pretty cool if you could do that. :sunny: :heart:  (I am not there, so I couldn't do it before.)

**Comment by martinklepsch** [comment]
Someone else posted about it in some group as well: https://www.facebook.com/groups/1106085959408694/permalink/1261726380511317/

**Comment by Malwine** [comment]
Please tweet about the event if you can.
Or retweet:
https://twitter.com/ClojureBerlin/status/676741803262025728

**Comment by plexus** [comment]
I've put some emails I've sent to mailing lists in the repo, in case people want some inspiration https://github.com/clojurebridge-berlin/organization/blob/master/email_templates/reachout_emails.md

**Comment by martinklepsch** [comment]
Created a FB event: https://www.facebook.com/events/510385959135087/

Because it's not created by a Facebook Page I cannot add a Tickets link but I will update the copy a bit to make clear that registration via our website is required.

Let me know if you have any suggestions, it's minimal because I didn't want to copy all the information from the website but I guess it's fine?

**Comment by jellea** [comment]
Since signups are closed think we can close this now?
