### ISSUE TITLE
Find 4-5 lightning speakers

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#51]
Speakers to invite with potential topics:
- Tamara or Ariane or Franziska or anyone from the project group, Clojure Project Group
- Johannes, What a Developer Rweally Does
- Coaches

**Comment by Malwine** [comment]
Idea: Somebody from the learning group could talk: Ariane or Franziska?

**Comment by vsmart** [comment]
@Malwine I think that's covered by the first bullet point :) (Tamara is in the learning group - we should ask Ariane too).

**Comment by Malwine** [comment]
@vsmart True. :neckbeard: :trollface:

**Comment by thatbettina** [comment]
I'll ask the project group on Wednesday when I show up there.

Anyone got the contact info for Johannes so that I can ask him if he'd like to give the same lightning talk again?

**Comment by vsmart** [comment]
He will probably be at the project group too. If not, he is on the clojure dojo slack.

**Comment by thatbettina** [comment]
Update on lightning talks: 
Ariane and Julia will give a lightning talk about the project group.
And Johannes will give his lightning talk from ClojureBridge 1 again.
Maybe I should stop by at the beginning of the coaches' training and pitch for more lightning talks?

**Comment by plexus** [comment]
Several coaches proposed a lightning talk on their signup form
- Using ClojureScript in the browser
- FP and composition. *
- What is a virtual machine?
- The Moral Character of Software (based on Phillip Rogaway's recent paper)
- Making a static website with Clojure *
- Threading macros/ higher order functions

just pick the ones you want and contact them directly.

**Comment by thatbettina** [comment]
@plexus Thanks! I have to make sure my old password for the orga account is still correct. 

Is "Threading macros/ higher order functions" a topic that also beginners will understand?

**Comment by thatbettina** [comment]
I'm thinking we each put stars next to talks we think would be cool, because I can realistically invite 3 out of 6 to talk since we have 2 other lightning talks already.

**Comment by plexus** [comment]
> Is "Threading macros/ higher order functions" a topic that also beginners will understand?

Threading macros: yes, higher order functions: probably not

**Comment by vsmart** [comment]
To be honest all of those sound too technical to me. If I was a complete beginner I think that would confuse/intimidate more than inspire&refresh which in my mind is the intention of the lightning talks. Maybe @jellea or someone else would like to do `10 cool things with clojure` or something similar again?  I think that worked well.

**Comment by plexus** [comment]
"Making a static website with Clojure" sounds like a simple and practical topic, as in: something they can actually try at home. Although I don't know what the tools are or how complex it is. That was @martinklepsch topic so maybe he can elaborate :)

**Comment by martinklepsch** [comment]
The idea was to give a short intro to Perun (
https://github.com/hashobject/perun) a static site generator based on Boot
(that however won't be the focus :).

I also think static sites are a nice intro topic and would be happy to come
up with a talk/written guide that people can follow up on later.

**Comment by thatbettina** [comment]
@vsmart I kinda also had the impression that these talks were too technical in the middle of a long day of lots of learning with the exception of 
- FP and composition. *
- The Moral Character of Software (based on Phillip Rogaway's recent paper)
- Making a static website with Clojure *

The functional programming and (music?) composition I thought might be fun with demos.
The moral character one sounds kinda philosophical.
And the static website with Clojure sounds like something a learner could do after our workshop, like here's what's next -- and you could come to our learners' group if you need help.

@martinklepsch Do you think that your topic would be something the learners could try to do by themselves after the workshop?

**Comment by martinklepsch** [comment]
@thatbettina If learners have some basic understanding of HTML/CSS I'm sure they could follow it after the workshop. I'll try to prepare a little repo/instruction thing people can work with after the workshop.
