### ISSUE TITLE
Wunderlist Address 

### ISSUE THREAD

**Issue by andreiursan** [clojurebridge-berlin/organization#53]
In the following registration form: https://docs.google.com/forms/d/1yoZVmo4Z8umpO9hmYB32WBv2Tpmjsgxv3zR5rFspvYA/viewform

Please use Wunderlist as a location. It would also be easier to identify - the only displayed logo at the venue is Wunderlist. As a general rule, you can refer to us as Wunderlist.

current

```
6 Wunderkinder, GmbH Karl-Liebknecht-Straße 32, 10178 Berlin, Germany
```

should be

```
Wunderlist, Karl-Liebknecht-Straße 32, 10178 Berlin, Germany
```

**Comment by plexus** [comment]
:heavy_check_mark:

**Comment by andreiursan** [comment]
thanks :+1: 
btw `GmbH` is not required 
`Wunderlist, GmbH`
