### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#54]
For the workshop lunch I would stick to the same caterer, everybody was very happy with what they brought.

For installfest Malwine suggested we have a warm winter soup to welcome people with, which I think is a great idea. I'll check with the caterer if she can do that as well, otherwise suggestions on where to get it are welcome. 

For coaches training, afternoon snacks, maybe additional installfest  food or for breakfast, I'd like to go with these people http://gregariousmammal.com/services/healthyhackers/

They have some really nice things on offer for a very decent price.

**Comment by thatbettina** [comment]
How's the food ordering going? I like healthy food but we have to have vegan options.

**Comment by Malwine** [comment]
I mailed the soup caterer for the install fest. Soup only is at 380 Euro. Plus dessert it is 480 Euro. I guess we don't take the desserts (I just asked them about it because they are yummi :D )
I will give her a call tomorrow to talk about details.

**Comment by plexus** [comment]
I'll arrange the rest of the food.

**Comment by plexus** [comment]
Here's the quote from the caterer. What do y'all think? 

Price wise it's good, last time we paid 73.80+500+95=€668.80 for coaches training+lunch+cupcakes, so this is cheaper, and we get nice food for the coaches too instead of cheap pizza.

> Menu:  
> Thursday 14th January (for 20 people)    
> 
> • 20 antipasto skewers (V,gf) €28  
> • 30 mini spring vegetable and spinach tarts (V) €42 
> • 30 vegetable frittata slices (v,gf) €42 
> • 1 large Hummus, baba ganoush, , corn chips and vegetable platter (V, gf) €20 
> • 50 x Chocolate raspberry brownie bites  (V) €70 
> 
> (v vegetarian V vegan gf gluten free) 
> 
> €202 plus €10 delivery fee  
> Total: €212 
> 
> Menu  
> Saturday 23rd January (for 60 people) 
> 
> Soups 
> 
> • 35 serves Red bean, quinoa and jerk spice soup for  (V, gf) €52.50 
> • 35 serves Thai lentil soup for 30 (V, gf) €52.50 
> • Mixed bread, rolls  and vegan butter €20.00    
> 
> Sides 
> 
> • Asian coleslaw (V, gf) €25.00 
> • Potato salad  (V, gf) €25.00 
> • Cous cous salad (V, gf) €25.00 
> • Pesto pasta salad (V), €25.00 
> • Dips (Baba ganoush and Hummus) and corn chips (V, gf) €20.00  
> • Mixed cheese platter €25.00 
> 
> Or alternatively to sides, I can do mixed finger food to an equivalent cost e.g. rice paper rolls, frittata, falafels and homemade hummus, spinach tarts 
> 
> Afternoon tea 
> 
> • 40 Chocolate raspberry brownies €45.00 
> • 40 Raw muesli balls €45.00 
> • 2 kg small red apples €6.00 
> • 2 kg small mandarin/clementines €6.00 
> 
> Total plus €10 transport: €382 
> Total for all catering: €594

**Comment by nicsnet** [comment]
Sounds :yum: to me :heart:

**Comment by vsmart** [comment]
Sounds delicious! My only concern is soup twice - friday night _and_ saturday lunch. I like soup though, and there'll be sides, so I think it's ok.

**Comment by plexus** [comment]
Yeah that was my thought as well, but it's pretty "solid" soup (beans, quinoa, lentils) plus with the sides I think it's ok.

**Comment by Malwine** [comment]
@plexus Soup on both days?

**Comment by plexus** [comment]
Alright, not soup then. I'll come up with something else.

**Comment by Malwine** [comment]
Or, we can just have Pizza on Friday! Can we talk on the phone at 11:30 for 5 mins?

**Comment by plexus** [comment]
If we're going to do soup once I think it makes more sense in the evening at the installfest.

I checked with the caterer for an alternative:

> I could do a jamaican gumbo and a texan chilli for the same price with rice (both vegan), or I could do curries.

Go for that then?

@Malwine sure you can call me any time :)

**Comment by Malwine** [comment]
We only need to make sure that is isn't too spicy. Last time some people gave us that as a feedback.

**Comment by thatbettina** [comment]
I could just be speaking for myself, but I wonder if the food will be enough to make people full. I remember at ClojureD they had tons of little finger foods and sides, but somehow it wasn't enough to get me full. I remember I wasn't the only one, so just putting that in as something to consider.

**Comment by vsmart** [comment]
@plexus, I'd say go for the gumbo & chili as lunch. We can ask them to not make it spicy like @Malwine suggested. That should also be super filling @thatbettina.

**Comment by plexus** [comment]
The gumbo and chilli also sounds good to me, and we're ordering for sixty people even though we probably will be fewer. Last time the food was only just enough, I want to make sure it's definitely enough this time.
