### ISSUE TITLE
Venue-related enquiries

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#55]
Please post in here anything you need double checked with WL regarding the venue. 

Is there anything that needs to be prepared in advance, for any of the planned meetups?

**Comment by plexus** [comment]
https://github.com/ClojureBridge/organizing/blob/master/Hosting-venue-questions.md

**Comment by vsmart** [comment]
Thanks arne! do you know if andrei wrote something up for those questions last time? if not I will do it and post it in here.

**Comment by thatbettina** [comment]
Do we have a beamer? 

What did we do for the demo? Were all the projects put on a USB stick or did people plug in their laptops to the beamer? For which we need some cable thingies...

**Comment by vsmart** [comment]
Yea, there's a beamer. We should just be able to plug in a mac. Cables for that are there already.

**Comment by vsmart** [comment]
I've answered most of the questions here https://github.com/clojurebridge-berlin/organization/blob/master/venue.md

**Comment by thatbettina** [comment]
Thanks so much @vsmart 
I'll refer to your blob from now on :)

**Comment by plexus** [comment]
Thanks @vsmart for filling all this out
- keep us posted on the coffee situation. If it's the same as last time we should try to bring a drip coffee maker or moka pots (bialetti) plus ground coffee
- I can bring some extra adapters for the projector: mini-VGA=>VGA, mini-HDMI=>HDMI, DisplayPort=>HDMI, that should leave us well covered

**Comment by vsmart** [comment]
I'm having lunch with our office manager tomorrow where I'll try to get the remaining questions cleared up :) Also regarding coffee + water ( cc @Malwine )

**Comment by plexus** [comment]
Great! I asked what Rails Girls Berlin does regarding insurance, it seems usually the space has insurance that covers things, or they fall under Ruby Berlin e.V. which also has insurance.

**Comment by vsmart** [comment]
as I said in the other issue, WL will provide coffee + bottled water. 
someone is looking into the insurance thing, I'll let you know as soon as I hear back.

**Comment by jellea** [comment]
@vsmart any news on insurance?

**Comment by vsmart** [comment]
unfortunately no clear answers. We couldn't find out what the exact policy is and person who deals with our insurance is on paternity leave at the moment. :/
However I have verbal confirmation that most likely the event is covered by Wunderlist insurance, and we'll have Wunderlist's help to deal with any potential insurance issues as they arrive.
