### ISSUE TITLE
Nonalcoholic Drinks

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#57]
I want to order our drinks asap.

**Last time we had:**
- with caffeine 
  24 bottles FRITZ COLA ZUCKERFREI (sugarfree if diabetes or non sugar person)
  24 bottles FRITZ COLA
  20 bottles CLUB MATE
- without caffeine
  48 bottles FRITZ ZITRONELIMO
  48 bottles ALMDUDLER
  6 (1l) bottles BECKERS BESTER APFELSAFT TRÜB

= **170 bottles**

**What should we change?**
- More Mate?
- No apple juice?
- Less coke?
- more lemonade variety. bionade for example.

**Comment by Malwine** [comment]
We order from BerlinEinkauf.com if you want to have a look at their offer.

**Comment by Malwine** [comment]
@plexus @martinklepsch @jellea @vsmart

**Comment by jellea** [comment]
I remember having too much coke, too less water. Apple juice is ok, but smaller bottles?

**Comment by Malwine** [comment]
Ok, thanks for the tipp. I will try to find smaller apple juice, maybe lemonades.

**Comment by Malwine** [comment]
Water we got from wunderlist. Are they providing it again? @vsmart ?

**Comment by nicsnet** [comment]
How about Apfelschorle, in 0.5 l bottles? And i vote for one extra crate of mate maybe a different type or flavour.

**Comment by Malwine** [comment]
EDIT Jan-12 15:00
My proposal:
- with caffeine  
  FRITZ KOLA 24X0,33
  CLUB MATE 40X0,5
  FRITZ KOLA ZF. 24X0,33L  
- without caffeine  
  BIONADE KRAEUTER 48X0,33L
  VAIHINGER APFELSAFT 24X0,2L 
  BIONADE HOLUNDER 6X0,5L 
  FRITZ ZITRONELIMO 24X0,33L

= 190 Bottles

I am waiting for @vsmart to tell me about **water** at wunderlist. We might buy some too.

**Comment by vsmart** [comment]
Wunderlist will provide water and coffee.

**Comment by Malwine** [comment]
YAY :tada: 
Then I go for more lemonade :tropical_drink:

**Comment by Malwine** [comment]
Maybe we can buy some tea bags too.
The drinks will be ordered these days.

**Comment by jellea** [comment]
@Malwine I presume this won't be for tonight's coaches training, right? @vsmart and I are thinking of picking some drinks up at a spaeti for tonight.

**Comment by plexus** [comment]
Spaeti will be expensive though. I can pass by a supermarket but I can only bring so much. What do we need? Does Wunderlist supply water?

**Comment by Malwine** [comment]
Ow yeah it is only delivered before the day before the workshop.
Last time wunderlist had beers.

**Comment by vsmart** [comment]
Drinks arrived!

**Comment by Malwine** [comment]
@vsmart YAY \o/ Thanks for telling. I already got nervous.
