### ISSUE TITLE
Breakfast

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#58]
Would someone mind taking charge of this?

Last time we ordered 60 croissants for 84 euros from [Brezel Company Berlin](http://shop.brezel-company.eu/) (cfr. [#36](https://github.com/clojurebridge-berlin/organization/issues/36))

The problem with that was that they weren't vegan. Brezel company has a few vegan options

> 101 Laugenbrezel 100g 0,70 €
> 858 Apfel Streusel (vegan) 19,26 €
> 866 Schoko-Kirsch-Streuesel (vegan) 19,26 €

But it's either Laugenbrezel, which might be a bit bland, or ordering what is basically a whole cake/pie, which might not be everyone's thing for breakfast.

@vsmart as the vegan of the group, what's your take on this? Any alternatives that come to mind?

@thatbettina you ordered breakfast last time. Would you have time to do so again this time?

**Comment by thatbettina** [comment]
I can order it unless we have a better alternative.

I think if we order the Laugenbrezel and bring some nice vegan aufstrichen, it would be ok. @vsmart what do you think?

Is it written down anywhere the number of people with dietary wishes and what kind of wishes?

**Comment by vsmart** [comment]
I could try my local lpg bakery tomorrow morning and ask for a quote for breakfast for 60 people. They have the usual stuff but also great vegan baked goods like muffins etc.

**Comment by plexus** [comment]
There's a separate spreadsheet in the Google Drive where you can see who's been invited and who has accepted. That's the only place where you can see the dietary restrictions at the moment. 

IIRC it's only vegetarian/vegan/gluten-free so far.

**Comment by vsmart** [comment]
Stopped by that bakery I was talking about. They do orders. 
Is 1 muffin enough for breakfast? I could order 60 vegan muffins, maybe half chocolate, half carrot-cinnamon. 
 and + 5 gluten-free rolls or something. What do you think? 

ETA: or maybe 30 muffins and 30 rolls or brezels for people who prefer non-sweet breakfast. 

Let me know

**Comment by thatbettina** [comment]
@vsmart I don't have the schedule in front of me, but I think we're serving lunch about 3 hours after breakfast so I think one muffin should be enough. 

The brezel company charges a delivery fee for orders under 40 euros, so I could order about 35 brezeln from them to get our order up to the minimum. Should I go ahead and order a mix of salty brezeln then?

**Comment by vsmart** [comment]
@thatbettina so you will get 35 brezeln from brezel company, and I will order ~35 muffins + 5 gluten free items from "my" bakery (lpg)? 
this bakery is on my way to the office so i would just pick up the muffins myself saturday morning

**Comment by thatbettina** [comment]
I'm thinking 

| Bretzeln | Price |
| --- | --- |
| 10 vegan Laugenbretzeln | 7 Euro |
| 10 pumpkin-seed bretzeln | 11.77 Euros |
| 10 chocolate croissants | 14.45 Euros |
| 8 laugen croissants | 10.70 Euros |

for a total of 43.87 Euros.

ETA: not sure why my table didn't work :(

**Comment by vsmart** [comment]
Looks good. I will order 30 vegan muffins (15 chocolate, 15 carrot-cinnamon) and 5 GF items, then we can call it day. ☑️

I think you need a blank line above your table for it to work.

**Comment by thatbettina** [comment]
Great! Am ordering tonight for delivery at 9:00am on Saturday.

**Comment by vsmart** [comment]
muffins were 49.50 .... a bit pricy ;/ but they  are vegan and bio :apple:

**Comment by plexus** [comment]
That's not going to break the bank :)

Will they also be delivered? Do we pay at delivery time, or do you pay in advance?

Make sure to keep receipts if you pay anything. I'll try to pay back any small expenses already on workshop day.

**Comment by vsmart** [comment]
I will pick them up on saturday morning. The bakery is on my way to the office. 
I paid this morning already and will bring receipt.

@plexus can you let me know how many GF items we need? I would just pick those up that day at the same place.

**Comment by plexus** [comment]
There is one person who filled in gluten-free. Also one person is lactose-intolerant. Probably not an issue but we should be able to tell them if any of the pastries contain milk products.

**Comment by plexus** [comment]
The best would be to prepare pieces of paper like
- [ ] vegetarian
- [ ] vegan
- [ ] gluten-free
- [ ] lactose-free
- [ ] free of nuts, apples, pepper and peaches

so we can just check the right boxes for each thing we serve
