### ISSUE TITLE
Create a Quil cheatsheet

### ISSUE THREAD

**Issue by jellea** [clojurebridge-berlin/organization#59]
Somebody had the good idea of creating a cheatsheet for clojure/quil, to not overload them with too much possibilities.

There's already a start for the Clojure one here: https://github.com/ClojureBridge/curriculum/blob/gh-pages/outline/cheatsheet.md

**Comment by vsmart** [comment]
how about https://learnxinyminutes.com/docs/clojure/ from learn x in y minutes? Or a shortened version of it. 1 a4 page is enough I hope.

**Comment by vsmart** [comment]
Idea / "nice-to-have" we discussed today: get a small cheatsheet to stick into the notebook.
alternatively the a4 version on normal paper to go along with the book is also great.

**Comment by jellea** [comment]
Can print some cheatsheets at home :)
