### ISSUE TITLE
Create Twitter Account

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#6]
London ClojureBridge has one, not sure if we should have one too. Thoughts?

**Comment by plexus** [comment]
The Solingen peeps already created one for "ClojureBridge DE". I guess they
can tweet out our workshop as well :) But we could totally also make a
Berlin specific one.

**Comment by nicsnet** [comment]
How about ClojureBridge Berlin ? or ClojureBridge BER

**Comment by martinklepsch** [comment]
Just came to mind: We could also use the @clojureberlin account.

**Comment by thatbettina** [comment]
Great idea!

**Comment by thatbettina** [comment]
@Malwine As our communicator, I think you should decide which Twitter account you'll tweet from :) What do you think?

**Comment by Malwine** [comment]
I think its best to use @clojureberlin because there are already some followers

**Comment by martinklepsch** [comment]
I'll close this. @Malwine now has access to the account. If anyone else wants, let me know.
