### ISSUE TITLE
After-{Party|Drinks|Dinner}

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#60]
From here https://github.com/clojurebridge-berlin/organization/issues/42

_Afterparty_

```
This is something the ClojureBridge docs mention several times. 
Should we consider picking an "official" venue instead of having people find their own 
way after the workshop?`
```

I suggested [Kaschk](http://www.yelp.com/biz/kaschk-berlin), a coffee shop + craft beer place, since it's fairly spacious and very closeby. 
@plexus pointed out that dinner right after the workshop is probably a better idea as everyone will be super hungry. 

My suggestions - either: 

1) Book ~20 spaces in a nearby restaurant, e.g. [Soy](http://www.soy-berlin.com) a vegan vietnamese place across the street from the office. If people want to go for drinks afterwards it's up to them.
👍 easier to keep a group together
👎 we might not all fit there

or

 2) Let everyone find their own food and agree to reconvene in Kaschk one hour after the end of the workshop. 
👍 easier for us to organise
👍 everyone can get whatever food they like
👎 less people would probably come - most people would leave after food

**Comment by vsmart** [comment]
I guess a combination of both could work too. As in, we book a few seats for dinner, but tell people we'll be in kaschk later anyway.

**Comment by plexus** [comment]
I think letting people find their own way is the most realistic option in this case. Going for dinner with such a big group is a major pain. You never know how many people will really show up, annoying the restaurant, and ordering dinner with 20+ people at the same time means you have to wait forever for your meal. Not to mention the logistics of getting the group to their destination (tip: just getting out of the building will take twice as long as you thought it would take to get to your destination).

We could list up some suggestions though, especially for places around Kaschk, maybe even suggest that people form little groups and make their own reservations.

ArrrrCamp did a pretty cool thing this year, they asked all speakers and attendees if they were interested to join for dinner, then split them into groups and made reservations at a bunch of restaurants, so you each went for dinner with a handful of people, including one or two speakers or organizers. Might be an idea for next time.

Going to Kaschk afterwards is a great idea, but we should notify them beforehand. If all attendees, coaches, and orga show up we'll be around 60 people, so even if only half of them show up it's still a pretty big group.

**Comment by vsmart** [comment]
:cool: - Makes sense. 

I stopped by at Kaschk today. Let them know we'd come around 7.30pm with ~30 people on Saturday. ☑️

List of places we can suggest for dinner: 
- Soy 
- Dolores 
- Madami 
- Kiez Falafel

**Comment by plexus** [comment]
:100:

**Comment by vsmart** [comment]
think this can be closed
