### ISSUE TITLE
Proposed Schedule for the day

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#61]
How about having the same schedule as last time except I'll have two different sessions for the lightning talks?

09:00 – 09:30 Coffee & Registration
09:30 – 09:45 Welcome Talk -- in both German and English?
09:45 – 10:15 Intro to Clojure -- in both German and English?
10:15 – 13:00 Coding in Groups
13:00 – 14:00 Lunch

14:00 – 14:20 3 Lightning Talks
- Jelle: 10 amazing things you can do with Clojure (in 5 minutes) -- not yet confirmed
- Igor: The Moral Character of Software
- Johannes: Advice to burgeoning programmers

14:20 – 17:00 Coding in Groups

17:00 - 17:15 2 Lightning Talks about how to continue
- Martin: Static websites with Clojure
- Ariane & Julia: Clojure Project Group -- not yet confirmed

17:15 – 18:00 Demo of Code 
18:00 Official End of the Workshop - Time to socialize

**Comment by vsmart** [comment]
Looks good! One small thing - maybe move Martin's talk to lunch time and either igor's or johannes' to the evening instead. I think the more technical one at lunch is better, when there's still more capacity to listen left :)

**Comment by thatbettina** [comment]
@vsmart Thanks; good point--I'll check in with @martinklepsch to see if it's technical or inspiring :+1:

**Comment by thatbettina** [comment]
Ok, so here's the schedule then. Any more feedback before I send it out tomorrow?

09:00 – 09:30 Coffee & Registration
09:30 – 09:45 Welcome Talk -- in both German and English?
09:45 – 10:15 Intro to Clojure -- in both German and English?
10:15 – 13:00 Coding in Groups
13:00 – 14:00 Lunch

14:00 – 14:20 3 Lightning Talks

Jelle: 10 amazing things you can do with Clojure (in 5 minutes)
Igor: The Moral Character of Software
Martin: Static websites with Clojure

14:20 – 17:00 Coding in Groups

17:00 - 17:15 2 Lightning Talks about how to continue

Johannes: Advice to burgeoning programmers
Ariane & Julia: Clojure Project Group 
17:15 – 18:00 Demo of Code 
18:00 Official End of the Workshop - Time to socialize

**Comment by vsmart** [comment]
LGTM :tada:

**Comment by plexus** [comment]
I had to Google that. I was like "lesbian gay trans m....?"

**Comment by thatbettina** [comment]
Me too; I had to look it up @plexus I feel old!

**Comment by vsmart** [comment]
Hehe - Whoops! Sorry! It's what I'm used to using on here as a "Good to go!" keyword or signal.
