### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#68]
This is the proposed timeline for the Summer 2016 Workshop.
- Tue 29.03.2016 : Kickoff meeting
- Sun 17.04.2016 : Registration opens
- Mon 18.04.2016 at 19:00: Core Team Meeting I
- Mon 09.05.2016 at 19:00: Core Team Meeting II
- Sun 29.05.2016 : Registration closes / end of fundraising
- Mon 30.05.2016 at 19:00: Core Team Meeting III
- Thu 09.06.2016 : Coaches Training
- Fri 17.06.2016 : InstallFest
- Sat 18.06.2016 : Workshop day
- Sun 26.06.2016 at 12:30 : Retrospective + Jelle's Birthday

Please check your calendars. We can further discuss this tonight at the kick-off meeting.

**Comment by plexus** [comment]
Google calendar link : https://calendar.google.com/calendar/embed?src=Y2xvanVyZWJyaWRnZS5iZXJsaW5AZ21haWwuY29t

**Comment by plexus** [comment]
These dates have been discussed and are final now. Core meetings moved to Mondays.

**Comment by vsmart** [comment]
Update: The retrospective is now at July 5th 7:30pm
