### ISSUE TITLE
Pick a date

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#7]
News from Solingen!

tl;dr: "we can't tell you what date to pick, and doing it on the same date probably won't have much negative effect, but it won't do much good either, and yeah actually really we think it's better to do it on separate dates."

I'm not sure now... I like June or maybe early July as a time frame. Solingen is 12/13 June. Euroclojure is 25/26 June. We definitely don't want to overlap with Euroclojure, and if we want coaches or attendees to potentially do both Solingen and Berlin it also shouldn't be adjacent weekends.

We probably should check if Rails Girls is doing a workshop around that time as well. (ping @nerdbabe)

So main options I see are: same date as Solingen, or first weekend of July. What do you think?

> ---------- Forwarded message ----------
> From: Falko R. <--->
> Date: 2015-03-17 8:57 GMT+01:00
> Subject: ClojureBridge Berlin
> To: arne@...
> Cc: Silvia S. <--->, Gerrit H. <--->
> 
> Hi Arne,
> 
> wir finden das super, dass das in Berlin auch stattfinden soll.
> Und -- vorweg geschrieben -- ihr seid natürlich vollkommen frei, wann
> ihr das durchführt.
> 
> Ich hatte spontan an eine mögliche Kanibalisierung (Coaches,
> Teilnehmerinnen) gedacht, aber die Distanz erscheint mir groß genug.
> Außerdem hatte zB Stefan Kamphausen spontan Interesse an CB bekundet,
> aber die Entfernung von Berlin hält ihn davon ab, in Solingen beizuspringen.
> 
> Silvia hatte da etwas validere Bedenken bzgl. gleicher Termin:
> 
> "Ich sehe keinen direkten Vorteil, wenn es am gleichen Tag stattfindet,
> dafür aber Nachteile.
> 
> An zwei Terminen wird den Teilnehmerinnen ermöglicht in Berlin
> teilzunehmen, die zB in Solingen nicht können und umgekehrt. Vermutlich
> wird es auch in Berlin genug Coaches geben, aber so sind die Coaches
> halt auch definitiv nicht austauschbar und man macht ggf. Fehler am
> gleichen Tag, statt gegenseitig voneinander zu lernen.
> 
> Dass wir uns Teilnehmerinnen wegnehmen, glaube ich auch nicht, aber das
> Angebot wäre halt größer, wenn man verschiedene Termine hat."
> 
> Zwei Veranstaltungstermine = größere Auswahl für Reisewillige ist auf
> jeden Fall ein wichtiger Punkt.
> 
> Wie gesagt: wir können Euch nicht sagen, was ihr tun sollt...
> 
> Grüße
> Falko

**Comment by martinklepsch** [comment]
First weekend in July sounds good to me.

**Comment by plexus** [comment]
Just realized the first weekend of July is Polyconf (http://polyconf.com/). Not necessarily a blocker but something to keep in mind, as it will definitely take away a few potential coaches.

**Comment by nicsnet** [comment]
I attended Polyconf last year and really liked it, it's still on my conference list for 2015 (as well as Euroclojure :) ). So I vote for second week in July 11-12th.

Then we also have more time to organise everything.

**Comment by plexus** [comment]
It's typically an installation party on Friday, and the main workshop on Saturday, so that would be 10/11 July. Those dates would totally work for me.

**Comment by martinklepsch** [comment]
:+1:

**Comment by thatbettina** [comment]
I can do 10/11 July. RailsGirls Berlin is doing a beginners workshop on July 31, FYI.

**Comment by thatbettina** [comment]
Just created a coaches sign-up Google Doc and added a field where coaches can say on which dates they can coach, so that might make the decision easier.

**Comment by thatbettina** [comment]
So July 10/11 is the date!!! 

I will change the info on the Google Form now.
