### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#70]
This is an quite important topic for me. We got just a small amount of feedback the last two times.
Over all people seem to be quite happy with how we do these workshops. But I want to go beyond that.

The next feedback rounds shouldn't be about food, venue etc. 
It should be about topics why people come to us, how we reach them and how to keep them interested in programming.

Questions could be:
- why did you initially join?
- what is your background?
- how did you find us?
- what was especially interesting to you to join clojurenbridge?
- do you want to continue learning [programming, clojure, animation etc.]? and how do you think you will continue?
- what should we have done differently? what was a surprise to you?

Questions for us could be:
- how do we keep people interested?
- is our workshop giving them a real insight in programming? or is it quite tough and not so understandable?
- do people get inspired?

**Comment by Malwine** [comment]
Please feel welcome to discuss and add your ideas!

**Comment by vsmart** [comment]
what do you mean by "the next feedback round"? the first one after the next workshop? or something to send to the wider community? 

but, yes, definite 👍 on getting feedback & taking that more seriously. at the kick-off meeting we discussed getting some initial feedback from participants right before the demo. that could be a good way to hear back from people more reliably.

**Comment by Malwine** [comment]
> what do you mean by "the next feedback round"? the first one after the next workshop? or something to send to the wider community? 

I mean the first one after the next workshop. Or in between.

**Comment by Malwine** [comment]
I started working on the feedback form: https://docs.google.com/forms/d/11Kfb0J8Xxc_zHQU2r49X4G09LS7iCcFrnzsU7gPsV7U/viewform

Suggestions welcome!

**Comment by Malwine** [comment]
We are currently collecting feedback.
