### ISSUE TITLE
Signup Form + Confirmations

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/organization#71]
I created the new form and setup the confirmation email stuff
- [Trello card](https://trello.com/c/eaRGZh0p/2-set-up-attendee-sign-up-form)
- [Form (public)](http://goo.gl/forms/CW2zQ4U2WU)
- [Form (editable)](https://docs.google.com/forms/d/1LpaMVP-F9CTr8FiRsWhoIThxVoNMWFOa6MBUc3WLnW4/edit?usp=forms_home&ths=true)
- [Confirmation Email Template](https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Attendee-Signup-Confirmation-Email)

The form now contains two additional questions: age & participation in previous ClojureBridge workshops.

Few things left to discuss:
1. Didn't yet delete the T-Shirt question — why can't we have T-Shirts?
2. Didn't yet shorten the CC/Photo Permission section
3. Didn't add a "Motivation" question. There's "Is there anything else you like to mention?" so if people are eager to tell they can.

**Comment by jellea** [comment]
Why is age important?
1. Not as practical as for example notebooks. Expensive, lots of work.
2. Linking out to a web page is better probably, also so ppl have a reference after the signup, say during the workshop.

**Comment by vsmart** [comment]
+1 to removing t-shirt stuff. 

also I would suggest 
- removing the OS question. 
- simplifying the programming experience question. Ben made a suggestion at the kick-off that I really liked which was to boil it down to these two questions: 

`a) Have you coded before? 
    b) Have you done clojure before?`

**Comment by plexus** [comment]
> Why is age important?

Quoting @Malwine on Trello:

> This would be good for our statistics and it is important if we do some reach out to younger ones this year. We need to figure out the legal requirements for under aged though.

**Comment by plexus** [comment]
I've expanded the [attendee confirmation email](https://github.com/clojurebridge-berlin/organization/wiki/[email]-Attendee-Signup-Confirmation-Email), but now the translation needs updating.

I wrote a [confirmation email for coaches](https://github.com/clojurebridge-berlin/organization/wiki/[email]-Coach-Signup-Confirmation-Email). Does it need translating?

I removed the t-shirt question from the signup form and shortened the photo license explanation.

**Comment by Malwine** [comment]
@plexus I translated the rest of the attendee mail. But I am not sure if we should send the link to `land of quill`. It can be intimidating to see this bunch of code and not knowing what to do with it. Especially because it has no German translation. **I am for taking it out.**

I think for coaches we don't need a German translation. Most professionals in our fiels know English.

**Comment by Malwine** [comment]
@vsmart About the **experience**. I am for making it shorter but we defintitely need more information. Both questions are yes/no. But to match groups it is very helpful to know more. So I suggest:

a) Have you coded before? `Choose YES / NO`

b) If you answered "yes", please tell us what you did.  `Free field`

b) Have you done clojure before? `Choose YES / NO`

**Comment by jellea** [comment]
Wont b1 answer b2 as well? :)

**Comment by plexus** [comment]
Note that the link is not to the land of quil, but to the beginners introduction.

I think it's good to send people already something they can look at if they like. If there's a better alternative I'm all ears.

**Comment by plexus** [comment]
For the last workshop we had these answers for the experience question
- 31 Beginner
- 2 Intermediate in Clojure
- 28 Intermediate, no Clojure
- 9 Advanced, no Clojure

Maybe we can keep Beginner/Intermediate/Advanced + a separate "Have you done Clojure"?

**Comment by Malwine** [comment]
@plexus I would keep it simple and and leave an open option.
@jellea As I said already it is easier to match groups if you have some more information. E.g. I made groups at the first workshop that had done e.g. some Ruby, Javascript or looked into HTML before.

**Comment by Malwine** [comment]
@martinklepsch Can we please add another question with a free small field: `How did you hear from us?`
I want to do different outreach this year and it would be great to see what works the best.

**Comment by vsmart** [comment]
I made some changes. 
- Removed OS question 
- Added "How did you find out about clojure bridge" 
- Simplified age brackets to (under 18 | 18 - 30 | over 30) 
- Changed experience question to what Malwine suggested here https://github.com/clojurebridge-berlin/organization/issues/71#issuecomment-205206727
- Updated health/disability question
- Various copy edits

Please have another look over the form, and let's get it out soon :)

**Comment by plexus** [comment]
Thank you <3

**Comment by Malwine** [comment]
@vsmart Thank you :heart_eyes:

**Comment by plexus** [comment]
I also set up the coaches form based on the previous coaches form and including a couple things we have in the attendee form (health issues, photo permission)
- [Public form link](https://docs.google.com/forms/d/1Dx4zpnV6DHQNTn3VhLByyE8QbhKt3lKXjhCrlwWSmuQ/viewform)
- [Editable form](https://docs.google.com/forms/d/1Dx4zpnV6DHQNTn3VhLByyE8QbhKt3lKXjhCrlwWSmuQ/edit?usp=drive_web)
- [Trello card](https://trello.com/c/6lF11OMy/3-set-up-coach-sign-up-form)
- [Confirmation email template](https://github.com/clojurebridge-berlin/organization/wiki/[email]-Coach-Signup-Confirmation-Email)

I updated the confirmation emails for both attendees and coaches to be what is currently in the wiki. I took out the link to land-of-quil. I tested the submission, the confirmation emails work fine. 

I think we are ready to launch these into the big wide world!

Small tip when testing these forms: if you simply remove submitted values in the responses spreadsheet then the next time someone submits you get a blank line. Instead what you should do
- In the editable form go to "responses", in the dropdown click "delete all responses"
- In the responses spreadsheets, select the row numbers of the results you want to remove (so the whole row is selected), right click on the row number and choose "delete rows"

Both forms are now in the new Google Forms and owned by ClojureBridge.Berlin, so next time we can more easily duplicate-edit-reuse.

**Comment by vsmart** [comment]
Done 🎉 They are now up on the website.
