### ISSUE TITLE
Respond to Gitter

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#72]
I was introduced to Gitter after the last workshop, and they were interested in sponsoring. This week I got this mail from them.

> I am sorry for following up so late! We are interested in sponsoring the event but we usually sponsor conferences or meetups provided that the group actually uses Gitter as a communication platform - during the event, at least. 
> That's when it makes the most sense for us to sponsor. 
> 
> I just wanted to let you know about that - and looking forward to hearing from you. 

I don't think this adds any value, and we agreed last time not to give sponsors extra perks, since they should really support us for its own sake. So I wrote this reply.

> We have a general policy that sponsors don't get extra perks. ClojureBridge is not a commercial event, it's an attempt at changing the tech scene for the better, and it's 100% run by volunteers. By supporting us companies can show that they actually care about diversity, and put their money where their mouth is. It also means in the long run we help create a bigger and more diverse hiring pool, which benefits you as well.
> 
> We have a swag table at the event where companies can put things like stickers, pens, thumb drives. We also elaborately mention and thank our sponsors on social media, so you can use this to your advantage for public relations.
> 
> Anything else like pitch talks or demos we tend to decline because they create extra distractions in an already overwhelmingly full day.
> 
> I hope you understand,
> Best regards,

I haven't sent it yet, feedback welcome.

**Comment by martinklepsch** [comment]
I think it's great! 👍    💯

**Comment by lislis** [comment]
+1

**Comment by jellea** [comment]
Maybe worth mentioning that most of our first clojurebridge was organised over Gitter? In case all they want is a success story? Feels like the email could be a bit more welcoming that way? :)

**Comment by martinklepsch** [comment]
> Maybe worth mentioning that most of our first clojurebridge was organised over Gitter?

Was it? I don't remember using Gitter for anything ClojureBridge related. (I could totally have forgotton though :)

I see your point in a way but I think Arne's text does a good job at politely explaining the Why behind this policy.

**Comment by jellea** [comment]
Oh sure, just felt it was a bit too negative and it could start with a positive note :)

**Comment by thatbettina** [comment]
Mostly +1 but I'd start with the swag table paragraph regarding what they Do get, then explain why not demos or pitches or other perks. Also I'd change the sentence about the money and mouth like this: "they care about diversity and community enough to support it financially without a specific benefit for the company." The original wording sounds a bit accusatory imp :)

We should also add this info to our sponsor page.

**Comment by thatbettina** [comment]
Yes I agree so I made a suggestion :) remember we DO want sponsors :D

**Comment by Malwine** [comment]
We wrote to them. Can we close this issue? @plexus @vsmart ?

**Comment by plexus** [comment]
yes, I wrote back, but quite late, and they no longer responded.

**Comment by Malwine** [comment]
Well... then I guess we can close this.
