### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#73]
We like to give people something to take home that's also kind of useful. The first time we had t-shirts, the second time we improvised notebooks.

Cognitect said earlier they could sponsor for "something in the €500 range", the only condition is that it's payable by credit card.

I think it would be nice to do notebooks again. One idea is to have them printed with a logo on the front, and for example a clojure/quil cheatsheet on the inner flap.

Somebody would have to research suppliers to see what we can get in that price range, and someone would have to get out their best design skills.

**Comment by Malwine** [comment]
Babbel has ordered our swag! Yay!
