### ISSUE TITLE
Core Meeting I agenda

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#74]
- [x] launch/open the sign-up forms
- organizational stuff
  - keep in touch with volunteers
  - how to hand out tasks
- reach out to new groups
  - facebook groups
  - mailing lists: reflect-info
  - groups like Female Pressure
  - non-internet outreach, e.g. flyers in libraries; posters
  - local radio
  - schools ; universities
- catering
  - one caterer for coaches event + installfest, e.g. sandwiches
  - one caterer for the main event
  - breakfast
  - drinks: wunderlist?
- notebooks
  - try to order online
  - can be covered by Cognitect
  - has to be payable by credit card
- sponsors
  - Tiers
    - €400: coaches training + installfest food
    - €500: notebooks
    - €600: food main event
    - €250: supporter (4?)
  - Three top tiers get mentioned on social media
  - The rest get mentioned in the presentation, on our site, clojurebridge.org, get to put stuff on the swag table
- hand out initial tasks

Tasks

Sponsoring
- [Ben] update the sponsor-us landing page with the sponsor tiers
  - add a step-by-step "how to sponsor through Travis"
- [Arne] check in with Cognitect
- [everyone] think of who to contact for sponsors

Swag
- [Nicola  & Ben] Research and design for notebooks

Reach out
- Announce new workshop on various channels
  - [Ben] writing a template for our own mailing list
  - [Arne] Twitter
  - [Arne] Instagram
  - [Franka] ClojureBridge.org
    - add a template to the wiki
    - create the issue
  - [Ben] write a template for writing to facebook, mailing lists
- [Malwine] Coordinate wider outreach effort 
- [Volunteer] Research what we need to handle -18s; Julia can ask someone from Coder Dojo, also Ellen might know
- [Arne] check what happened with the receipt of the stickers last time
- [Franka] mention on the website that there will be male coaches
- [Arne & Malwine] Coordinate volunteers
- [Arne & Jelle & Julia] Coordinate curriculum effort
- [Tamara] How to improve feedback?

**Comment by vsmart** [comment]
@plexus could you clarify again a bit what's needed for 
`[Franka] ClojureBridge.org |
add a template to the wiki |
create the issue`

specifically - can you link me to the old issue from last time? Thanks!

**Comment by plexus** [comment]
@vsmart it's explained in more detail in this trello ticket https://trello.com/c/bO3EcZhD/11-make-template-in-wiki-for-clojurebridge-workshops-issue
