### ISSUE TITLE
Wider outreach effort

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#75]
We would like to reach untapped audiences.

Put all your ideas here!

Some ideas mentioned at the first core meeting
- facebook groups
- mailing lists: reflect-info
- groups like Female Pressure
- non-internet outreach, e.g. flyers in libraries; posters
- local radio
- schools ; universities

Concretely
- [x] reflect-info mailing list

**Comment by socksy** [comment]
Queer Exchange Berlin FB Group? https://www.facebook.com/groups/1504213836509257/

**Comment by Malwine** [comment]
**For the record**
Find the files for our posters and flyers below.

[flyer-final.pdf](https://github.com/clojurebridge-berlin/organization/files/250641/flyer-final.pdf)
[poster-final.pdf](https://github.com/clojurebridge-berlin/organization/files/255446/poster-final.pdf)

**Comment by martinklepsch** [comment]
Just to keep things documented: I reached out to [Mit Vergnügen](http://mitvergnuegen.com/) and will update here once I know more.

**Comment by Malwine** [comment]
Started to spread the posters at FU.
There is a Trello [task](https://trello.com/c/MVP6TxHg/23-distribute-flyers-and-posters-collection-of-venues) with venues for posters.

**Comment by Malwine** [comment]
We did well with the outreach this year. 
Closing it as we hit the 100 application mark.
