### ISSUE TITLE
Description of the target group

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#77]
Background: during organization of the previous workshop there was some discussion about who this workshop is for, and how we phrase that in our materials. 

IIRC correctly the consensus was to be inclusive without making it too complicated, i.e. we describe our target group as "women or those who identify as women".

Unfortunately this didn't result in a visible change, so e.g. the website still just says "women" without qualifying this. 

I had a look at what other chapters are doing. Most just use the standard ClojureBridge boilerplate, but I found a few other examples (see below).

This is what I'm proposing. I'm including "nonbinary", which I _think_ would include e.g. genderqueer, genderfluid, agender. (We already had one nonbinary person sign up for this workshop).

> ClojureBridge Berlin is a free Clojure programming workshop for women*. Especially for those with just a little or no programming experience.
> 
> \* We are offing this workshop to help make the Clojure community more accessible to a diverse range of participants. As such, registration is open to people who identify as a woman or have a nonbinary gender identity.

_Questions:_
- is that good enough as a starting point? We can dig into this deeper at the next core meeting, but I'd like to submit our text for ClojureBridge.org today
- is there a German equivalent for "nonbinary"?

_For reference:_

---

> **http://clojurebridge-berlin.github.io/**
> 
> **EN** ClojureBridge is a free Clojure programming workshop for women. Especially for those with just a little or no programming experience.
> **DE** ClojureBridge ist ein kostenloser Programmier-Workshop für Frauen. Besonders für diejenigen mit keiner oder wenig Erfahrung im Programmieren. 

---

> **ClojureBridge standard boilerplate**
> 
> This workshop is intended to reach out to women who are new to Clojure. To register, you must identify as a woman. Men, you are welcome to come if you find a woman who wants to learn Clojure who will register and bring you as a guest.

---

> **ClojureBridge London, February 2016**
> 
> We're offing this workshop to help make the Clojure community more accessible to a diverse range of participants. As such, this event is only welcoming participants who identify as female or nonbinary. Males may register as a guest of one of these participants.

---

> **ClojureBridge Edinburgh, September 2014**
> 
> This free workshop is open to anyone who was assigned female at birth and anyone who identifies as a woman, genderqueer, genderfluid, or genderfree regardless of gender presentation or assigned sex at birth.  It is suitable for beginner to intermediate programmers who have no previous experience of Clojure.

---

**Comment by vsmart** [comment]
@plexus thanks for raising these important questions. 👍 

I definitely want to make it more clear that trans folks, genderqueer, agender, & intersex people are welcome. I don't think just saying `women` makes that clear. 

In German space I often see the description FLTI: (Frauen, Lesben, Trans- & Intersex) 

Taken from [here](http://nonbinary.org/wiki/Glossary_of_German_gender_and_sex_terminology#F)

```
FLTI - "Frauen, Lesben, Inter*, Trans*": "women, lesbians, intersex- & trans people"
 is often used to describe the groups invited to a certain event or location.
 Often with * placed after the T and/or I, sometimes without mentioning intersex as "FLT".

 Ideally means "everyone except non-intersex cis men", but since these evolved from
 women-only spaces, results vary and the reality can be exlusive of
 some trans and intersex people.
```

for me, either we include (everyone who identifies as women + genderqueer folx), or everyone but cis men (e.g. also including trans men...stepping away from "clojure workshop for women"...)
in which case it's pretty important to also change the way we talk about the workshop in general. i.e. stop advertising it as `workshop for women`.
