### ISSUE TITLE
Non-alcoholic Drinks

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#78]
Not so much a discussion point, just to let you know: 

Microsoft/Wunderlist will provide:
- coffee
- tea
- water (sparkling/still) 
- bionade
- fanta/cola/sprite
- lift apfelschorle 

These are the drinks we have in the office anyway. Additionally we will order:
- a crate of Club Mate.

**Comment by Malwine** [comment]
It would be good to have a range of drinks:
- with / without coffein
- with sugar / without sugar
- with gas / without gas

**Comment by Malwine** [comment]
Last year, just for the numbers:

```
with caffeine

FRITZ KOLA 24X0,33
CLUB MATE 40X0,5
FRITZ KOLA ZF. 24X0,33L

without caffeine

BIONADE KRAEUTER 48X0,33L
VAIHINGER APFELSAFT 24X0,2L
BIONADE HOLUNDER 6X0,5L
FRITZ ZITRONELIMO 24X0,33L

= 190 Bottles
```

**Comment by Malwine** [comment]
If everything is ordered we could close this issue, can't we @vsmart ?

**Comment by vsmart** [comment]
Yep
