### ISSUE TITLE
Coaches Outreach

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/organization#79]
I really hope we can get some more women coaches this time. It's good to have them there for the participants to see & it stops this weird dynamic of all-men coaches, all-women students. 

what we've tried so far: 
- [x] women who code berlin meetup announcement
- [x] clojure dojo meetup 
- [x] email to lambda-ladies mailing list 
- [x] women in tech slack 
- [ ] .... ?

It'd be cool if we can all speak to other women engineers we know, they don't have to be clojure experts to coach.

**Comment by Malwine** [comment]
We should discuss to invite women coaches from other cities. Maybe we can help cover some travel costs. Will explain this tonight.

**Comment by vsmart** [comment]
I think the conclusion was that we can do the invite & cover plan tickets. So are you planning on inviting Eleonore @Malwine? :)

**Comment by Malwine** [comment]
@vsmart We are in touch about it.

**Comment by Malwine** [comment]
Our coaches are confirmed. Good ratio of women this year! Well done! 👏
