### ISSUE TITLE
Set up an announcement list

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#8]
It would be good to set up a mailing list that interested parties can subscribe to. IIRC you can get free mailing lists from mailchimp. They're great, simple and reliable.

If we can already start pointing people there this will make gathering attendees and coaches easier in the future. I already have a handful of email addresses to start with :)

**Comment by martinklepsch** [comment]
Alternatively maybe Google Groups? Also Tinyletter could just work fine.

**Comment by plexus** [comment]
I would avoid Google Groups. a) because I would avoid it in general, and b) because this is strictly intended as an announcement list, not a discussion list.

I didn't know Tinyletter, at first glance it looks like it would fit the bill as well.

**Comment by martinklepsch** [comment]
@plexus I see the point of it being an announcement list but I believe you can get to a similar effect by restricting who can post. I'd consider it a good thing having a list of announcements available via some web interface, which would be harder to achieve with newsletter style solutions.

It's nothing I consider worth arguing about though so please feel free to proceed whatever you feel is right.

**Comment by thatbettina** [comment]
What about whoever assigns themselves this issue and gets it done can decide?

**Comment by plexus** [comment]
Ah of course, Eurucamp. So they won't do much in June /July.

**Comment by plexus** [comment]
To some extent we have clojureverse for this now. It only includes alumni and coaches, but it should be good enough for getting the word out.
