### ISSUE TITLE
Email for reflect-info Mailing list

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#81]
I've drafted what I'd like to send to the reflect-info list, and would gladly take feedback. It's also not specific to this list, so when done I'll add it to the wiki email templates.

> Hello lovely people,
> 
> We'd love to invite you to our free workshop for women\* to learn programming. It's called ClojureBridge, and aimed at complete beginners. We'll be working with a unique technology called Clojure that can be used to create anything you want in the digital sphere. We'll aim to make some animated visuals by the end of the day long workshop.
> 
> The event will be on Friday 17th June in the evening and Saturday 18th June for the day. We'd be splitting into small groups with a couple of (possibly male) coaches and then regrouping in the evening to show each other what we've achieved.
> 
> The workshop is entirely free of charge, and breakfast, lunch, and soft drinks will be provided.
> 
> Sign up now: https://docs.google.com/forms/d/1LpaMVP-F9CTr8FiRsWhoIThxVoNMWFOa6MBUc3WLnW4/viewform?c=0&w=1
> More information: https://clojurebridge-berlin.github.io/

Und auf Deutsch:

> Hallo liebe leute!
> 
> Wir würden euch gerne zu unserem kostenlosen Programmier- Workshop für Frauen\* einladen. Es heißt ClojureBridge und richtet sich an komplette Anfänger. Wir werden mit einer einzigartigen Programmiersprache names Clojure arbeiten, die man nutzen kann um fast alles in der digitalen Sphäre zu schaffen. Das Ziel ist es, dass ihr bis zum Ende des Tages animierte Grafiken erstellen könnt.
> 
> Das Ereignis wird Freitagabend 17 Juni und am Samstag 18 Juni stattfinden. Wir werden uns in kleine Gruppen mit ein paar Coaches (möglicherweise männliche Coaches) aufteilen, und uns am Abend wieder treffen um einander zu zeigen was wir erreicht haben. 
> 
> Der Workshop ist komplett kostenlos, und Frühstück, Mittagsessen und alkoholfreie Getränke werden gestellt.
> 
> Jetzt hier anmelden: https://docs.google.com/forms/d/1LpaMVP-F9CTr8FiRsWhoIThxVoNMWFOa6MBUc3WLnW4/viewform?c=0&w=1 
> Mehr Informationen: https://clojurebridge-berlin.github.io/

Credits to Romina for proofreading and correcting my atrocious German.

**Comment by plexus** [comment]
Hey @socksy I think this looks pretty good!

**Comment by nicsnet** [comment]
> Es heißt ClojureBridge
> -> Er heißt ClojureBridge (der Workshop)
> Anfänger
> -> Anfängerinnen
> 
>  Wir werden uns in kleine Gruppe
> -> Wir werden uns in kleinen Gruppen
> 
> möglicherweise männliche Coaches
> -> möglicherweise männlichen Coaches

**Comment by nicsnet** [comment]
I would change

> wir erreicht haben
> to 
> -> wir geschafft haben (less performance pressure)

**Comment by Malwine** [comment]
> This is my proposal.

Hallo liebe Leute!

Wir würden euch gerne zu unserem kostenlosen Programmier-Workshop für Frauen\* einladen. Dieser Workshop heißt ClojureBridge und richtet sich an komplette Anfängerinnen. Wir werden mit der einzigartigen Programmiersprache Clojure arbeiten, die ihr nutzen könnt, um fast alles in der digitalen Welt zu realisieren. Das Ziel ist es, dass ihr bis zum Ende des Tages animierte Grafiken erstellen könnt.

Der Workshop wird Freitag (Abend), den 17 Juni und am Samstag, den 18 Juni 2016 stattfinden. Wir werden uns in kleine Gruppen mit ein paar Coaches (möglicherweise männliche Coaches) aufteilen und uns Nachmittags wieder treffen, um einander zu zeigen, was wir gebaut haben.

Der Workshop ist komplett kostenlos, und Frühstück, Mittagsessen und alkoholfreie Getränke werden gestellt.

**Comment by vsmart** [comment]
@Malwine 2 small things: "und !veganes! Frühstück, Mittagsessen" + ich würde das "einzigartig" vor Clojure entfernen

**Comment by socksy** [comment]
ok final version:

> Hallo liebe leute!
> 
> Wir würden euch gerne zu unserem kostenlosen Programmier-Workshop für Frauen\* einladen. Dieser Workshop heißt ClojureBridge und richtet sich an komplette Anfängerinnen. Wir werden mit der Programmiersprache Clojure arbeiten, die ihr nutzen könnt, um fast alles in der digitalen Welt zu realisieren. Das Ziel ist es, dass ihr bis zum Ende des Tages animierte Grafiken erstellen könnt.
> 
> Der Workshop wird Freitag (Abend), den 17 Juni und am Samstag, den 18 Juni 2016 stattfinden. Wir werden uns in kleine Gruppen mit ein paar Coaches (möglicherweise männliche Coaches) aufteilen und uns Nachmittags wieder treffen, um einander zu zeigen, was wir gebaut haben.
> 
> Der Workshop ist komplett kostenlos, und veganes Frühstück, Mittagsessen und alkoholfreie Getränke werden gestellt.
> 
> Jetzt hier anmelden: https://docs.google.com/forms/d/1LpaMVP-F9CTr8FiRsWhoIThxVoNMWFOa6MBUc3WLnW4/viewform?c=0&w=1
> Mehr Informationen: https://clojurebridge-berlin.github.io/
> 
> ---
> 
> Hello lovely people,
> 
> We'd love to invite you to our free workshop for women\* to learn programming. It's called ClojureBridge, and aimed at complete beginners. We'll be working with a unique technology called Clojure that can be used to create anything you want in the digital sphere. We'll aim to make some animated visuals by the end of the day long workshop.
> 
> The event will be on Friday 17th June in the evening and Saturday 18th June for the day. We'd be splitting into small groups with a couple of (possibly male) coaches and then regrouping in the evening to show each other what we've achieved.
> 
> The workshop is entirely free of charge, and a vegan breakfast and lunch will be provided along with soft drinks.
> 
> Sign up now: https://docs.google.com/forms/d/1LpaMVP-F9CTr8FiRsWhoIThxVoNMWFOa6MBUc3WLnW4/viewform?c=0&w=1
> More information: https://clojurebridge-berlin.github.io/

**Comment by Malwine** [comment]
@socksy 

> Hallo liebe leute!

Leute is a noun and should be upcase. So: **Hallo liebe Leute!**
Other than that it is fine. Thank you for all the effort.

**Comment by Malwine** [comment]
Very well done by @socksy !
Many sign ups from the list! 💯

**Comment by vsmart** [comment]
that's awesome! @Malwine @socksy
