### ISSUE TITLE
Speakers & Lightning Talks

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#83]
@lislis 
We are looking for female speakers especially (role models!). We should have a good range between German and English talks.

Confirmed speakers:
- [Sara](https://twitter.com/sareg0) | EN | Topic to be announced
- [Lisa](https://lislis.de/) | DE | Making Games
- [Julia](https://twitter.com/anderspree) | EN/DE | The Learners Group
- Lan Anh | DE | Informatik-Studium an der HTW / _Study Computer Science at HTW_
- [Jelle](https://twitter.com/jellea) | EN | 10 things you can do with Clojure (inspirational)
- Wilhelmina | EN | Social transformation with Computer Science

**Comment by lislis** [comment]
I could talk about making games. In German or English or both (!?)

**Comment by jellea** [comment]
Think it would be cool to have a talk in German this time! :)

**Comment by Malwine** [comment]
@lislis confirmed 🔥

**Comment by lislis** [comment]
awesome!

**Comment by Malwine** [comment]
New speakers: Julia and Lan Anh! 🎉

**Comment by jellea** [comment]
Just a thought: how about doing an inspirational talk (or two) during Installfest? Since a lot of ppl are done so quickly... and it spreads the cognitive load a bit more over the weekend.

**Comment by Malwine** [comment]
@jellea I would love to have you talking about the 10 things you can do with clojure! Do you like to do that?

**Comment by jellea** [comment]
I can, but lets see if we can go all female role models first? :D Wdyt about talks during installfest?

**Comment by Malwine** [comment]
@jellea I would actually love to have it Saturday morning after the intro. And maybe on Friday we can have another women speaking.

**Comment by Malwine** [comment]
Speaker @jellea confirmed ✨

**Comment by sareg0** [comment]
I will be talking about learning to code; my story as a case study of the variety of routes there are into coding even if you don't have a formal education

**Comment by Malwine** [comment]
Thank you @sareg0 for letting us know :) Thats great!

**Comment by Malwine** [comment]
Wilhelmina as a speaker confirmed!!! 🎉 💯

**Comment by Malwine** [comment]
Speaker diversity and all women setup was nice. 
We will improve the speaker briefing next time.

**Comment by jellea** [comment]
Loved the talks @Malwine! Thanks!
