### ISSUE TITLE
Catering / Breakfast / Cupcakes

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#84]
I got in touch with the caterer from last time (Cate Lawrence). She will do coaches training, installfest, and workshop lunch. She's working on a proposal. She has a budget of 900€ available, which she will invoice directly to Cognitect (500) and SoundCloud Women in Engineering.

Breakfast and Cupcakes we'll order ourselves and get them refunded through Travis Foundation.

**Comment by vsmart** [comment]
Can we close this one? @nicsnet @plexus

**Comment by vsmart** [comment]
OK, I will order 40 muffins and 40 pretzel/breadroll/other stuff at the bakery tomorrow

**Comment by vsmart** [comment]
Got cupcakes covered, catering covered, and I will buy breakfast tomorrow

**Comment by vsmart** [comment]
Update: bought 30 chocolate muffins, 30 carrot cake muffins, 30 vollkornbrötchen and I will pick them up saturday morning
