### ISSUE TITLE
Hackday on {{date}} 🎉

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#88]
Hello dear friends!

Last meeting we came up with the idea to do a hackday! YAY! \o/ 🎉 🍹 💻 🙋 👲 🆑 💕 

I hope we'll find a date in August or September to get together for one Saturday and hack on ideas to make our orga process easier and nicer.
### Topics:
- documentation: 
  - how to document? 
  - how to find and use existing documentation? 
  - how to report back and help the board
- create a timeline to help newbies what has to be done and **when**
- create a application process app: Issue https://github.com/clojurebridge-berlin/organization/issues/87

Please add more topics and ideas to this issue!

**Comment by Realtin** [comment]
Possible Dates:

**August:**
- 6.08
- 13.08
- 20.08
- 27.08

**September**
- 3.09
- ~~10.09~~ [ClojuTRE!]
- 17.09 [we might have already started prepping the next workshop]
- 24.09

**Comment by lislis** [comment]
How about hacking on the app during the Euroclojure week?
