### ISSUE TITLE
Summerteam - Winterteam ? 

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#89]
I wanted to open an discussion about the idea we came up with in the meeting about having a summer and a winter team. 

For me personally the winter is the most busy time and summer is better for me. But I heard other team members preferring the winter. So maybe we can get an idea here who is up for winter or summer?

**Comment by Malwine** [comment]
Malwine = Summer ✅

**Comment by lislis** [comment]
Lisa = Winter

**Comment by vsmart** [comment]
i slightly prefer `winter` as usually summer is busier for me. 
not a strong preference though. (especially since prep for summer happens in spring, really).

**Comment by Realtin** [comment]
Julia = Winter

**Comment by plexus** [comment]
I will still do this winter edition, and take a break next summer.

I don't think we have to force people to choose one of the two though. The main point is that it should be accepted and encouraged for people to regularly take a break.

The kick-off meeting is on September 15. If you know anyone that you think would make a good ClojureBridge organizer then maybe ask them if they like to join that meeting.

**Comment by Malwine** [comment]
I think you're right @plexus 
So I am closing this for now :)
