### ISSUE TITLE
Coach training pre-workshop!

### ISSUE THREAD

**Issue by thatbettina** [clojurebridge-berlin/organization#9]
I'm going through the Google Group for ClojureBridge organizers, and it's highly recommended that coaches go through coach training (esp. if we accept absolute beginners to programming) before the workshop to learn some basics about how to teach and coach. 

I quote: "It has a few parts that are RailsBridge-specific but most of it is about how to encourage a safe, welcoming environment for learning, and how to ensure TAs are prepared to help everyone get the most out of the workshop: how to get students engaged, how to deal with potential issues before they escalate, how to make sure everyone is happy and learning, and not getting frustrated. 

Yes, it's yet one more thing to organize on everyone's calendar, and it means one more space to find a host for and more food/drink to pay for but it really is absolutely worth the effort! Trust me, it made a huge difference for us in San Francisco!"

They use this deck: http://docs.railsbridge.org/workshop/more_teacher_training

More info here: https://groups.google.com/forum/#!topic/clojurebridge-workshops/6SdqNVGN1Ss

**Comment by Malwine** [comment]
:+1:

**Comment by Malwine** [comment]
We need to set a date!

**Comment by Malwine** [comment]
I like the RailsBridge Deck!!

Also we should prepare coaches to questions from attendees like:
- Why should I learn functional programming/Clojure?
- What is the difference to other programming languages? (Java/Ruby/C++ etc.)
- What can I do with Clojure?
- Which learning-resources can you recommend me?
  - Clojurescript Koans
  - Clojure for the True and Brave
  - Joy of Clojure?

**Comment by thatbettina** [comment]
@martinklepsch - Soundcloud has a dev who wants to coach. I asked the person to sign up via the Google Form so keep an eye out for that so that you can invite the coach to your training please.

**Comment by Malwine** [comment]
@martinklepsch Did you roughly decide on a date? Or are there dates that are most accepted?

**Comment by plexus** [comment]
Looking at the doodle, there are several dates with 12 "accepted"
- Wednesday 3 June
- Tuesday 9
- Wednesday 10
- Thursday 11
- Friday 12
- Monday 15

**Comment by martinklepsch** [comment]
I've been a bit busy lately sorry for the delay on this. 

I just sent out an Email to all coaches. Settled on 11.06.

It'd be great if someone could help (or take over) organisation of it. I've been occupied with other stuff (which also caused the delay on this) and need to organise the coming Clojure meetup as well.

**Comment by Malwine** [comment]
@jellea Are you out with your garden? Then we need to ask @andreiursan if we can do it in 6w.
Did you think about the location, @martinklepsch ?

I can help/take over the preparation/presentation of the content of the workshop. 
Already have some ideas. But we need to be **some people there**. I cannot do it alone.

**Comment by plexus** [comment]
I'll be there. Can help prepping as well.

**Comment by Malwine** [comment]
@plexus 
So I would propose to have Pizza before the presentation.
And maybe a small break in between?

**Comment by plexus** [comment]
@martinklepsch so I'll just order a bunch of pizza's for tonight? How many people are we expecting?

**Comment by martinklepsch** [comment]
@plexus There are 20 registered people: http://www.meetup.com/de/Clojure-Berlin/events/223009586/
I expect that 2-3 might not show up but not more (hopefully).

**Comment by martinklepsch** [comment]
@plexus @andreiursan would like to have a rough ETA so he can prepare. Please let him know.

**Comment by plexus** [comment]
@andreiursan I hope to get there between 18:30 and 19:00 so I still have a few minutes to check the place out and set up. Will order the food for 19:30. What about you @malwine?

**Comment by Malwine** [comment]
What is an ETA?
Will be there around 18:30 too.

**Comment by plexus** [comment]
Estimated Time of Arrival :smile:

**Comment by Malwine** [comment]
:expressionless:

**Comment by Malwine** [comment]
The workshop was given with positive result and feedback. 
Was absolutely worth it.
