### ISSUE TITLE
Timeline 

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#91]
- Wk 0: 12-18 September
  - Wed 15.09.2016 : Kickoff meeting
- Wk 1: 19-25 September
- Wk 2: 26 September - 2 October
  - Registration opens
- Wk 3: 3 October - 9 October
  - Thu 06.10.2016 at 19:00: Core Team Meeting
- Wk 4: 10 October - 16 October
- Wk 5: 17 October - 23 October
  - Mon 17.10.2016 at 19:00: Core Team Meeting
- Wk 6: 24 October - 30 October
- Wk 7: 31 October - 6 November
  - Registration closes
- Wk 8: 7 November - 13 November
  - Mon 07.11.2016 at 19:00: Core Team Meeting
- Wk 9: 14 November - 20 November
  - Thu 17.11.2016 : Coaches Training
- Wk 10: 21 November - 27 November
  - Mon 21.11.2016 : Core Team Meeting
  - Fri 25.11.2016 : InstallFest
  - Sat 26.11.2016 : Workshop day
- Wk 12
  - Mon 5.12.2016 Retrospective
- Wk ?
  - Team Dinner

**Comment by vsmart** [comment]
I will be away all of September so I'd miss the kickoff & first core meeting. Any chance we could push the first core meeting back a week?

**Comment by plexus** [comment]
I'm ok with that. Do keep in mind that we already are giving ourselves less time than last time. I'm sure our well-oiled machine can handle that, just something to be aware of.

What are people's opinions on the retrospective and team dinner? Here are my thoughts...
- I think it's important to do both a formal retrospective, and an informal "let's celebrate we did it again" thing
- retrospective works best if it's very soon after the workshop, so it's still fresh, and so we can truly round up and put it behind us
- celebratory dinner can be bit later so everyone has gotten some time to relax
- I'd like to do retrospective early December, the week after the workshop, maybe on a weekday. Not sure how others would feel about that, I understand from previous meetings people consider December off-limits due to end-of-year engagements
- we could do the celebrations a couple weeks into January, so people have had a chance to recover from Sylvester ;)
- we didn't do any celebratory thing yet for the last workshop. maybe we should? September seems pretty packed already, but maybe October?

**Comment by plexus** [comment]
@socksy you took some notes of when various things happened last time, is there anything you would already put in the timeline up-front?

**Comment by socksy** [comment]
Last time, first thing we did was confirm the venue for sure, 3/4 days after the kickoff meeting. Then we redrafted the sign up form and opened applications (by having "apply now") on the website 2 weeks later. This was all sorted out before the first core meeting.

**Comment by plexus** [comment]
@vsmart seems 3 October doesn't work for several people. We're moving it to Thursday 6 October. I hope that works for you!

**Comment by vsmart** [comment]
Closing the "proposal" issue. Moved to [wiki](https://github.com/clojurebridge-berlin/organization/wiki/November-2016:-Timeline) for documentation.
