### ISSUE TITLE
Kick-off meeting

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#92]
Will happen Thursday 15 September at Babbel, invitation has gone out through the mailing list.

http://eepurl.com/ceFSRs

Agenda
- presentation about ClojureBridge and ClojureBridge Berlin (need to see if I find my slides from last time)
- discuss & approve the proposed Timeline (#91)
- introductions, discussion, etc. 

The only "formal" agenda item is the timeline, we start organizing for real at the first core meeting.

I'd like to order some food, nothing fancy. Suggestions welcome.

Can people with past orga experience who plan to be there please raise their hand? We might need a few people to make sure everyone is properly welcomed and made to feel at home.

**Comment by Realtin** [comment]
✋

**Comment by socksy** [comment]
I'm against having a presentation. Seemed a bit over the top last time, and I don't think we have so many people that talking to them 1-1 isn't a more effective information imparting strategy.

**Comment by plexus** [comment]
Fine by me not to have a presentation, as it's less work. How do other people feel about this? I can see a risk of having too little structure to the meeting, making newcomers feel disoriented. 

So what's the alternative? We do a round of introductions and then just chat, take questions, etc?

**Comment by vsmart** [comment]
@plexus @socksy Are there any notes from the kick-off?
