### ISSUE TITLE
Pair organizing

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#93]
This idea has been brought up before, but I'm not sure if it was generally liked or not, so putting it here for discussion. Could be good if we could get a bit of input on this before the kick-off.

The idea is to pair up new organizers/volunteers with past organizers. This person can make sure they get introduced to Github, Slack, Trello, the Wiki, and general "way of working" stuff. From listening to people who joined for the second or third workshop it seems this is all pretty hard to figure out alone.

This would also create an opportunity to better document things, based on the actual questions you get.

This could also be a way for past organizers to stay involved in a lesser way, i.e. no longer being part of core, potentially not doing any actual "organizing", but merely being a guide/mentor for someone else.

Thoughts?

**Comment by socksy** [comment]
Assuming this is a good idea, here is a table that people can edit themselves to:

| Pair Member 1 | Pair Member 2 | Area of interest |
| --- | --- | --- |
| @nicsnet (Nicola) |  |  |
| @jellea (Jelle) |  | Learners group |
| @Realtin (Julia) |  |  |
| @lislis (Lisa) |  |  |
| @vsmart (Franks) | @codebeige (Tibor) |  |
| @plexus (Arne) | @lithop (Yulia) | Finances, sponsoring, attendee care |
| @socksy (Ben) | @sklind (Saskia) | Not design |

This leaves @codebeige (Tibor) and Kate. @nicsnet, can you add Kate to the orga [here](https://github.com/orgs/clojurebridge-berlin/people)?

People feel free to merge rows too. And to edit this comment accordingly.

**Comment by vsmart** [comment]
I'll be pairing with Tibor and I assume that Kate will pair Nicola. Closing this. 🎉
