### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by plexus** [clojurebridge-berlin/organization#94]
Using mailchimp with a GMail address may cause mails to end up in the spam box, so I went ahead and registered clojurebridge-berlin.org.

For reference:
- clojurebridge-berlin.org points to GH pages
- info@clojurebridge-berlin.org redirects to the GMail account

The domain name is registered at DNSimple in my name, it's 14 USD/year, I'll add it to the rest of my expenses for Travis Foundation after the workshop.

The redirecting is done through Mailgun, with a new clojurebridge.berlin account. It's free up to 10'000 emails per month, and its easy to use API might come in handy for the attendees app.

**Comment by Malwine** [comment]
Perfect @plexus Thank you very much!

**Comment by socksy** [comment]
Is this set up so we can email from gmail using this account?

**Comment by plexus** [comment]
No, if you want to email from this account you need to use a local client like thunderbird. Ping my if you want the credentials.

**Comment by vsmart** [comment]
Thanks again for this @plexus 👏 ❤️
