### ISSUE TITLE
Speakers & Lightning Talks (November)

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/organization#95]
This issue collects our Saturday Lightning talk speakers. You can propose speakers here and set them on the confirmed list, once they confirmed.
- **Possible Topics:** Clojure, personal tech story, Inspirational, Learning to learn, Learners group, open tech initiatives, Study computer science, how to continue... etc.
- **Special focus:** We are looking for female speakers and people of color. 
- **Language:** We should have a good range between German and English talks.
- **Rewards:** We do offer the attendance for the workshop as a reward for the talk. Other than that speakers get food and merchandise and :heart: . 

🅰️ Action point from the retro: Improve speaker briefing concerning usage of conscious language and imagery. 

### Confirmed speakers 

* [Bettina](https://twitter.com/ThatBettina) | EN | Cool things you can do with Clojure
* [Jenny](https://twitter.com/twojing) | EN | This is professionalism
* [Malwine](https://twitter.com/malweene) | DE/EN? | Was möglich ist 👀
* [Ellen](https://twitter.com/ellen_koenig) + Ariane | EN + DE | Intro to the Learning Group
* [Laura](https://twitter.com/lauralindal) | DE/EN? | Empowerment
* [Jessica](https://twitter.com/jjordan_dev) | EN| My journey into coding

**Comment by Malwine** [comment]
Btw, I just opened the issue because I met Claudina and Kriesse the other day. Please feel welcome to take over the topic (as I won't) and continue however you want 😊

**Comment by Realtin** [comment]
- ~~Sara R. DE/EN~~
- Johannes EN

**Comment by vsmart** [comment]
Good news! I invited my colleague Jenny (twojing on Twitter) who is an amazing human & has speaking experience, and she's interested and will give a talk ✨

**Comment by Realtin** [comment]
Great! everyone I talked to yet has turned me down :(
@vsmart you know the Topic of the Talk?

**Comment by Malwine** [comment]
@Realtin Don't be sad, dear! We'll figure it out. ❤️  I asked Claudina and Kriesse again and am waiting for their answer. And I might set myself on the list. Topic might be `different technologies overview` or `growth/fixed mindset`. Whatever fits better with the other speakers.

**Comment by Malwine** [comment]
Unfortunately Kriesse is out due to holidays but she recommended another speaker. I wrote a message and cc'd you, @Realtin

**Comment by vsmart** [comment]
I've invited [Ellen](https://twitter.com/ellen_koenig) to give a talk on the learning group.

Update: Ellen confirmed 🎉 but we're looking for a second person to do the talk in German and English

**Comment by jellea** [comment]
I'm happy to handover my links for the 10 awesome things with Clojure talk if lack of content/idea/preperation time is the reason for not giving a talk ;)

**Comment by Malwine** [comment]
Laura from RailsGirls would give a talk. I sold my soul for it.

**Comment by vsmart** [comment]
hahaha @Malwine. Great 👏 Can I add her to the confirmed speaker list? (at the top)

**Comment by vsmart** [comment]
@Realtin did you hear back from Jordan whether she will make it? :)

**Comment by vsmart** [comment]
I've made some updates to the speaker prep email [here](https://github.com/clojurebridge-berlin/organization/wiki/%5Bemail%5D-Speakers-Preparation) and prepared a speaker sign up form. will send out tomorrow, any comments welcome. :)

**Comment by Realtin** [comment]
yes she is booking her travel now

**Comment by vsmart** [comment]
much success with the speakers ✨ i left a doc here: https://github.com/clojurebridge-berlin/organization/blob/master/documents/nov2016-speakers.md
