### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by socksy** [clojurebridge-berlin/organization#99]
To be done after #97. Needed:
- Update dates
- Remove mailing list button
- Fix nightcode link
- Link to new Sign-Up form, ala [this](https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/18)

**Comment by Realtin** [comment]
Link to the Coaches Form: https://goo.gl/forms/K62AAYVYdwDScFmM2

**Comment by vsmart** [comment]
Done 🎉 in https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/32
